{"metadata":{"title":"appearanceValue(for:whenContainedIn:selector:)","role":"symbol","roleHeading":"Type Method","symbolKind":"method","externalID":"c:objc(cs)ZDKUIUtil(cm)appearanceValueForClass:whenContainedIn:selector:","navigatorTitle":[{"text":"appearanceValueForClass:whenContainedIn:selector:","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearanceValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"!, "},{"text":"whenContainedIn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIAppearanceContainer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIAppearanceContainer"},{"kind":"text","text":".Type!, "},{"text":"selector","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier","text":"Selector"},{"text":"!) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"!","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:whencontainedin:selector:)"]},{"paths":["\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:whencontainedin:selector:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:whenContainedIn:selector:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appearanceValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewClass"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"whenContainedIn"},{"text":" ","kind":"text"},{"text":"containerClass","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIAppearanceContainer","preciseIdentifier":"c:objc(pl)UIAppearanceContainer","kind":"typeIdentifier"},{"kind":"text","text":".Type!, "},{"text":"selector","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The appearance value will come from this class.","type":"text"}],"type":"paragraph"}],"name":"viewClass"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The containing class.","type":"text"}]}],"name":"containerClass"},{"name":"selector","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The appearance selector"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"An appearance value or nil if none have been set."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]]},"abstract":[{"text":"Get the UI_APPEARANCE_SELECTOR value for a class when contained in a given class","type":"text"}],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"role":"symbol","abstract":[],"title":"ZDKUIUtil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIUtil","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkuiutil","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKUIUtil"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/appearanceValue(for:whenContainedIn:selector:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:whenContainedIn:selector:)","abstract":[{"type":"text","text":"Get the UI_APPEARANCE_SELECTOR value for a class when contained in a given class"}],"url":"\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:whencontainedin:selector:)","navigatorTitle":[{"kind":"identifier","text":"appearanceValueForClass:whenContainedIn:selector:"}],"role":"symbol","type":"topic","title":"appearanceValue(for:whenContainedIn:selector:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appearanceValue"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"whenContainedIn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIAppearanceContainer","kind":"typeIdentifier","text":"UIAppearanceContainer"},{"kind":"text","text":".Type!, "},{"kind":"externalParam","text":"selector"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"appearanceValueForClass:whenContainedIn:selector:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appearanceValueForClass:whenContainedIn:selector:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"appearanceValueForClass:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:@T@Class"},{"kind":"text","text":") "},{"text":"viewClass","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"whenContainedIn:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Class<UIAppearanceContainer>","preciseIdentifier":"c:QOobjc(pl)UIAppearanceContainer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"containerClass"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selector:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:e","text":"SEL"},{"text":" *) ","kind":"text"},{"text":"selector","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"ZDKUIUtil","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments","value":[{"text":"ZDKUIUtil","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:whenContainedIn:selector:)\/title","op":"replace","value":"appearanceValueForClass:whenContainedIn:selector:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:whenContainedIn:selector:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appearanceValueForClass:whenContainedIn:selector:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}