{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appearanceValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The appearance value will come from this view."}],"type":"paragraph"}],"name":"view"},{"name":"selector","content":[{"inlineContent":[{"text":"The appearance selector.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The appearance value or nil if none has been set."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-4i9sm"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"appearanceValueForView:selector:"}],"title":"appearanceValue(for:selector:)","externalID":"c:objc(cs)ZDKUIUtil(cm)appearanceValueForView:selector:","modules":[{"name":"SupportSDK"}],"symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appearanceValue"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"text":"selector","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"kind":"keyword","text":"Any"},{"text":"!","kind":"text"}],"role":"symbol"},"abstract":[{"type":"text","text":"Gets the UI_APPEARANCE_SELECTOR value for a view."}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-4i9sm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-4i9sm"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/appearanceValue(for:selector:)-4i9sm":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appearanceValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"selector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"appearanceValueForView:selector:","kind":"identifier"}],"title":"appearanceValue(for:selector:)","url":"\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-4i9sm","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-4i9sm","abstract":[{"text":"Gets the UI_APPEARANCE_SELECTOR value for a view.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"role":"symbol","abstract":[],"title":"ZDKUIUtil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIUtil","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkuiutil","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKUIUtil"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"appearanceValueForView:selector:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appearanceValueForView:selector:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"appearanceValueForView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"view"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selector:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:e","text":"SEL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"selector"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-4i9sm\/title","op":"replace","value":"appearanceValueForView:selector:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-4i9sm\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"appearanceValueForView:selector:"}]},{"op":"replace","value":"ZDKUIUtil","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKUIUtil"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}