{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkuiutil\/currentinterfaceorientation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkuiutil\/currentinterfaceorientation()"]}],"abstract":[{"text":"Returns current interface orientation. If orientation is unknown presume portrait","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]]},"metadata":{"title":"currentInterfaceOrientation()","navigatorTitle":[{"text":"currentInterfaceOrientation","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"SupportSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentInterfaceOrientation","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation","text":"UIInterfaceOrientation"}],"externalID":"c:objc(cs)ZDKUIUtil(cm)currentInterfaceOrientation"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/currentInterfaceOrientation()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentInterfaceOrientation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation","text":"UIInterfaceOrientation"}],"languages":["swift"]}]},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Current interface orientation","type":"text"}]}],"kind":"content"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/currentInterfaceOrientation()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/currentInterfaceOrientation()","title":"currentInterfaceOrientation()","navigatorTitle":[{"text":"currentInterfaceOrientation","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns current interface orientation. If orientation is unknown presume portrait"}],"url":"\/documentation\/supportsdk\/zdkuiutil\/currentinterfaceorientation()","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentInterfaceOrientation"},{"text":"() -> ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"}],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"role":"symbol","abstract":[],"title":"ZDKUIUtil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIUtil","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkuiutil","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKUIUtil"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"currentInterfaceOrientation","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"currentInterfaceOrientation","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation","text":"UIInterfaceOrientation"},{"text":") ","kind":"text"},{"kind":"identifier","text":"currentInterfaceOrientation"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"currentInterfaceOrientation","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1currentInterfaceOrientation()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1currentInterfaceOrientation()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"currentInterfaceOrientation","kind":"identifier"}]},{"op":"replace","value":"ZDKUIUtil","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments","value":[{"kind":"identifier","text":"ZDKUIUtil"}]}]}]}