{"metadata":{"externalID":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate(im)conversationsBarButtonLocalizedLabel","symbolKind":"method","role":"symbol","modules":[{"name":"SupportSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"}],"title":"conversationsBarButtonLocalizedLabel()","roleHeading":"Instance Method","platforms":[]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonLocalizedLabel()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonlocalizedlabel()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonlocalizedlabel()"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationsBarButtonLocalizedLabel"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"A localized string for the right nav bar button.","type":"text"}],"type":"paragraph"}]}],"deprecationSummary":[{"inlineContent":[{"text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens ","type":"text"}],"type":"paragraph"}],"sections":[],"abstract":[{"text":"To conform implementations should return a localized string for the right nav bar button title.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/conversationsBarButtonLocalizedLabel()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonLocalizedLabel()","navigatorTitle":[{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonlocalizedlabel()","role":"symbol","kind":"symbol","deprecated":true,"type":"topic","title":"conversationsBarButtonLocalizedLabel()","abstract":[{"type":"text","text":"To conform implementations should return a localized string for the right nav bar button title."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"abstract":[],"role":"symbol","deprecated":true,"title":"ZDKHelpCenterConversationsUIDelegate","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"conversationsBarButtonLocalizedLabel","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"conversationsBarButtonLocalizedLabel"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonLocalizedLabel()\/title","op":"replace","value":"conversationsBarButtonLocalizedLabel"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonLocalizedLabel()\/fragments"},{"value":"ZDKHelpCenterConversationsUIDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}]}]}]}