{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/navItem"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/willDismiss()"],"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate"},"kind":"symbol","sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController"],"title":"Conforming Types","type":"conformingTypes","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKContainerChildControllerDelegate) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContainerChildControllerDelegate"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/containerchildcontrollerdelegate"]},{"paths":["\/documentation\/supportsdk\/containerchildcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"ContainerChildControllerDelegate","navigatorTitle":[{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"role":"symbol","externalID":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContainerChildControllerDelegate"}],"url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","kind":"symbol","role":"symbol","title":"ContainerChildControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"ContainerChildControllerDelegate"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerViewController"}],"url":"\/documentation\/supportsdk\/containerviewcontroller","kind":"symbol","role":"symbol","title":"ContainerViewController","navigatorTitle":[{"kind":"identifier","text":"ContainerViewController"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate/willDismiss()":{"abstract":[],"kind":"symbol","type":"topic","title":"willDismiss()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/willDismiss()","required":true,"url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate\/willdismiss()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"willDismiss"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismiss"},{"text":"()","kind":"text"}]},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CoordinatingViewController"}],"url":"\/documentation\/supportsdk\/coordinatingviewcontroller","kind":"symbol","role":"symbol","title":"CoordinatingViewController","navigatorTitle":[{"kind":"identifier","text":"CoordinatingViewController"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate/navItem":{"title":"navItem","url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate\/navitem","required":true,"navigatorTitle":[{"kind":"identifier","text":"navItem"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navItem","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"kind":"text","text":"?"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/navItem","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"ZDKContainerChildControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"}]},{"value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/navItem"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/willDismiss()"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforming Types","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController"],"type":"conformingTypes","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title","value":"ZDKContainerChildControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/title","value":"ContainerViewController"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/fragments","op":"replace","value":[{"text":"ContainerViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate~1willDismiss()\/title","value":"willDismiss"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willDismiss"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate~1willDismiss()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/title","value":"ZDKCoordinatingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/fragments","value":[{"kind":"identifier","text":"ZDKCoordinatingViewController"}]},{"value":"navItem","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate~1navItem\/title"},{"value":[{"text":"navItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate~1navItem\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}