{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/coordinator"]},{"paths":["\/documentation\/supportsdk\/coordinator"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator\/start(present:with:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKCoordinator) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"metadata":{"symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"SupportSDK"}],"role":"symbol","title":"Coordinator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(pl)ZDKCoordinator"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformingTypes","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator"],"title":"Conforming Types","kind":"relationships"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator":{"abstract":[],"kind":"symbol","url":"\/documentation\/supportsdk\/coordinator","title":"Coordinator","type":"topic","role":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"Coordinator","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HelpCenterCoordinator","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterCoordinator","kind":"identifier"}],"title":"HelpCenterCoordinator","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","url":"\/documentation\/supportsdk\/helpcentercoordinator"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator/start(present:with:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/supportsdk\/coordinator\/start(present:with:)","title":"start(present:with:)","type":"topic","required":true,"role":"symbol","navigatorTitle":[{"text":"startWithPresent:with:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"text":"present","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","text":"ContainerChildController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier","text":"ContainerChildControllerDelegate"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator\/start(present:with:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestCoordinator":{"role":"symbol","url":"\/documentation\/supportsdk\/requestcoordinator","type":"topic","title":"RequestCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RequestCoordinator","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"RequestCoordinator","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"ZDKCoordinator","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKCoordinator","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKCoordinator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator\/start(present:with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator"],"kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKCoordinator"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/title","value":"ZDKCoordinator"},{"value":[{"text":"ZDKCoordinator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/title","op":"replace","value":"ZDKHelpCenterCoordinator"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterCoordinator","kind":"identifier"}]},{"value":"startWithPresent:with:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator~1start(present:with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator~1start(present:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithPresent:with:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/title","value":"RequestCoordinator"},{"value":[{"kind":"identifier","text":"RequestCoordinator"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/fragments","op":"replace"}]}]}