{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger"},"variants":[{"paths":["\/documentation\/supportsdk\/suasdebuglogger"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/suasdebuglogger"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"]}],"abstract":[{"type":"text","text":"Used to enable "},{"identifier":"https:\/\/github.com\/zendesk\/Suas-iOS","type":"reference","isActive":true},{"type":"text","text":" logging."},{"type":"text","text":" "},{"text":"Suas drives most of the Ticketing UI so the Suas logs can be useful for debugging it.","type":"text"},{"type":"text","text":" "},{"text":"Enabling the Suas logger produces a lot of information and will slow down the SDK.","type":"text"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger\/enabled"],"title":"Type Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKSuasDebugLogger) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SuasDebugLogger"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"name":"Version","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"style":"note","type":"aside"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"metadata":{"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"SuasDebugLogger","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SuasDebugLogger","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"title":"SuasDebugLogger","roleHeading":"Class","externalID":"c:@M@SupportSDK@objc(cs)ZDKSuasDebugLogger"},"references":{"doc://com.zendesk.SupportSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"https://github.com/zendesk/Suas-iOS":{"type":"link","titleInlineContent":[{"type":"text","text":"Suas"}],"url":"https:\/\/github.com\/zendesk\/Suas-iOS","title":"Suas","identifier":"https:\/\/github.com\/zendesk\/Suas-iOS"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger/enabled":{"navigatorTitle":[{"text":"enabled","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger\/enabled","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Toggle the Suas debug logging"}],"kind":"symbol","title":"enabled","type":"topic","url":"\/documentation\/supportsdk\/suasdebuglogger\/enabled"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSuasDebugLogger/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSuasDebugLogger\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"kind":"symbol","title":"init","type":"topic","url":"\/documentation\/supportsdk\/zdksuasdebuglogger\/init"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger":{"navigatorTitle":[{"kind":"identifier","text":"SuasDebugLogger"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SuasDebugLogger","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Used to enable "},{"type":"reference","identifier":"https:\/\/github.com\/zendesk\/Suas-iOS","isActive":true},{"type":"text","text":" logging."},{"type":"text","text":" "},{"type":"text","text":"Suas drives most of the Ticketing UI so the Suas logs can be useful for debugging it."},{"type":"text","text":" "},{"type":"text","text":"Enabling the Suas logger produces a lot of information and will slow down the SDK."}],"title":"SuasDebugLogger","type":"topic","url":"\/documentation\/supportsdk\/suasdebuglogger"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"ZDKSuasDebugLogger","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKSuasDebugLogger"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ZDKSuasDebugLogger","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSuasDebugLogger\/init"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger\/enabled"],"title":"Type Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKSuasDebugLogger","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger~1enabled\/title","value":"enabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger~1enabled\/fragments","value":[{"kind":"identifier","text":"enabled"}]},{"value":"ZDKSuasDebugLogger","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/fragments","value":[{"text":"ZDKSuasDebugLogger","kind":"identifier"}],"op":"replace"}]}]}