{"metadata":{"externalID":"c:objc(pl)ZDKHelpCenterArticleRatingHandlerProtocol","symbolKind":"protocol","modules":[{"name":"SupportSDK"}],"title":"ZDKHelpCenterArticleRatingHandlerProtocol","role":"symbol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterArticleRatingHandlerProtocol"}],"navigatorTitle":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/articleRatingVoteSelected(_:at:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/currentArticleVote()"],"title":"Instance Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformingTypes","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler"],"title":"Conforming Types","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterArticleRatingHandlerProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingHandlerProtocol":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol","url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol","type":"topic","kind":"symbol","role":"symbol","title":"ZDKHelpCenterArticleRatingHandlerProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingHandlerProtocol/currentArticleVote()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/currentArticleVote()","url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol\/currentarticlevote()","kind":"symbol","type":"topic","role":"symbol","title":"currentArticleVote()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentArticleVote","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"currentArticleVote"}],"required":true},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingHandlerProtocol/articleRatingVoteSelected(_:at:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/articleRatingVoteSelected(_:at:)","url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol\/articleratingvoteselected(_:at:)","kind":"symbol","type":"topic","role":"symbol","title":"articleRatingVoteSelected(_:at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"articleRatingVoteSelected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol","text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"articleRatingVoteSelected:atIndex:"}],"required":true},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"type":"topic","role":"symbol","kind":"symbol","title":"HelpCenterArticleVotingHandler","url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler","navigatorTitle":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"ZDKHelpCenterArticleRatingHandlerProtocol","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/articleRatingVoteSelected(_:at:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/currentArticleVote()"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforming Types","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler"],"type":"conformingTypes","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"ZDKHelpCenterArticleRatingHandlerProtocol","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/title"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingHandlerProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol~1currentArticleVote()\/title","value":"currentArticleVote","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol~1currentArticleVote()\/fragments","value":[{"kind":"text","text":"- "},{"text":"currentArticleVote","kind":"identifier"}]},{"value":"articleRatingVoteSelected:atIndex:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol~1articleRatingVoteSelected(_:at:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol~1articleRatingVoteSelected(_:at:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/title","value":"HelpCenterArticleVotingHandler","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/fragments"}]}]}