{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/emptyHelpCenter","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidCategoryIds","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidSectionIds","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/noArticlesForLabels"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/Equatable-Implementations","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/RawRepresentable-Implementations"]}],"abstract":[{"type":"text","text":"Help Center error codes."}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcentererror"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererror"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@E@ZDKHelpCenterError","modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterError"}],"title":"ZDKHelpCenterError","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterError","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterError","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/SY","doc:\/\/com.zendesk.SupportSDK\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError":{"abstract":[{"text":"Help Center error codes.","type":"text"}],"kind":"symbol","type":"topic","title":"ZDKHelpCenterError","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentererror","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterError"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterError"}]},"doc://com.zendesk.SupportSDK/SY":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/invalidCategoryIds":{"abstract":[{"text":"Category ids were not found in Help Center.","type":"text"}],"kind":"symbol","type":"topic","title":"ZDKHelpCenterError.invalidCategoryIds","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidCategoryIds","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/invalidcategoryids","navigatorTitle":[{"text":"ZDKHelpCenterErrorInvalidCategoryIds","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidCategoryIds"}]},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/init(rawValue:)":{"abstract":[],"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]},"doc://com.zendesk.SupportSDK/s8SendableP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/RawRepresentable-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/rawrepresentable-implementations"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/supportsdk\/zdkhelpcentererror\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/Equatable-Implementations","kind":"article"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/invalidSectionIds":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidSectionIds","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/invalidsectionids","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterErrorInvalidSectionIds"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSectionIds"}],"abstract":[{"type":"text","text":"Section ids were not found in Help Center."}],"title":"ZDKHelpCenterError.invalidSectionIds"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/noArticlesForLabels":{"kind":"symbol","title":"ZDKHelpCenterError.noArticlesForLabels","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/noArticlesForLabels","abstract":[{"type":"text","text":"No articles were found with the specified labels."}],"type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/noarticlesforlabels","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"noArticlesForLabels","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterErrorNoArticlesForLabels","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/emptyHelpCenter":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/emptyHelpCenter","title":"ZDKHelpCenterError.emptyHelpCenter","abstract":[{"text":"Help Center has no content.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterErrorEmptyHelpCenter","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyHelpCenter"}],"type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/emptyhelpcenter"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterError"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKHelpCenterError","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/emptyHelpCenter","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidCategoryIds","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidSectionIds","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/noArticlesForLabels"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterError","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/title","op":"replace","value":"ZDKHelpCenterError"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterError"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/fragments"},{"value":"ZDKHelpCenterErrorInvalidCategoryIds","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidCategoryIds\/title"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterErrorInvalidCategoryIds"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidCategoryIds\/fragments","op":"replace"},{"value":"ZDKHelpCenterErrorInvalidSectionIds","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidSectionIds\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidSectionIds\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterErrorInvalidSectionIds"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1noArticlesForLabels\/title","op":"replace","value":"ZDKHelpCenterErrorNoArticlesForLabels"},{"value":[{"text":"ZDKHelpCenterErrorNoArticlesForLabels","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1noArticlesForLabels\/fragments","op":"replace"},{"op":"replace","value":"ZDKHelpCenterErrorEmptyHelpCenter","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1emptyHelpCenter\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1emptyHelpCenter\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterErrorEmptyHelpCenter"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}