{"variants":[{"paths":["\/documentation\/supportsdk\/zdkuiscreenframe()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkuiscreenframe()"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"ZDKUIScreenFrame","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKUIScreenFrame"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"role":"symbol","externalID":"c:ZDKUIUtil.h@F@ZDKUIScreenFrame","roleHeading":"Function","modules":[{"name":"SupportSDK"}],"title":"ZDKUIScreenFrame()","symbolKind":"func"},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIScreenFrame()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Returns the full screen frame with no attempt to account for the status bar.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIScreenFrame","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"url":"\/documentation\/supportsdk","kind":"symbol","role":"collection","title":"SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIScreenFrame()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIScreenFrame()","type":"topic","abstract":[{"text":"Returns the full screen frame with no attempt to account for the status bar.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIScreenFrame"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"url":"\/documentation\/supportsdk\/zdkuiscreenframe()","kind":"symbol","role":"symbol","title":"ZDKUIScreenFrame()","navigatorTitle":[{"text":"ZDKUIScreenFrame","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"value":"ZDKUIScreenFrame","op":"replace","path":"\/metadata\/title"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKUIScreenFrame","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIScreenFrame"},{"text":"()","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIScreenFrame()\/title","value":"ZDKUIScreenFrame"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIScreenFrame()\/fragments","value":[{"kind":"identifier","text":"ZDKUIScreenFrame"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}