{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKUIUtil"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkuiutil"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkuiutil"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"},"metadata":{"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIUtil"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","title":"ZDKUIUtil","externalID":"c:objc(cs)ZDKUIUtil","navigatorTitle":[{"text":"ZDKUIUtil","kind":"identifier"}]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-1dn96","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-4i9sm","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:whenContainedIn:selector:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/buildButton(withFrame:andTitle:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/currentInterfaceOrientation()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/fixOrientation(of:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isLandscape()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isNewerVersion(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isOlderVersion(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isPad()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isSameVersion(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/scaledHeight(for:constrainedByWidth:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/separatorHeightForScreenScale()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/shouldEnableAttachments(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/isPad()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isPad"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPad","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isPad()","url":"\/documentation\/supportsdk\/zdkuiutil\/ispad()","title":"isPad()","abstract":[{"text":"<#Description#>","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/fixOrientation(of:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/fixOrientation(of:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fixOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"!","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"fixOrientation(of:)","url":"\/documentation\/supportsdk\/zdkuiutil\/fixorientation(of:)","navigatorTitle":[{"kind":"identifier","text":"fixOrientationOfImage:"}],"abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/isOlderVersion(_:)":{"role":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil\/isolderversion(_:)","navigatorTitle":[{"kind":"identifier","text":"isOlderVersion:"}],"kind":"symbol","abstract":[{"type":"text","text":"Checks to see if the majorVersionNumber is less than the current device version"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isOlderVersion","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isOlderVersion(_:)","title":"isOlderVersion(_:)"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/shouldEnableAttachments(_:)":{"title":"shouldEnableAttachments(_:)","role":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil\/shouldenableattachments(_:)","type":"topic","abstract":[{"text":"Checks if the host app is a landscape only app and will enable or disable the attachments","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"button accordingly."}],"navigatorTitle":[{"kind":"identifier","text":"shouldEnableAttachments:"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldEnableAttachments","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/shouldEnableAttachments(_:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/appearanceValue(for:whenContainedIn:selector:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"appearanceValueForClass:whenContainedIn:selector:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appearanceValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"whenContainedIn"},{"kind":"text","text":": "},{"text":"UIAppearanceContainer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIAppearanceContainer"},{"kind":"text","text":".Type!, "},{"kind":"externalParam","text":"selector"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:whencontainedin:selector:)","abstract":[{"type":"text","text":"Get the UI_APPEARANCE_SELECTOR value for a class when contained in a given class"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:whenContainedIn:selector:)","title":"appearanceValue(for:whenContainedIn:selector:)"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/buildButton(withFrame:andTitle:)":{"role":"symbol","abstract":[{"text":"Convenience method for creating UIButton.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"buildButton","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withFrame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!) -> "},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"title":"buildButton(withFrame:andTitle:)","navigatorTitle":[{"kind":"identifier","text":"buildButtonWithFrame:andTitle:"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/buildButton(withFrame:andTitle:)","type":"topic","kind":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil\/buildbutton(withframe:andtitle:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/isLandscape()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLandscape","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isLandscape()","navigatorTitle":[{"kind":"identifier","text":"isLandscape"}],"url":"\/documentation\/supportsdk\/zdkuiutil\/islandscape()","abstract":[{"type":"text","text":"<#Description#>"}],"type":"topic","title":"isLandscape()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/isSameVersion(_:)":{"abstract":[{"text":"isSameVersion checks to see if the majorVersionNumber is the same as the current device version","type":"text"}],"type":"topic","title":"isSameVersion(_:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isSameVersion(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil\/issameversion(_:)","navigatorTitle":[{"text":"isSameVersion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSameVersion","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/currentInterfaceOrientation()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/currentInterfaceOrientation()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentInterfaceOrientation"},{"text":"() -> ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"}],"type":"topic","role":"symbol","kind":"symbol","title":"currentInterfaceOrientation()","url":"\/documentation\/supportsdk\/zdkuiutil\/currentinterfaceorientation()","navigatorTitle":[{"kind":"identifier","text":"currentInterfaceOrientation"}],"abstract":[{"type":"text","text":"Returns current interface orientation. If orientation is unknown presume portrait"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/separatorHeightForScreenScale()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"separatorHeightForScreenScale"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"separatorHeightForScreenScale","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/separatorHeightForScreenScale()","url":"\/documentation\/supportsdk\/zdkuiutil\/separatorheightforscreenscale()","title":"separatorHeightForScreenScale()","abstract":[{"text":"The height of a separator for retina and none retina screens.","type":"text"}]},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/isNewerVersion(_:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isNewerVersion(_:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNewerVersion"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","role":"symbol","kind":"symbol","title":"isNewerVersion(_:)","url":"\/documentation\/supportsdk\/zdkuiutil\/isnewerversion(_:)","navigatorTitle":[{"text":"isNewerVersion:","kind":"identifier"}],"abstract":[{"type":"text","text":"isNewVersion checks to see if the majorVersionNumber is greater than the current device version"}]},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/appearanceValue(for:selector:)-4i9sm":{"abstract":[{"type":"text","text":"Gets the UI_APPEARANCE_SELECTOR value for a view."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-4i9sm","type":"topic","title":"appearanceValue(for:selector:)","role":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-4i9sm","navigatorTitle":[{"kind":"identifier","text":"appearanceValueForView:selector:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appearanceValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!, "},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/scaledHeight(for:constrainedByWidth:)":{"navigatorTitle":[{"kind":"identifier","text":"scaledHeightForSize:constrainedByWidth:"}],"url":"\/documentation\/supportsdk\/zdkuiutil\/scaledheight(for:constrainedbywidth:)","kind":"symbol","abstract":[{"text":"<#Description#>","type":"text"}],"title":"scaledHeight(for:constrainedByWidth:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/scaledHeight(for:constrainedByWidth:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaledHeight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"constrainedByWidth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"abstract":[],"type":"topic","title":"ZDKUIUtil","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil","navigatorTitle":[{"kind":"identifier","text":"ZDKUIUtil"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIUtil"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/appearanceValue(for:selector:)-1dn96":{"title":"appearanceValue(for:selector:)","role":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-1dn96","type":"topic","abstract":[{"type":"text","text":"Gets the UI_APPEARANCE_SELECTOR value for a class."}],"navigatorTitle":[{"kind":"identifier","text":"appearanceValueForClass:selector:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appearanceValue"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"selector","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"text":"!) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-1dn96"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKUIUtil"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKUIUtil","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKUIUtil","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-1dn96","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-4i9sm","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:whenContainedIn:selector:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/buildButton(withFrame:andTitle:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/currentInterfaceOrientation()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/fixOrientation(of:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isLandscape()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isNewerVersion(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isOlderVersion(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isPad()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/isSameVersion(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/scaledHeight(for:constrainedByWidth:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/separatorHeightForScreenScale()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/shouldEnableAttachments(_:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIUtil","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isPad()\/title","value":"isPad","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isPad()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"isPad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1fixOrientation(of:)\/title","value":"fixOrientationOfImage:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1fixOrientation(of:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fixOrientationOfImage:","kind":"identifier"}]},{"op":"replace","value":"isOlderVersion:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isOlderVersion(_:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"isOlderVersion:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isOlderVersion(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1shouldEnableAttachments(_:)\/title","op":"replace","value":"shouldEnableAttachments:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1shouldEnableAttachments(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"shouldEnableAttachments:"}]},{"op":"replace","value":"appearanceValueForClass:whenContainedIn:selector:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:whenContainedIn:selector:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"appearanceValueForClass:whenContainedIn:selector:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:whenContainedIn:selector:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1buildButton(withFrame:andTitle:)\/title","value":"buildButtonWithFrame:andTitle:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildButtonWithFrame:andTitle:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1buildButton(withFrame:andTitle:)\/fragments"},{"op":"replace","value":"isLandscape","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isLandscape()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isLandscape()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isLandscape","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isSameVersion(_:)\/title","op":"replace","value":"isSameVersion:"},{"value":[{"text":"+ ","kind":"text"},{"text":"isSameVersion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isSameVersion(_:)\/fragments","op":"replace"},{"op":"replace","value":"currentInterfaceOrientation","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1currentInterfaceOrientation()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1currentInterfaceOrientation()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"currentInterfaceOrientation"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1separatorHeightForScreenScale()\/title","value":"separatorHeightForScreenScale","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1separatorHeightForScreenScale()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"separatorHeightForScreenScale"}]},{"op":"replace","value":"isNewerVersion:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isNewerVersion(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1isNewerVersion(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"isNewerVersion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-4i9sm\/title","op":"replace","value":"appearanceValueForView:selector:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-4i9sm\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appearanceValueForView:selector:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1scaledHeight(for:constrainedByWidth:)\/title","value":"scaledHeightForSize:constrainedByWidth:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1scaledHeight(for:constrainedByWidth:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"scaledHeightForSize:constrainedByWidth:","kind":"identifier"}],"op":"replace"},{"value":"ZDKUIUtil","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments","value":[{"text":"ZDKUIUtil","kind":"identifier"}]},{"value":"appearanceValueForClass:selector:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-1dn96\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-1dn96\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appearanceValueForClass:selector:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}