{"variants":[{"paths":["\/documentation\/supportsdk\/zduispinner"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zduispinner"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDUISpinner","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Spinner creation block."}],"metadata":{"roleHeading":"Type Alias","title":"ZDUISpinner","modules":[{"name":"SupportSDK"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDUISpinner","kind":"identifier"}],"externalID":"c:ZDKSpinnerDelegate.h@T@ZDUISpinner","navigatorTitle":[{"text":"ZDUISpinner","kind":"identifier"}],"role":"symbol","symbolKind":"typealias"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDUISpinner"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"text":"ZDKSpinnerDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKSpinnerDelegate"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"rect for the spinner","type":"text"}],"type":"paragraph"}],"name":"frame"}],"kind":"parameters"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate","type":"topic","title":"ZDKSpinnerDelegate","url":"\/documentation\/supportsdk\/zdkspinnerdelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"abstract":[{"text":"Spinner control delegate.","type":"text"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDUISpinner":{"kind":"symbol","title":"ZDUISpinner","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDUISpinner","abstract":[{"text":"Spinner creation block.","type":"text"}],"url":"\/documentation\/supportsdk\/zduispinner","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ZDUISpinner","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZDUISpinner","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"value":"ZDUISpinner","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZDUISpinner","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDUISpinner"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id<ZDKSpinnerDelegate> (^)(struct CGRect)","kind":"typeIdentifier","preciseIdentifier":"c:BF*Qoobjc(pl)ZDKSpinnerDelegate(#$@S@CGRect)"},{"text":" ","kind":"text"},{"text":"ZDUISpinner","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/title","value":"ZDKSpinnerDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDUISpinner\/title","op":"replace","value":"ZDUISpinner"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDUISpinner\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDUISpinner"}]}]}]}