{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CustomField","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"4.0.0"}]}],"type":"aside","name":"Version"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/customfields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/customfields"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/customFields","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Custom Fields set in any created tickets"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CustomField","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField"},{"kind":"text","text":"]"}],"title":"customFields","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUiConfiguration(py)customFields","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"customFields"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration":{"role":"symbol","title":"RequestUiConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestUiConfiguration"}],"abstract":[{"type":"text","text":"Data class used to configure Ticketing"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestUiConfiguration"}],"url":"\/documentation\/supportsdk\/requestuiconfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration/customFields":{"role":"symbol","title":"customFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CustomField","preciseIdentifier":"c:@M@SupportProvidersSDK@objc(cs)ZDKCustomField"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Custom Fields set in any created tickets"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/customFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customFields"}],"url":"\/documentation\/supportsdk\/requestuiconfiguration\/customfields"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"customFields"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"customFields"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<ZDKCustomField *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"customFields"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/title","value":"ZDKRequestUiConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKRequestUiConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1customFields\/title","value":"customFields"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1customFields\/fragments","value":[{"kind":"identifier","text":"customFields"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}