{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimating"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/zdkspinnerdelegate\/startanimating()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkspinnerdelegate\/startanimating()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/startAnimating()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Start the spinner animating."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"startAnimating"}],"role":"symbol","title":"startAnimating()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimating"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)ZDKSpinnerDelegate(im)startAnimating","required":true,"modules":[{"name":"SupportSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate/startAnimating()":{"navigatorTitle":[{"kind":"identifier","text":"startAnimating"}],"role":"symbol","title":"startAnimating()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimating"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Start the spinner animating."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/startAnimating()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/supportsdk\/zdkspinnerdelegate\/startanimating()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate":{"role":"symbol","title":"ZDKSpinnerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"abstract":[{"type":"text","text":"Spinner control delegate."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"url":"\/documentation\/supportsdk\/zdkspinnerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startAnimating"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAnimating"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startAnimating"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1startAnimating()\/title","value":"startAnimating"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1startAnimating()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAnimating"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/title","value":"ZDKSpinnerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}