{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol\/updatebuttonstatesforbutton(atindexselected:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol\/updatebuttonstatesforbutton(atindexselected:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateButtonStatesForButton","kind":"identifier"},{"text":"(","kind":"text"},{"text":"atIndexSelected","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol\/updateButtonStatesForButton(atIndexSelected:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol"]]},"metadata":{"modules":[{"name":"SupportSDK"}],"title":"updateButtonStatesForButton(atIndexSelected:)","externalID":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol(im)updateButtonStatesForButtonAtIndexSelected:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateButtonStatesForButton","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atIndexSelected"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"updateButtonStatesForButtonAtIndexSelected:","kind":"identifier"}],"required":true,"symbolKind":"method","roleHeading":"Instance Method"},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingStateProtocol/updateButtonStatesForButton(atIndexSelected:)":{"abstract":[],"title":"updateButtonStatesForButton(atIndexSelected:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateButtonStatesForButton","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atIndexSelected"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol\/updatebuttonstatesforbutton(atindexselected:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateButtonStatesForButtonAtIndexSelected:"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol\/updateButtonStatesForButton(atIndexSelected:)","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingStateProtocol":{"abstract":[],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ZDKHelpCenterArticleRatingStateProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"updateButtonStatesForButtonAtIndexSelected:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateButtonStatesForButtonAtIndexSelected:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateButtonStatesForButtonAtIndexSelected:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol~1updateButtonStatesForButton(atIndexSelected:)\/title","value":"updateButtonStatesForButtonAtIndexSelected:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol~1updateButtonStatesForButton(atIndexSelected:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateButtonStatesForButtonAtIndexSelected:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/title","op":"replace","value":"ZDKHelpCenterArticleRatingStateProtocol"},{"value":[{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/fragments"}]}]}