{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"off","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/off"},"sections":[],"metadata":{"title":"ZDKContactUsVisibility.off","roleHeading":"Case","externalID":"c:@E@ZDKContactUsVisibility@ZDKContactUsVisibilityOff","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"off"}],"navigatorTitle":[{"text":"ZDKContactUsVisibilityOff","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"role":"symbol","platforms":[]},"schemaVersion":{"patch":0,"major":0,"minor":3},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}]}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility\/off"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility\/off"]}],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKContactUsVisibility"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKContactUsVisibility"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/supportsdk\/zdkcontactusvisibility","title":"ZDKContactUsVisibility","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","role":"symbol","abstract":[{"text":"Used to select where conversations nav bar button will be active.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/off":{"title":"ZDKContactUsVisibility.off","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"off","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKContactUsVisibilityOff"}],"abstract":[],"kind":"symbol","deprecated":true,"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/off"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKContactUsVisibilityOff"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKContactUsVisibilityOff","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKContactUsVisibilityOff","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ZDKContactUsVisibility","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/title"},{"value":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1off\/title","op":"replace","value":"ZDKContactUsVisibilityOff"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1off\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContactUsVisibilityOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}