{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/supportengine\/engine()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/supportengine\/engine()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/engine()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"engine"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"SupportEngine","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportEngine","kind":"typeIdentifier"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","title":"engine()","externalID":"c:@M@SupportSDK@objc(cs)ZDKSupportEngine(cm)engineAndReturnError:","navigatorTitle":[{"text":"engineAndReturnError:","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"engine"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","kind":"typeIdentifier","text":"SupportEngine","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportEngine"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SupportEngine","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SupportEngine"}],"abstract":[],"url":"\/documentation\/supportsdk\/supportengine","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","title":"SupportEngine"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/engine()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/engine()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"engine","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"SupportEngine","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportEngine","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"engine()","url":"\/documentation\/supportsdk\/supportengine\/engine()","navigatorTitle":[{"text":"engineAndReturnError:","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"engineAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"engineAndReturnError:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"ZDKSupportEngine","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportEngine","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine"},{"text":" *) ","kind":"text"},{"text":"engineAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"ZDKSupportEngine","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/fragments","value":[{"kind":"identifier","text":"ZDKSupportEngine"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine~1engine()\/title","op":"replace","value":"engineAndReturnError:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine~1engine()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"engineAndReturnError:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}