{"variants":[{"paths":["\/documentation\/supportsdk\/theme\/currenttheme"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/theme\/currenttheme"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/currentTheme","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","role":"symbol","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"currentTheme","kind":"identifier"}],"title":"currentTheme","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"currentTheme","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKTheme","text":"Theme"}],"symbolKind":"property","platforms":[],"externalID":"c:@M@SupportSDK@objc(cs)ZDKTheme(cpy)currentTheme"},"abstract":[{"type":"text","text":"The theme currently applied to the SDK."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentTheme","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKTheme","text":"Theme","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"2.0.0","type":"text"}]}],"name":"Version","type":"aside","style":"note"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Theme":{"url":"\/documentation\/supportsdk\/theme","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme","abstract":[{"type":"text","text":"Used to style the SDK."}],"type":"topic","navigatorTitle":[{"text":"Theme","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Theme"}],"title":"Theme"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Theme/currentTheme":{"abstract":[{"type":"text","text":"The theme currently applied to the SDK."}],"role":"symbol","navigatorTitle":[{"text":"currentTheme","kind":"identifier"}],"title":"currentTheme","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentTheme","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Theme","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKTheme"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/currentTheme","kind":"symbol","deprecated":true,"url":"\/documentation\/supportsdk\/theme\/currenttheme"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"currentTheme","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"currentTheme","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"ZDKTheme","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKTheme","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"currentTheme"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme\/title","value":"ZDKTheme"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme~1currentTheme\/title","value":"currentTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme~1currentTheme\/fragments","value":[{"kind":"identifier","text":"currentTheme"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}