{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptionsOnEmptySearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.4.0"}]}],"type":"aside","name":"Version"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptionsonemptysearch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptionsonemptysearch"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptionsOnEmptySearch","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Show the "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button in the Help Center empty search result screen"},{"type":"text","text":" "},{"type":"text","text":"true by default"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptionsOnEmptySearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"showContactOptionsOnEmptySearch","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterUiConfiguration(py)showContactOptionsOnEmptySearch","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"showContactOptionsOnEmptySearch"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration":{"role":"symbol","title":"HelpCenterUiConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterUiConfiguration"}],"abstract":[{"type":"text","text":"Data class used to configure Help Center"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HelpCenterUiConfiguration"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/showContactOptionsOnEmptySearch":{"role":"symbol","title":"showContactOptionsOnEmptySearch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptionsOnEmptySearch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Show the "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button in the Help Center empty search result screen"},{"type":"text","text":" "},{"type":"text","text":"true by default"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptionsOnEmptySearch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showContactOptionsOnEmptySearch"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptionsonemptysearch"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"showContactOptionsOnEmptySearch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"showContactOptionsOnEmptySearch"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptionsOnEmptySearch"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/title","value":"ZDKHelpCenterUiConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUiConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptionsOnEmptySearch\/title","value":"showContactOptionsOnEmptySearch"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptionsOnEmptySearch\/fragments","value":[{"kind":"identifier","text":"showContactOptionsOnEmptySearch"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}