{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowRequestCreation"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"name":"Version","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"5.1.0"}]}],"type":"aside"}]}],"abstract":[{"text":"Show a ","type":"text"},{"code":"Contact Support","type":"codeVoice"},{"text":" button in the request list view, and in the empty state for the list.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","title":"allowRequestCreation","role":"symbol","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestListUiConfiguration(py)allowRequestCreation","navigatorTitle":[{"text":"allowRequestCreation","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"SupportSDK"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowRequestCreation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/allowRequestCreation","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestlistuiconfiguration\/allowrequestcreation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/requestlistuiconfiguration\/allowrequestcreation"]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestListUIConfiguration/allowRequestCreation":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/allowRequestCreation","url":"\/documentation\/supportsdk\/requestlistuiconfiguration\/allowrequestcreation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowRequestCreation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"allowRequestCreation","navigatorTitle":[{"text":"allowRequestCreation","kind":"identifier"}],"abstract":[{"type":"text","text":"Show a "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button in the request list view, and in the empty state for the list."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestListUIConfiguration":{"url":"\/documentation\/supportsdk\/requestlistuiconfiguration","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestListUIConfiguration"}],"type":"topic","kind":"symbol","role":"symbol","title":"RequestListUIConfiguration","navigatorTitle":[{"text":"RequestListUIConfiguration","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"allowRequestCreation","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"allowRequestCreation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"allowRequestCreation","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"allowRequestCreation","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1allowRequestCreation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1allowRequestCreation\/fragments","value":[{"text":"allowRequestCreation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKRequestListUiConfiguration","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration\/title"},{"op":"replace","value":[{"text":"ZDKRequestListUiConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}