{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKTheme) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set the currentTheme.primaryColor to style the UI."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"type":"aside","name":"Version"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/theme"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/theme"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used to style the SDK."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"Theme"}],"role":"symbol","title":"Theme","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"symbolKind":"class","externalID":"c:@M@SupportSDK@objc(cs)ZDKTheme","modules":[{"name":"SupportSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/primaryColor"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/currentTheme"]}],"references":{"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Theme/primaryColor":{"deprecated":true,"role":"symbol","title":"primaryColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The primary color of the SDK."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/primaryColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryColor"}],"url":"\/documentation\/supportsdk\/theme\/primarycolor"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Theme":{"deprecated":true,"role":"symbol","title":"Theme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"abstract":[{"type":"text","text":"Used to style the SDK."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Theme"}],"url":"\/documentation\/supportsdk\/theme"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Theme/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/supportsdk\/theme\/init"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Theme/currentTheme":{"deprecated":true,"role":"symbol","title":"currentTheme","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Theme","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKTheme"}],"abstract":[{"type":"text","text":"The theme currently applied to the SDK."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/currentTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentTheme"}],"url":"\/documentation\/supportsdk\/theme\/currenttheme"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKTheme"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKTheme"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKTheme"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/primaryColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme\/currentTheme"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKTheme"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme~1primaryColor\/title","value":"primaryColor"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme~1primaryColor\/fragments","value":[{"kind":"identifier","text":"primaryColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme\/title","value":"ZDKTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme\/fragments","value":[{"kind":"identifier","text":"ZDKTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme~1currentTheme\/title","value":"currentTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme~1currentTheme\/fragments","value":[{"kind":"identifier","text":"currentTheme"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}