{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITableViewDataSource"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Data source for Help Center attachments."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"title":"ZDKHelpCenterAttachmentsDataSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ZDKHelpCenterAttachmentsDataSource","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource\/init(articleId:)"]}],"references":{"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITableViewDataSource"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource":{"role":"symbol","title":"ZDKHelpCenterDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"abstract":[{"type":"text","text":"The support view that displays help center content."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterAttachmentsDataSource":{"role":"symbol","title":"ZDKHelpCenterAttachmentsDataSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"abstract":[{"type":"text","text":"Data source for Help Center attachments."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterAttachmentsDataSource/init(articleId:)":{"role":"symbol","title":"init(articleId:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"articleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Initializes a data source with a cell identifier, configuration block and a provider."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource\/init(articleId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithArticleId:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource\/init(articleid:)"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterAttachmentsDataSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource\/init(articleId:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","preciseIdentifier":"c:objc(cs)ZDKHelpCenterDataSource","text":"ZDKHelpCenterDataSource"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/title","value":"ZDKHelpCenterDataSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/title","value":"ZDKHelpCenterAttachmentsDataSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource~1init(articleId:)\/title","value":"initWithArticleId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource~1init(articleId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithArticleId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}