{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate"]]},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","title":"stopAnimating()","symbolKind":"method","required":true,"externalID":"c:objc(pl)ZDKSpinnerDelegate(im)stopAnimating","navigatorTitle":[{"text":"stopAnimating","kind":"identifier"}],"modules":[{"name":"SupportSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Stop the spinner animating.","type":"text"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/stopAnimating()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportsdk\/zdkspinnerdelegate\/stopanimating()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkspinnerdelegate\/stopanimating()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate":{"kind":"symbol","title":"ZDKSpinnerDelegate","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate","url":"\/documentation\/supportsdk\/zdkspinnerdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"abstract":[{"text":"Spinner control delegate.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate/stopAnimating()":{"navigatorTitle":[{"text":"stopAnimating","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/stopAnimating()","type":"topic","kind":"symbol","title":"stopAnimating()","url":"\/documentation\/supportsdk\/zdkspinnerdelegate\/stopanimating()","abstract":[{"text":"Stop the spinner animating.","type":"text"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"stopAnimating","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopAnimating","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stopAnimating","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKSpinnerDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/fragments"},{"op":"replace","value":[{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/navigatorTitle"},{"op":"replace","value":"stopAnimating","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1stopAnimating()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAnimating"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1stopAnimating()\/fragments"}]}]}