{"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator\/init(viewController:topLevel:layoutPosition:)","interfaceLanguage":"swift"},"abstract":[{"text":"Creates an instance","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicator\/init(viewcontroller:toplevel:layoutposition:)"]},{"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicator\/init(viewcontroller:toplevel:layoutposition:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topLevel"},{"kind":"text","text":" "},{"text":"topLevelView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"layoutPosition","kind":"externalParam"},{"kind":"text","text":" "},{"text":"position","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition","text":"ZDKLayoutGuideApplicatorPosition","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"the viewcontroller containing the view to fix the layout for","type":"text"}]}]},{"name":"topLevelView","content":[{"inlineContent":[{"type":"text","text":"the view that is closest to the parent y origin."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"positions to fix","type":"text"}],"type":"paragraph"}],"name":"position"}]}],"metadata":{"modules":[{"name":"SupportSDK"}],"role":"symbol","title":"init(viewController:topLevel:layoutPosition:)","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithViewController:topLevelView:layoutPosition:"}],"roleHeading":"Initializer","externalID":"c:objc(cs)ZDKLayoutGuideApplicator(im)initWithViewController:topLevelView:layoutPosition:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topLevel"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layoutPosition"},{"kind":"text","text":": "},{"text":"ZDKLayoutGuideApplicatorPosition","preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicator/init(viewController:topLevel:layoutPosition:)":{"url":"\/documentation\/supportsdk\/zdklayoutguideapplicator\/init(viewcontroller:toplevel:layoutposition:)","abstract":[{"type":"text","text":"Creates an instance"}],"role":"symbol","kind":"symbol","title":"init(viewController:topLevel:layoutPosition:)","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator\/init(viewController:topLevel:layoutPosition:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"topLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"text":"layoutPosition","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition","text":"ZDKLayoutGuideApplicatorPosition","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithViewController:topLevelView:layoutPosition:","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"abstract":[{"text":"Layout guides positions to fix","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"title":"ZDKLayoutGuideApplicatorPosition","kind":"symbol","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicator":{"url":"\/documentation\/supportsdk\/zdklayoutguideapplicator","abstract":[{"text":"This class tries to fix the layout spacing when using XIB instead of storyboard.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Since we cannot reference the top\/bottom layout guids. This class fixes the top\/bottom layout to be relative to the guides."}],"role":"symbol","kind":"symbol","title":"ZDKLayoutGuideApplicator","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"navigatorTitle":[{"text":"ZDKLayoutGuideApplicator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithViewController:topLevelView:layoutPosition:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithViewController:topLevelView:layoutPosition:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithViewController:"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"text":"topLevelView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"topLevelView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"layoutPosition:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","text":"ZDKLayoutGuideApplicatorPosition","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"position"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"initWithViewController:topLevelView:layoutPosition:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator~1init(viewController:topLevel:layoutPosition:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithViewController:topLevelView:layoutPosition:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator~1init(viewController:topLevel:layoutPosition:)\/fragments"},{"op":"replace","value":"ZDKLayoutGuideApplicatorPosition","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/fragments","value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/title","value":"ZDKLayoutGuideApplicator"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/fragments"}]}]}