{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKRequestUi) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestUi"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"type":"aside","name":"Version"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/requestui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/requestui"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used to build view controller for ticketing. The returned objects must be presented inside a UINavigationController."},{"type":"text","text":" "},{"type":"text","text":"The containing navigation controller can be presented any way you see fit."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestUi"}],"title":"RequestUi","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUi","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RequestUi"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList(with:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:configurations:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(with:)"]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/supportsdk\/requestui\/init"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestList(with:)":{"role":"symbol","title":"buildRequestList(with:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Request List with a list of Configurations."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildRequestListWith:"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestlist(with:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestUi(requestId:)":{"role":"symbol","title":"buildRequestUi(requestId:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Request Ui. This allows users to create and respond to individual tickets."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildRequestUiWithRequestId:"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestUi(requestId:configurations:)":{"role":"symbol","title":"buildRequestUi(requestId:configurations:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configurations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Request Ui with a list of Configurations."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:configurations:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildRequestUiWithRequestId:configurations:"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:configurations:)"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestList()":{"role":"symbol","title":"buildRequestList()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestList"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Request List. This is a list of a users tickets."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildRequestList"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestlist()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestUi()":{"role":"symbol","title":"buildRequestUi()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Request Ui. This allows users to create and respond to individual tickets."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildRequestUi"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestui()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi":{"role":"symbol","title":"RequestUi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestUi"}],"abstract":[{"type":"text","text":"Used to build view controller for ticketing. The returned objects must be presented inside a UINavigationController."},{"type":"text","text":" "},{"type":"text","text":"The containing navigation controller can be presented any way you see fit."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestUi"}],"url":"\/documentation\/supportsdk\/requestui"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestUi(with:)":{"role":"symbol","title":"buildRequestUi(with:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Request Ui with a list of Configurations."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildRequestUiWith:"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestui(with:)"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKRequestUi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKRequestUi"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKRequestUi"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList(with:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:configurations:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRequestUi"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestList(with:)\/title","value":"buildRequestListWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestList(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestListWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:)\/title","value":"buildRequestUiWithRequestId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestUiWithRequestId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:configurations:)\/title","value":"buildRequestUiWithRequestId:configurations:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:configurations:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestUiWithRequestId:configurations:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestList()\/title","value":"buildRequestList"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestList()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi()\/title","value":"buildRequestUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestUi"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/title","value":"ZDKRequestUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/fragments","value":[{"kind":"identifier","text":"ZDKRequestUi"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(with:)\/title","value":"buildRequestUiWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestUiWith:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}