{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKSupportUI) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportUI"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/supportui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/supportui"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/helpCenterLocaleOverride"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/refreshRequest(requestId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/instance"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/initialize(withZendesk:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SupportUI"}],"role":"symbol","title":"SupportUI","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportUI"}],"symbolKind":"class","externalID":"c:@M@SupportSDK@objc(cs)ZDKSupportUI","modules":[{"name":"SupportSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI":{"deprecated":true,"role":"symbol","title":"SupportUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportUI"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SupportUI"}],"url":"\/documentation\/supportsdk\/supportui"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/initialize(withZendesk:)":{"deprecated":true,"role":"symbol","title":"initialize(withZendesk:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withZendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initialize the SupportUI singleton with the Zendesk singleton"},{"type":"text","text":" "},{"type":"text","text":"from ZendeskCoreSDK"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/initialize(withZendesk:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithZendesk:"}],"url":"\/documentation\/supportsdk\/supportui\/initialize(withzendesk:)"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/refreshRequest(requestId:)":{"deprecated":true,"role":"symbol","title":"refreshRequest(requestId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"This method can be used to aid in handling push notifications relating to requests."},{"type":"text","text":" "},{"type":"text","text":"This method can result in a dynamic update in the request UI. For this occur,"},{"type":"text","text":" "},{"type":"text","text":"the push notification and the on screen request must contain matching request ids."},{"type":"text","text":" "},{"type":"text","text":"This method will return true only in the case of a successful UI update."},{"type":"text","text":" "},{"type":"text","text":"A return value of false means that the push notification was unhandled."},{"type":"text","text":" "},{"type":"text","text":"At this point you can decided how best to update the user based on the contents of the notification."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/refreshRequest(requestId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshRequestWithRequestId:"}],"url":"\/documentation\/supportsdk\/supportui\/refreshrequest(requestid:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/helpCenterLocaleOverride":{"deprecated":true,"role":"symbol","title":"helpCenterLocaleOverride","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpCenterLocaleOverride"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Locale override for help center"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/helpCenterLocaleOverride","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"helpCenterLocaleOverride"}],"url":"\/documentation\/supportsdk\/supportui\/helpcenterlocaleoverride"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/instance":{"deprecated":true,"role":"symbol","title":"instance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SupportUI","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportUI"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Get the API instance (singleton)."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/instance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instance"}],"url":"\/documentation\/supportsdk\/supportui\/instance"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKSupportUI"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKSupportUI"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKSupportUI"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/helpCenterLocaleOverride"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/refreshRequest(requestId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/instance"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/initialize(withZendesk:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSupportUI"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/title","value":"ZDKSupportUI"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/fragments","value":[{"kind":"identifier","text":"ZDKSupportUI"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1initialize(withZendesk:)\/title","value":"initializeWithZendesk:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1initialize(withZendesk:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithZendesk:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1refreshRequest(requestId:)\/title","value":"refreshRequestWithRequestId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1refreshRequest(requestId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshRequestWithRequestId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1helpCenterLocaleOverride\/title","value":"helpCenterLocaleOverride"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1helpCenterLocaleOverride\/fragments","value":[{"kind":"identifier","text":"helpCenterLocaleOverride"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1instance\/title","value":"instance"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1instance\/fragments","value":[{"kind":"identifier","text":"instance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}