{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview(withConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi(withConfigs:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"title":"ZDKHelpCenterUi","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ZDKHelpCenterUi","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/build(_:andConfigs:)":{"deprecated":true,"role":"symbol","title":"build(_:andConfigs:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:andConfigs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticle:andConfigs:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/build(_:andconfigs:)"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"role":"symbol","title":"ZDKHelpCenterUi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticle(withArticleId:)":{"deprecated":true,"role":"symbol","title":"buildHelpCenterArticle(withArticleId:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverviewUi()":{"role":"symbol","title":"buildHelpCenterOverviewUi()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverviewUi"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Help Center Overview view controller. Displays an overview of your HelpCenter"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverviewUi"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui()"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverview()":{"deprecated":true,"role":"symbol","title":"buildHelpCenterOverview()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverview"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview()"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(_:)":{"role":"symbol","title":"buildHelpCenterArticleUi(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUi:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverviewUi(withConfigs:)":{"role":"symbol","title":"buildHelpCenterOverviewUi(withConfigs:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverviewUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Help Center Overview view controller with a list of ZDKConfigurations."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi(withConfigs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverviewUiWithConfigs:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui(withconfigs:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/build(_:)":{"deprecated":true,"role":"symbol","title":"build(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticle:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/build(_:)"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(withArticleId:andConfigs:)":{"role":"symbol","title":"buildHelpCenterArticleUi(withArticleId:andConfigs:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:andConfigs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:andConfigs:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:andconfigs:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(withArticleId:)":{"role":"symbol","title":"buildHelpCenterArticleUi(withArticleId:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:)"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticle(withArticleId:andConfigs:)":{"deprecated":true,"role":"symbol","title":"buildHelpCenterArticle(withArticleId:andConfigs:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:andConfigs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:andConfigs:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:andconfigs:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(_:andConfigs:)":{"role":"symbol","title":"buildHelpCenterArticleUi(_:andConfigs:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:andConfigs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUi:andConfigs:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:andconfigs:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverview(withConfigs:)":{"deprecated":true,"role":"symbol","title":"buildHelpCenterOverview(withConfigs:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview(withConfigs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverviewWithConfigs:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview(withconfigs:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterUi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:andConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview(withConfigs:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi(withConfigs:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1build(_:andConfigs:)\/title","value":"buildHelpCenterArticle:andConfigs:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1build(_:andConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticle:andConfigs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title","value":"ZDKHelpCenterUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:)\/title","value":"buildHelpCenterArticleWithArticleId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi()\/title","value":"buildHelpCenterOverviewUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverviewUi"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview()\/title","value":"buildHelpCenterOverview"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverview"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:)\/title","value":"buildHelpCenterArticleUi:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleUi:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi(withConfigs:)\/title","value":"buildHelpCenterOverviewUiWithConfigs:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi(withConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverviewUiWithConfigs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1build(_:)\/title","value":"buildHelpCenterArticle:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1build(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticle:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:andConfigs:)\/title","value":"buildHelpCenterArticleUiWithArticleId:andConfigs:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:andConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:andConfigs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:)\/title","value":"buildHelpCenterArticleUiWithArticleId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:andConfigs:)\/title","value":"buildHelpCenterArticleWithArticleId:andConfigs:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:andConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:andConfigs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:andConfigs:)\/title","value":"buildHelpCenterArticleUi:andConfigs:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:andConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleUi:andConfigs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview(withConfigs:)\/title","value":"buildHelpCenterOverviewWithConfigs:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview(withConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverviewWithConfigs:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}