{"variants":[{"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter\/init(withpresentingviewcontroller:configurations:engines:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter\/init(withpresentingviewcontroller:configurations:engines:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPresentingViewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configurations"},{"kind":"text","text":": ["},{"text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"engines","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","text":"ZDKEngine","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"init(withPresentingViewController:configurations:engines:)","externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterContactUsRouter(im)initWithPresentingViewController:configurations:engines:","roleHeading":"Initializer","modules":[{"name":"SupportSDK"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPresentingViewController:configurations:engines:"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPresentingViewController"},{"kind":"text","text":" "},{"text":"presentingViewController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configurations"},{"kind":"text","text":": ["},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"], "},{"text":"engines","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ZDKEngine","kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/init(withPresentingViewController:configurations:engines:)"},"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"kind":"symbol","title":"HelpCenterContactUsRouter","type":"topic","url":"\/documentation\/supportsdk\/helpcentercontactusrouter","navigatorTitle":[{"text":"HelpCenterContactUsRouter","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter/init(withPresentingViewController:configurations:engines:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/init(withPresentingViewController:configurations:engines:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPresentingViewController","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configurations"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration"},{"kind":"text","text":"], "},{"text":"engines","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ZDKEngine","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine"},{"text":"])","kind":"text"}],"title":"init(withPresentingViewController:configurations:engines:)","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/helpcentercontactusrouter\/init(withpresentingviewcontroller:configurations:engines:)","navigatorTitle":[{"kind":"identifier","text":"initWithPresentingViewController:configurations:engines:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithPresentingViewController:configurations:engines:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPresentingViewController:configurations:engines:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPresentingViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"presentingViewController"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configurations:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<ZDKConfiguration>>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configurations"},{"text":" ","kind":"text"},{"text":"engines:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<ZDKEngine>>"},{"kind":"text","text":" *) "},{"text":"engines","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKHelpCenterContactUsRouter","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterContactUsRouter"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/fragments"},{"value":"initWithPresentingViewController:configurations:engines:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1init(withPresentingViewController:configurations:engines:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1init(withPresentingViewController:configurations:engines:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPresentingViewController:configurations:engines:"}]}]}]}