{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/engines"},"abstract":[{"text":"The ","type":"text"},{"code":"Contact Support","type":"codeVoice"},{"text":" button on the Help Center Article screen will route to the “UMI” screen,","type":"text"},{"text":" ","type":"text"},{"text":"if an engine is added to this array. If the array is empty, we route to the ","type":"text"},{"code":"Request List","type":"codeVoice"},{"text":" screen if","type":"text"},{"text":" ","type":"text"},{"code":"Conversations","type":"codeVoice"},{"text":" are turned on, otherwise we will route to the ","type":"text"},{"code":"Request Screen","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engines","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Engine","preciseIdentifier":"s:12MessagingAPI6EngineP","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"name":"Version","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"5.0.0"}]}],"style":"note","type":"aside"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/supportsdk\/articleuiconfiguration\/engines"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"engines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6EngineP","text":"Engine"},{"kind":"text","text":"]"}],"symbolKind":"property","modules":[{"name":"SupportSDK"}],"roleHeading":"Instance Property","externalID":"s:10SupportSDK22ArticleUiConfigurationC7enginesSay12MessagingAPI6Engine_pGvp","title":"engines"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration":{"url":"\/documentation\/supportsdk\/articleuiconfiguration","title":"ArticleUiConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ArticleUiConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ArticleUiConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration","type":"topic","abstract":[{"text":"Data class used to configure Article Screen","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/engines":{"title":"engines","kind":"symbol","url":"\/documentation\/supportsdk\/articleuiconfiguration\/engines","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/engines","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"Contact Support","type":"codeVoice"},{"type":"text","text":" button on the Help Center Article screen will route to the “UMI” screen,"},{"type":"text","text":" "},{"type":"text","text":"if an engine is added to this array. If the array is empty, we route to the "},{"code":"Request List","type":"codeVoice"},{"type":"text","text":" screen if"},{"type":"text","text":" "},{"code":"Conversations","type":"codeVoice"},{"type":"text","text":" are turned on, otherwise we will route to the "},{"code":"Request Screen","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engines","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Engine","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6EngineP"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ZDKArticleUiConfiguration","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/title"},{"op":"replace","value":[{"text":"ZDKArticleUiConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/fragments"},{"op":"replace","value":[{"text":"ZDKArticleUiConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/navigatorTitle"}]}]}