{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonimage()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonimage()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"To conform implementations should return an image for the right nav bar button."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate"]]},"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(pl)ZDKCreateRequestUIDelegate(im)createRequestBarButtonImage","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createRequestBarButtonImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"!","kind":"text"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false,"name":"iOS"}],"required":true,"navigatorTitle":[{"text":"createRequestBarButtonImage","kind":"identifier"}],"title":"createRequestBarButtonImage()","modules":[{"name":"SupportSDK"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createRequestBarButtonImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"!","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"An image for the right nav bar button.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonImage()","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate":{"navigatorTitle":[{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}],"type":"topic","title":"ZDKCreateRequestUIDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate","kind":"symbol","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate","abstract":[{"type":"text","text":"Delegate for the create request view."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate/createRequestBarButtonImage()":{"type":"topic","abstract":[{"text":"To conform implementations should return an image for the right nav bar button.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonImage()","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createRequestBarButtonImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"!","kind":"text"}],"url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonimage()","navigatorTitle":[{"kind":"identifier","text":"createRequestBarButtonImage"}],"kind":"symbol","title":"createRequestBarButtonImage()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"createRequestBarButtonImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createRequestBarButtonImage"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createRequestBarButtonImage"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKCreateRequestUIDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonImage()\/title","value":"createRequestBarButtonImage","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"createRequestBarButtonImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonImage()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}