{"abstract":[{"type":"text","text":"Returns cell identifier for the data source. Default ZDKHelpCenterTableViewCell. Override if using a different cell type."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterdatasource\/cellidentifierfordatasource()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterdatasource\/cellidentifierfordatasource()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/cellIdentifierForDataSource()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource"]]},"metadata":{"modules":[{"name":"SupportSDK"}],"title":"cellIdentifierForDataSource()","symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterDataSource(cm)cellIdentifierForDataSource","role":"symbol","navigatorTitle":[{"text":"cellIdentifierForDataSource","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellIdentifierForDataSource","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellIdentifierForDataSource"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource/cellIdentifierForDataSource()":{"navigatorTitle":[{"text":"cellIdentifierForDataSource","kind":"identifier"}],"kind":"symbol","title":"cellIdentifierForDataSource()","url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource\/cellidentifierfordatasource()","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/cellIdentifierForDataSource()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellIdentifierForDataSource","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"abstract":[{"type":"text","text":"Returns cell identifier for the data source. Default ZDKHelpCenterTableViewCell. Override if using a different cell type."}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource":{"role":"symbol","title":"ZDKHelpCenterDataSource","url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource","abstract":[{"type":"text","text":"The support view that displays help center content."}],"navigatorTitle":[{"text":"ZDKHelpCenterDataSource","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDataSource","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"cellIdentifierForDataSource","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"cellIdentifierForDataSource","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cellIdentifierForDataSource","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1cellIdentifierForDataSource()\/title","value":"cellIdentifierForDataSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1cellIdentifierForDataSource()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cellIdentifierForDataSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/title","value":"ZDKHelpCenterDataSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"op":"replace"}]}]}