{"metadata":{"roleHeading":"Framework","title":"SupportSDK","externalID":"SupportSDK","symbolKind":"module","role":"collection","modules":[{"name":"SupportSDK"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[[]]},"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/BlockMiddleware","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/BlockReducer","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CombinedReducer","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Store","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKConstants","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]},{"title":"Protocols","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Action","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ApplicationType","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/AsyncAction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Middleware","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Reducer","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDynamicEquatable","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Window","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ActionSubscription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/AsyncMiddleware","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/BlockAsyncAction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/LoggerMiddleware","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/State","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Subscription"],"title":"Structures"},{"title":"Variables","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/EqualsFilter","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterEmptyHelpCenterDescription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterErrorDomain","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoArticlesForLabelsDescription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoCategoriesLocalisedDescription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoSectionsLocalisedDescription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/alwaysFilter","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/defaultLogger"]},{"title":"Functions","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGCenterRectInRect(_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGMakeCenteredRectInRect(_:_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGMakeCenteredRectOnXInRect(_:_:_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGRectMakeCenteredInScreen(_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIIsLandscape()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIOriginInWindow(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIScreenFrame()"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/+(_:_:)-2o1ks","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/+(_:_:)-8bv54"],"title":"Operators"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ActionListenerFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DispatchFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FilterFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/GetStateFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUi","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/KeyedState","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ListenerFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/MiddlewareFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/NextFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ReducerFunction","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/StateKey","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/StateSelector","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterCellConfigureBlock","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDUISpinner"],"title":"Type Aliases"},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Suas","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Swift","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/UIKit"],"title":"Extended Modules"}],"variants":[{"paths":["\/documentation\/supportsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Reducer":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Reducer","kind":"identifier"}],"title":"Reducer","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Reducer","navigatorTitle":[{"kind":"identifier","text":"Reducer"}],"role":"symbol","abstract":[{"text":"Protocol that represents a reducer","type":"text"}],"url":"\/documentation\/supportsdk\/reducer","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ApplicationType":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplicationType"}],"title":"ApplicationType","url":"\/documentation\/supportsdk\/applicationtype","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ApplicationType","abstract":[],"navigatorTitle":[{"text":"ApplicationType","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"role":"symbol","abstract":[],"title":"ZDKUIUtil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIUtil","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkuiutil","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKUIUtil"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Action":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"Action","kind":"identifier"}],"url":"\/documentation\/supportsdk\/action","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Action","title":"Action","abstract":[{"text":"Action to dispatch to the store","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Action"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/BlockAsyncAction":{"url":"\/documentation\/supportsdk\/blockasyncaction","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockAsyncAction"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/BlockAsyncAction","abstract":[{"text":"Create an ","type":"text"},{"type":"codeVoice","code":"AsyncAction"},{"type":"text","text":" inline by passing a block to the init"},{"text":" ","type":"text"},{"type":"text","text":"Check "},{"code":"AsyncAction","type":"codeVoice"},{"text":" for more info","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BlockAsyncAction"}],"kind":"symbol","title":"BlockAsyncAction","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler","title":"HelpCenterArticleVotingHandler","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/BlockMiddleware":{"kind":"symbol","url":"\/documentation\/supportsdk\/blockmiddleware","navigatorTitle":[{"kind":"identifier","text":"BlockMiddleware"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/BlockMiddleware","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BlockMiddleware","kind":"identifier"}],"role":"symbol","title":"BlockMiddleware","type":"topic","abstract":[{"text":"Create a middleware inline with a block.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/EqualsFilter":{"kind":"symbol","abstract":[{"text":"Listener filter callback that returns true if the old state and the new state are not equal.","type":"text"},{"type":"text","text":" "},{"text":"You can use this filter function when adding a listener if you want your notification function to be called when the state changes.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"EqualsFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK14FilterFunctiona","text":"FilterFunction"},{"text":"<","kind":"text"},{"text":"Any","kind":"keyword"},{"text":">","kind":"text"}],"title":"EqualsFilter","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/EqualsFilter","url":"\/documentation\/supportsdk\/equalsfilter","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"title":"ZDKHelpCenterDelegate","url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","deprecated":true},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/State":{"type":"topic","role":"symbol","url":"\/documentation\/supportsdk\/state","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/State","abstract":[{"type":"text","text":"Structure that represents the store state. The store state is kept as a "},{"type":"codeVoice","code":"Dictionary"},{"type":"text","text":" with "},{"code":"String","type":"codeVoice"},{"type":"text","text":" Keys and "},{"code":"Any","type":"codeVoice"},{"text":" Values (","type":"text"},{"code":"[String: Any]","type":"codeVoice"},{"text":")","type":"text"}],"title":"State","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"State"}],"navigatorTitle":[{"text":"State","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CGCenterRectInRect(_:_:)":{"abstract":[],"url":"\/documentation\/supportsdk\/cgcenterrectinrect(_:_:)","role":"symbol","title":"CGCenterRectInRect(_:_:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CGCenterRectInRect"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGCenterRectInRect(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGCenterRectInRect"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration","navigatorTitle":[{"text":"RequestUiConfiguration","kind":"identifier"}],"url":"\/documentation\/supportsdk\/requestuiconfiguration","title":"RequestUiConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestUiConfiguration","kind":"identifier"}],"abstract":[{"text":"Data class used to configure Ticketing","type":"text"}],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/StateKey":{"kind":"symbol","url":"\/documentation\/supportsdk\/statekey","navigatorTitle":[{"text":"StateKey","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/StateKey","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StateKey","kind":"identifier"}],"role":"symbol","title":"StateKey","type":"topic","abstract":[{"type":"text","text":"Store state is stored as a Dictionary of [StateKey: Any]"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIIsLandscape()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKUIIsLandscape"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIIsLandscape()","abstract":[{"text":"Helper for device orientation.","type":"text"}],"url":"\/documentation\/supportsdk\/zdkuiislandscape()","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKUIIsLandscape","kind":"identifier"}],"title":"ZDKUIIsLandscape()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/DispatchFunction":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DispatchFunction"}],"url":"\/documentation\/supportsdk\/dispatchfunction","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DispatchFunction","title":"DispatchFunction","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"DispatchFunction","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDUISpinner":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/zduispinner","title":"ZDUISpinner","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDUISpinner"}],"abstract":[{"text":"Spinner creation block.","type":"text"}],"navigatorTitle":[{"text":"ZDUISpinner","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDUISpinner"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUi":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUi","navigatorTitle":[{"text":"HelpCenterUi","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterUi"}],"role":"symbol","kind":"symbol","abstract":[],"title":"HelpCenterUi","type":"topic","url":"\/documentation\/supportsdk\/helpcenterui"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper":{"url":"\/documentation\/supportsdk\/zdktoastviewwrapper","abstract":[],"title":"ZDKToastViewWrapper","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKToastViewWrapper","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKToastViewWrapper"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterErrorDomain":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"ZDKHelpCenterErrorDomain","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterErrorDomain"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterErrorDomain","abstract":[{"type":"text","text":"Help Center error domain."}],"url":"\/documentation\/supportsdk\/zdkhelpcentererrordomain","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ReducerFunction":{"url":"\/documentation\/supportsdk\/reducerfunction","navigatorTitle":[{"text":"ReducerFunction","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ReducerFunction","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ReducerFunction","kind":"identifier"}],"type":"topic","title":"ReducerFunction"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/alwaysFilter":{"url":"\/documentation\/supportsdk\/alwaysfilter","title":"alwaysFilter","kind":"symbol","abstract":[{"text":"Listener filter callback that always returns true.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When using this filter callback the Listener will always be notified."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/alwaysFilter","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"alwaysFilter","kind":"identifier"},{"kind":"text","text":": "},{"text":"FilterFunction","kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK14FilterFunctiona"},{"text":"<","kind":"text"},{"kind":"keyword","text":"Any"},{"text":">","kind":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Store":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Store","kind":"identifier"}],"url":"\/documentation\/supportsdk\/store","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Store","navigatorTitle":[{"text":"Store","kind":"identifier"}],"title":"Store","role":"symbol","abstract":[{"type":"text","text":"Store that contains the application state, the reducer logic, the middleware and the listeners"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinator"}],"url":"\/documentation\/supportsdk\/coordinator","abstract":[],"navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"title":"Coordinator","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Suas":{"url":"\/documentation\/supportsdk\/suas","title":"Suas","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Suas","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Suas"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Suas"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/defaultLogger":{"title":"defaultLogger","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultLogger","kind":"identifier"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> ()"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/supportsdk\/defaultlogger","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/defaultLogger","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKConstants":{"url":"\/documentation\/supportsdk\/zdkconstants","abstract":[],"title":"ZDKConstants","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConstants"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKConstants","navigatorTitle":[{"kind":"identifier","text":"ZDKConstants"}],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CGMakeCenteredRectInRect(_:_:_:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGMakeCenteredRectInRect(_:_:_:)","title":"CGMakeCenteredRectInRect(_:_:_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CGMakeCenteredRectInRect"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"CGMakeCenteredRectInRect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"url":"\/documentation\/supportsdk\/cgmakecenteredrectinrect(_:_:_:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SYSTEM_VERSION_GREATER_THAN_SEVEN":{"url":"\/documentation\/supportsdk\/system_version_greater_than_seven","abstract":[],"title":"SYSTEM_VERSION_GREATER_THAN_SEVEN","role":"symbol","fragments":[{"kind":"identifier","text":"SYSTEM_VERSION_GREATER_THAN_SEVEN"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SYSTEM_VERSION_GREATER_THAN_SEVEN","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate","kind":"symbol","navigatorTitle":[{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"title":"ZDKSpinnerDelegate","url":"\/documentation\/supportsdk\/zdkspinnerdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Spinner control delegate."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SupportEngine","kind":"identifier"}],"url":"\/documentation\/supportsdk\/supportengine","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","title":"SupportEngine","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportEngine"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration":{"navigatorTitle":[{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Data class used to configure Help Center"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","role":"symbol","title":"HelpCenterUiConfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestListUIConfiguration":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestListUIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration","abstract":[],"navigatorTitle":[{"text":"RequestListUIConfiguration","kind":"identifier"}],"kind":"symbol","title":"RequestListUIConfiguration","url":"\/documentation\/supportsdk\/requestlistuiconfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIOriginInWindow(_:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIOriginInWindow(_:)","navigatorTitle":[{"kind":"identifier","text":"ZDKUIOriginInWindow"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKUIOriginInWindow"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"type":"topic","title":"ZDKUIOriginInWindow(_:)","abstract":[{"text":"Get the origin of the supplied view in the window.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/zdkuiorigininwindow(_:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility":{"kind":"symbol","title":"ZDKContactUsVisibility","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","navigatorTitle":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKContactUsVisibility","kind":"identifier"}],"abstract":[{"text":"Used to select where conversations nav bar button will be active.","type":"text"}],"deprecated":true,"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDLog":{"kind":"symbol","title":"ZDLog","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDLog","url":"\/documentation\/supportsdk\/zdlog","fragments":[{"kind":"identifier","text":"ZDLog"}],"abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"RequestUi","kind":"identifier"}],"url":"\/documentation\/supportsdk\/requestui","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","title":"RequestUi","abstract":[{"text":"Used to build view controller for ticketing. The returned objects must be presented inside a UINavigationController.","type":"text"},{"text":" ","type":"text"},{"text":"The containing navigation controller can be presented any way you see fit.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RequestUi","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/NextFunction":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"NextFunction","kind":"identifier"}],"url":"\/documentation\/supportsdk\/nextfunction","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/NextFunction","title":"NextFunction","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NextFunction","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ActionListenerFunction":{"kind":"symbol","navigatorTitle":[{"text":"ActionListenerFunction","kind":"identifier"}],"url":"\/documentation\/supportsdk\/actionlistenerfunction","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ActionListenerFunction","type":"topic","abstract":[{"text":"Callback function called when the action listener state is changed","type":"text"}],"title":"ActionListenerFunction","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionListenerFunction"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ListenerFunction":{"url":"\/documentation\/supportsdk\/listenerfunction","navigatorTitle":[{"text":"ListenerFunction","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ListenerFunction"}],"abstract":[{"text":"Callback function called when the listener state is changed","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ListenerFunction","title":"ListenerFunction","role":"symbol","type":"topic","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterNoCategoriesLocalisedDescription":{"kind":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenternocategorieslocaliseddescription","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterNoCategoriesLocalisedDescription"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoCategoriesLocalisedDescription","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterNoCategoriesLocalisedDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","title":"ZDKHelpCenterNoCategoriesLocalisedDescription","type":"topic","abstract":[{"text":"Error description for category id error.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDynamicEquatable":{"kind":"symbol","title":"SuasDynamicEquatable","url":"\/documentation\/supportsdk\/suasdynamicequatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDynamicEquatable","abstract":[{"type":"text","text":"Protocol used by "},{"type":"codeVoice","code":"EqualsFilter"},{"text":" filter callback to compare two state values.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If your state implements the "},{"type":"codeVoice","code":"Equatable"},{"text":" protocol there is no code required to implement ","type":"text"},{"code":"SuasDynamicEquatable","type":"codeVoice"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SuasDynamicEquatable"}],"navigatorTitle":[{"text":"SuasDynamicEquatable","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FilterFunction":{"url":"\/documentation\/supportsdk\/filterfunction","title":"FilterFunction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FilterFunction"}],"abstract":[{"text":"Filter function that decides if the listener should be notified or not","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FilterFunction","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"FilterFunction","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/BlockReducer":{"title":"BlockReducer","navigatorTitle":[{"text":"BlockReducer","kind":"identifier"}],"abstract":[{"type":"text","text":"Create a reducer inline with a block"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/BlockReducer","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BlockReducer","kind":"identifier"}],"url":"\/documentation\/supportsdk\/blockreducer","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterCoordinator"}],"url":"\/documentation\/supportsdk\/helpcentercoordinator","abstract":[],"navigatorTitle":[{"text":"HelpCenterCoordinator","kind":"identifier"}],"title":"HelpCenterCoordinator","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","kind":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/LoggerMiddleware":{"url":"\/documentation\/supportsdk\/loggermiddleware","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/LoggerMiddleware","abstract":[{"type":"text","text":"LoggerMiddleware that logs the action and state when each action is received"},{"type":"text","text":" "},{"text":"When an action is dispatched, the LoggerMiddleware will print information related to it in the console.","type":"text"}],"title":"LoggerMiddleware","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggerMiddleware"}],"navigatorTitle":[{"text":"LoggerMiddleware","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/DismissUtil":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DismissUtil","kind":"identifier"}],"navigatorTitle":[{"text":"DismissUtil","kind":"identifier"}],"type":"topic","url":"\/documentation\/supportsdk\/dismissutil","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil","title":"DismissUtil","kind":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingStateProtocol":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","type":"topic","title":"ZDKHelpCenterArticleRatingStateProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}],"abstract":[],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Subscription":{"url":"\/documentation\/supportsdk\/subscription","role":"symbol","abstract":[{"type":"text","text":"Subscription structure that represents a listener subscription."},{"text":" ","type":"text"},{"text":"When adding a listener you get a subscription back.","type":"text"},{"text":" ","type":"text"},{"text":"You can use this subscription to remove the listener, notify about the current state or link the listener lifecycle with an object.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Subscription"}],"navigatorTitle":[{"text":"Subscription","kind":"identifier"}],"kind":"symbol","type":"topic","title":"Subscription","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Subscription"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger":{"url":"\/documentation\/supportsdk\/suasdebuglogger","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SuasDebugLogger"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SuasDebugLogger"}],"role":"symbol","title":"SuasDebugLogger","type":"topic","abstract":[{"type":"text","text":"Used to enable "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/zendesk\/Suas-iOS"},{"type":"text","text":" logging."},{"type":"text","text":" "},{"type":"text","text":"Suas drives most of the Ticketing UI so the Suas logs can be useful for debugging it."},{"type":"text","text":" "},{"text":"Enabling the Suas logger produces a lot of information and will slow down the SDK.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CGMakeCenteredRectOnXInRect(_:_:_:_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGMakeCenteredRectOnXInRect"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"navigatorTitle":[{"kind":"identifier","text":"CGMakeCenteredRectOnXInRect"}],"title":"CGMakeCenteredRectOnXInRect(_:_:_:_:)","url":"\/documentation\/supportsdk\/cgmakecenteredrectonxinrect(_:_:_:_:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGMakeCenteredRectOnXInRect(_:_:_:_:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"role":"symbol","navigatorTitle":[{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerChildControllerDelegate"}],"abstract":[],"kind":"symbol","url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","title":"ContainerChildControllerDelegate","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterEmptyHelpCenterDescription":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterEmptyHelpCenterDescription","type":"topic","abstract":[{"text":"Error description for empty Help Center.","type":"text"}],"title":"ZDKHelpCenterEmptyHelpCenterDescription","url":"\/documentation\/supportsdk\/zdkhelpcenteremptyhelpcenterdescription","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterEmptyHelpCenterDescription"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZD_IS_IPHONE":{"abstract":[],"role":"symbol","url":"\/documentation\/supportsdk\/zd_is_iphone","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZD_IS_IPHONE","title":"ZD_IS_IPHONE","fragments":[{"text":"ZD_IS_IPHONE","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource":{"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource","abstract":[{"text":"The support view that displays help center content.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterDataSource","kind":"identifier"}],"title":"ZDKHelpCenterDataSource","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDataSource","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"abstract":[],"role":"symbol","deprecated":true,"title":"ZDKHelpCenterConversationsUIDelegate","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell","abstract":[],"role":"symbol","type":"topic","title":"ZDKSupportAttachmentCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSupportAttachmentCell"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKSupportAttachmentCell","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdksupportattachmentcell"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/StateSelector":{"url":"\/documentation\/supportsdk\/stateselector","role":"symbol","abstract":[{"text":"Function that selects part of the full state","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StateSelector","kind":"identifier"}],"navigatorTitle":[{"text":"StateSelector","kind":"identifier"}],"kind":"symbol","title":"StateSelector","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/StateSelector"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CombinedReducer":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CombinedReducer"}],"title":"CombinedReducer","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CombinedReducer","navigatorTitle":[{"text":"CombinedReducer","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Reducer that represents a combination of two reducers","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This reducers is not to be implemented by hand. You combine reducer by adding them with the "},{"type":"codeVoice","code":"+"},{"text":" operator.","type":"text"}],"type":"topic","url":"\/documentation\/supportsdk\/combinedreducer"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIScreenFrame()":{"navigatorTitle":[{"text":"ZDKUIScreenFrame","kind":"identifier"}],"title":"ZDKUIScreenFrame()","kind":"symbol","url":"\/documentation\/supportsdk\/zdkuiscreenframe()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKUIScreenFrame","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol","type":"topic","abstract":[{"text":"Returns the full screen frame with no attempt to account for the status bar.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIScreenFrame()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Theme":{"url":"\/documentation\/supportsdk\/theme","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme","abstract":[{"type":"text","text":"Used to style the SDK."}],"type":"topic","navigatorTitle":[{"text":"Theme","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Theme"}],"title":"Theme"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportSDK_h":{"title":"SupportSDK_h","fragments":[{"kind":"identifier","text":"SupportSDK_h"}],"kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/supportsdk_h","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportSDK_h","abstract":[],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CGRectMakeCenteredInScreen(_:_:)":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/cgrectmakecenteredinscreen(_:_:)","title":"CGRectMakeCenteredInScreen(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGRectMakeCenteredInScreen"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"navigatorTitle":[{"text":"CGRectMakeCenteredInScreen","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGRectMakeCenteredInScreen(_:_:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/requestattachment","title":"RequestAttachment","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestAttachment","kind":"identifier"}],"abstract":[{"text":"Creates an attachment to be uploaded when a request is created","type":"text"}],"navigatorTitle":[{"text":"RequestAttachment","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Middleware":{"url":"\/documentation\/supportsdk\/middleware","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Middleware protocol that represents a suas store middleware","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A middleware helps extending the dispatch logic of Suas."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Middleware","title":"Middleware","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Middleware"}],"navigatorTitle":[{"text":"Middleware","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChild":{"url":"\/documentation\/supportsdk\/containerchild","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ContainerChild","kind":"identifier"}],"title":"ContainerChild","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerChild"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType":{"title":"ZDKNavBarCreateRequestUIType","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype","abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display request creation."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition":{"abstract":[{"text":"Layout guides positions to fix","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"title":"ZDKLayoutGuideApplicatorPosition","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition","navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","role":"symbol"},"https://github.com/zendesk/Suas-iOS":{"type":"link","title":"Suas","url":"https:\/\/github.com\/zendesk\/Suas-iOS","identifier":"https:\/\/github.com\/zendesk\/Suas-iOS","titleInlineContent":[{"type":"text","text":"Suas"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Window":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Window","title":"Window","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Window"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Window"}],"url":"\/documentation\/supportsdk\/window","kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","url":"\/documentation\/supportsdk\/uikit","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/UIKit","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterContactUsRouter"}],"url":"\/documentation\/supportsdk\/helpcentercontactusrouter","title":"HelpCenterContactUsRouter","kind":"symbol","role":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterNoArticlesForLabelsDescription":{"title":"ZDKHelpCenterNoArticlesForLabelsDescription","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterNoArticlesForLabelsDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterNoArticlesForLabelsDescription","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenternoarticlesforlabelsdescription","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoArticlesForLabelsDescription","abstract":[{"type":"text","text":"Error description for label error."}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","type":"topic","url":"\/documentation\/supportsdk\/filetype","abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"navigatorTitle":[{"kind":"identifier","text":"FileType"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileType"}],"title":"FileType"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingHandlerProtocol":{"abstract":[],"title":"ZDKHelpCenterArticleRatingHandlerProtocol","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol","navigatorTitle":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterArticleRatingHandlerProtocol"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildController":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ContainerChildController","kind":"identifier"}],"url":"\/documentation\/supportsdk\/containerchildcontroller","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController","title":"ContainerChildController","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerChildController"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZD_IS_IPAD":{"abstract":[],"title":"ZD_IS_IPAD","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZD_IS_IPAD","type":"topic","url":"\/documentation\/supportsdk\/zd_is_ipad","fragments":[{"text":"ZD_IS_IPAD","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Swift":{"url":"\/documentation\/supportsdk\/swift","abstract":[],"type":"topic","kind":"symbol","role":"collection","title":"Swift","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Swift"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterAttachmentsDataSource":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource","role":"symbol","abstract":[{"text":"Data source for Help Center attachments.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"kind":"symbol","title":"ZDKHelpCenterAttachmentsDataSource","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/+(_:_:)-2o1ks":{"abstract":[{"text":"Combines two middlewares. The combined middleware creates a chain of middleware.","type":"text"},{"text":" ","type":"text"},{"text":"When calling next on the first middleware it progresses to the next one.","type":"text"},{"type":"text","text":" "},{"text":"The final middlwares next function calls the reducer dispatch will causes a state change.","type":"text"}],"title":"+(_:_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/+(_:_:)-2o1ks","type":"topic","url":"\/documentation\/supportsdk\/+(_:_:)-2o1ks","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"+","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Middleware","preciseIdentifier":"s:10SupportSDK10MiddlewareP"},{"kind":"text","text":", "},{"preciseIdentifier":"s:10SupportSDK10MiddlewareP","kind":"typeIdentifier","text":"Middleware"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK10MiddlewareP","text":"Middleware"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterNoSectionsLocalisedDescription":{"title":"ZDKHelpCenterNoSectionsLocalisedDescription","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"}],"url":"\/documentation\/supportsdk\/zdkhelpcenternosectionslocaliseddescription","abstract":[{"type":"text","text":"Error description for section id error."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoSectionsLocalisedDescription","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterError","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcentererror","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Help Center error codes."}],"title":"ZDKHelpCenterError","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestCoordinator":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestCoordinator","kind":"identifier"}],"url":"\/documentation\/supportsdk\/requestcoordinator","abstract":[],"navigatorTitle":[{"text":"RequestCoordinator","kind":"identifier"}],"title":"RequestCoordinator","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","type":"topic","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/AsyncMiddleware":{"url":"\/documentation\/supportsdk\/asyncmiddleware","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AsyncMiddleware"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/AsyncMiddleware","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsyncMiddleware"}],"role":"symbol","title":"AsyncMiddleware","type":"topic","abstract":[{"text":"Async Middleware handles actions of type ","type":"text"},{"type":"codeVoice","code":"AsyncAction"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/AsyncAction":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AsyncAction","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/AsyncAction","abstract":[{"text":"Async action this type of action is intercepted by ","type":"text"},{"type":"codeVoice","code":"AsyncMiddleware"},{"type":"text","text":" and is not dispatched to the reducer."}],"navigatorTitle":[{"text":"AsyncAction","kind":"identifier"}],"kind":"symbol","title":"AsyncAction","url":"\/documentation\/supportsdk\/asyncaction"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration":{"navigatorTitle":[{"text":"ArticleUiConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Data class used to configure Article Screen"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration","type":"topic","title":"ArticleUiConfiguration","url":"\/documentation\/supportsdk\/articleuiconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ArticleUiConfiguration","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/GetStateFunction":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GetStateFunction"}],"url":"\/documentation\/supportsdk\/getstatefunction","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/GetStateFunction","title":"GetStateFunction","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GetStateFunction"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterDelegate":{"kind":"symbol","title":"HelpCenterDelegate","url":"\/documentation\/supportsdk\/helpcenterdelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterDelegate","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterDelegate"}],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","abstract":[],"kind":"symbol","role":"symbol","title":"ContainerViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContainerViewController","kind":"identifier"}],"navigatorTitle":[{"text":"ContainerViewController","kind":"identifier"}],"url":"\/documentation\/supportsdk\/containerviewcontroller","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","navigatorTitle":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterUi","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"title":"ZDKHelpCenterUi","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterui"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterCellConfigureBlock":{"type":"topic","title":"ZDKHelpCenterCellConfigureBlock","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterCellConfigureBlock","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterCellConfigureBlock"}],"url":"\/documentation\/supportsdk\/zdkhelpcentercellconfigureblock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterCellConfigureBlock"}],"abstract":[{"type":"text","text":"A block for configuring cells. This is invoked in cell for row at index path."}],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/+(_:_:)-8bv54":{"title":"+(_:_:)","kind":"symbol","abstract":[{"text":"Combines two reducers. The combined reducer calls each of its internal reducer for a each paricular state key.","type":"text"}],"url":"\/documentation\/supportsdk\/+(_:_:)-8bv54","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"+"},{"text":" ","kind":"text"},{"text":"<","kind":"text"},{"text":"R1","kind":"genericParameter"},{"kind":"text","text":", "},{"text":"R2","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"R1","kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK1poiyAA15CombinedReducerCx_q_tAA0D0RzAaER_r0_lF2R1L_xmfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK1poiyAA15CombinedReducerCx_q_tAA0D0RzAaER_r0_lF2R2L_q_mfp","text":"R2"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK15CombinedReducerC","text":"CombinedReducer"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/+(_:_:)-8bv54"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/MiddlewareFunction":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MiddlewareFunction","kind":"identifier"}],"url":"\/documentation\/supportsdk\/middlewarefunction","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/MiddlewareFunction","title":"MiddlewareFunction","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MiddlewareFunction","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicator":{"abstract":[{"text":"This class tries to fix the layout spacing when using XIB instead of storyboard.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Since we cannot reference the top\/bottom layout guids. This class fixes the top\/bottom layout to be relative to the guides."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKLayoutGuideApplicator","kind":"identifier"}],"title":"ZDKLayoutGuideApplicator","url":"\/documentation\/supportsdk\/zdklayoutguideapplicator","navigatorTitle":[{"text":"ZDKLayoutGuideApplicator","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate":{"abstract":[{"text":"Delegate for the create request view.","type":"text"}],"title":"ZDKCreateRequestUIDelegate","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate","type":"topic","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate","navigatorTitle":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ActionSubscription":{"navigatorTitle":[{"text":"ActionSubscription","kind":"identifier"}],"url":"\/documentation\/supportsdk\/actionsubscription","abstract":[{"type":"text","text":"Subscription structure that represents a listener subscription."},{"text":" ","type":"text"},{"text":"When adding a listener you get a subscription back.","type":"text"},{"type":"text","text":" "},{"text":"You can use this subscription to remove the listener, notify about the current state or link the listener lifecycle with an object.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ActionSubscription","kind":"symbol","title":"ActionSubscription","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionSubscription","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/KeyedState":{"kind":"symbol","title":"KeyedState","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/KeyedState","navigatorTitle":[{"kind":"identifier","text":"KeyedState"}],"url":"\/documentation\/supportsdk\/keyedstate","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyedState"}],"abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController":{"url":"\/documentation\/supportsdk\/coordinatingviewcontroller","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","title":"CoordinatingViewController","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinatingViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CoordinatingViewController"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI":{"kind":"symbol","role":"symbol","abstract":[],"title":"SupportUI","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportUI","kind":"identifier"}],"url":"\/documentation\/supportsdk\/supportui","navigatorTitle":[{"kind":"identifier","text":"SupportUI"}],"deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Theme","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKConstants","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate"],"title":"Protocols"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterEmptyHelpCenterDescription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterErrorDomain","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoArticlesForLabelsDescription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoCategoriesLocalisedDescription","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoSectionsLocalisedDescription"],"title":"Variables"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGCenterRectInRect(_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGMakeCenteredRectInRect(_:_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGMakeCenteredRectOnXInRect(_:_:_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGRectMakeCenteredInScreen(_:_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIIsLandscape()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIOriginInWindow(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIScreenFrame()"],"title":"Functions"},{"title":"Macros","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SYSTEM_VERSION_GREATER_THAN_SEVEN","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportSDK_h","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDLog","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZD_IS_IPAD","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZD_IS_IPHONE"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterCellConfigureBlock","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDUISpinner"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType"],"title":"Enumerations"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"ZDKUIUtil","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments","value":[{"kind":"identifier","text":"ZDKUIUtil"}],"op":"replace"},{"op":"replace","value":"HelpCenterArticleVotingHandler","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/fragments","value":[{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title","op":"replace","value":"ZDKHelpCenterDelegate"},{"value":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGCenterRectInRect(_:_:)\/title","value":"CGCenterRectInRect"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGCenterRectInRect(_:_:)\/fragments","value":[{"text":"CGCenterRectInRect","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/title","value":"ZDKRequestUiConfiguration"},{"value":[{"kind":"identifier","text":"ZDKRequestUiConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIIsLandscape()\/title","value":"ZDKUIIsLandscape"},{"value":[{"kind":"identifier","text":"ZDKUIIsLandscape"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIIsLandscape()\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDUISpinner\/title","value":"ZDUISpinner","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDUISpinner\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDUISpinner"}]},{"value":"ZDKToastViewWrapper","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/fragments","value":[{"text":"ZDKToastViewWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterErrorDomain\/title","op":"replace","value":"ZDKHelpCenterErrorDomain"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterErrorDomain\/fragments","value":[{"text":"ZDKHelpCenterErrorDomain","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/title","value":"ZDKCoordinator"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/fragments","op":"replace","value":[{"text":"ZDKCoordinator","kind":"identifier"}]},{"value":"ZDKConstants","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKConstants\/title"},{"op":"replace","value":[{"text":"ZDKConstants","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKConstants\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGMakeCenteredRectInRect(_:_:_:)\/title","value":"CGMakeCenteredRectInRect"},{"value":[{"kind":"identifier","text":"CGMakeCenteredRectInRect"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGMakeCenteredRectInRect(_:_:_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/title","value":"ZDKSpinnerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/fragments"},{"op":"replace","value":"ZDKSupportEngine","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/title"},{"value":[{"text":"ZDKSupportEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/title","value":"ZDKHelpCenterUiConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUiConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration\/title","value":"ZDKRequestListUiConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration\/fragments","value":[{"text":"ZDKRequestListUiConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIOriginInWindow(_:)\/title","value":"ZDKUIOriginInWindow"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIOriginInWindow(_:)\/fragments","value":[{"kind":"identifier","text":"ZDKUIOriginInWindow"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/title","value":"ZDKContactUsVisibility"},{"value":[{"kind":"identifier","text":"ZDKContactUsVisibility"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/fragments","op":"replace"},{"value":"ZDKRequestUi","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestUi"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoCategoriesLocalisedDescription\/title","op":"replace","value":"ZDKHelpCenterNoCategoriesLocalisedDescription"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoCategoriesLocalisedDescription\/fragments","value":[{"text":"ZDKHelpCenterNoCategoriesLocalisedDescription","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKHelpCenterCoordinator","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterCoordinator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/title","value":"ZDKDismissUtil","op":"replace"},{"op":"replace","value":[{"text":"ZDKDismissUtil","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/fragments"},{"value":"ZDKHelpCenterArticleRatingStateProtocol","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/fragments","value":[{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"op":"replace"},{"value":"ZDKSuasDebugLogger","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/title"},{"value":[{"text":"ZDKSuasDebugLogger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGMakeCenteredRectOnXInRect(_:_:_:_:)\/title","value":"CGMakeCenteredRectOnXInRect","op":"replace"},{"value":[{"text":"CGMakeCenteredRectOnXInRect","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGMakeCenteredRectOnXInRect(_:_:_:_:)\/fragments"},{"value":"ZDKContainerChildControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterEmptyHelpCenterDescription\/title","value":"ZDKHelpCenterEmptyHelpCenterDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterEmptyHelpCenterDescription\/fragments","value":[{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/title","value":"ZDKHelpCenterDataSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/fragments","value":[{"text":"ZDKHelpCenterDataSource","kind":"identifier"}]},{"value":"ZDKHelpCenterConversationsUIDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/title","value":"ZDKSupportAttachmentCell","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKSupportAttachmentCell"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIScreenFrame()\/title","op":"replace","value":"ZDKUIScreenFrame"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIScreenFrame()\/fragments","value":[{"text":"ZDKUIScreenFrame","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme\/title","op":"replace","value":"ZDKTheme"},{"value":[{"text":"ZDKTheme","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Theme\/fragments"},{"value":"CGRectMakeCenteredInScreen","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGRectMakeCenteredInScreen(_:_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGRectMakeCenteredInScreen(_:_:)\/fragments","value":[{"text":"CGRectMakeCenteredInScreen","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/title","op":"replace","value":"ZDKRequestAttachment"},{"op":"replace","value":[{"text":"ZDKRequestAttachment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/fragments"},{"value":"ZDKContainerChild","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/fragments","value":[{"kind":"identifier","text":"ZDKContainerChild"}]},{"value":"ZDKNavBarCreateRequestUIType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/title"},{"op":"replace","value":[{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/fragments"},{"value":"ZDKLayoutGuideApplicatorPosition","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/fragments","value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/title","op":"replace","value":"ZDKHelpCenterContactUsRouter"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterContactUsRouter"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoArticlesForLabelsDescription\/title","value":"ZDKHelpCenterNoArticlesForLabelsDescription"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoArticlesForLabelsDescription\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterNoArticlesForLabelsDescription"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","op":"replace","value":"ZDKFileType"},{"value":[{"text":"ZDKFileType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","op":"replace"},{"value":"ZDKHelpCenterArticleRatingHandlerProtocol","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}]},{"op":"replace","value":"ZDKHelpCenterAttachmentsDataSource","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoSectionsLocalisedDescription\/title","value":"ZDKHelpCenterNoSectionsLocalisedDescription"},{"value":[{"text":"ZDKHelpCenterNoSectionsLocalisedDescription","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoSectionsLocalisedDescription\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/title","op":"replace","value":"ZDKHelpCenterError"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterError"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/fragments","op":"replace"},{"value":"RequestCoordinator","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/fragments","op":"replace","value":[{"text":"RequestCoordinator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/title","value":"ZDKArticleUiConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKArticleUiConfiguration"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/title","value":"ContainerViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/fragments","value":[{"kind":"identifier","text":"ContainerViewController"}],"op":"replace"},{"op":"replace","value":"ZDKHelpCenterUi","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterCellConfigureBlock\/title","value":"ZDKHelpCenterCellConfigureBlock"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterCellConfigureBlock\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterCellConfigureBlock"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/title","value":"ZDKLayoutGuideApplicator"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/title","value":"ZDKCreateRequestUIDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/fragments","op":"replace","value":[{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}]},{"value":"ZDKCoordinatingViewController","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKCoordinatingViewController"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/title","value":"ZDKSupportUI"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKSupportUI"}]}]}]}