{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/isVisible","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper"]]},"variants":[{"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper\/isvisible"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper\/isvisible"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"externalID":"c:objc(cs)ZDKToastViewWrapper(py)isVisible","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"SupportSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isVisible"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isVisible"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKToastViewWrapper"}],"url":"\/documentation\/supportsdk\/zdktoastviewwrapper","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","role":"symbol","title":"ZDKToastViewWrapper","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ZDKToastViewWrapper","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/isVisible":{"abstract":[],"type":"topic","url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/isvisible","title":"isVisible","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isVisible"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVisible","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/isVisible"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"isVisible","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"isVisible"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVisible"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/title","op":"replace","value":"ZDKToastViewWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/fragments","value":[{"kind":"identifier","text":"ZDKToastViewWrapper"}]},{"value":"isVisible","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1isVisible\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isVisible"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1isVisible\/fragments"}]}]}