{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/emptyhelpcenter"]},{"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/emptyhelpcenter"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"emptyHelpCenter","kind":"identifier"}],"title":"ZDKHelpCenterError.emptyHelpCenter","navigatorTitle":[{"text":"ZDKHelpCenterErrorEmptyHelpCenter","kind":"identifier"}],"externalID":"c:@E@ZDKHelpCenterError@ZDKHelpCenterErrorEmptyHelpCenter","symbolKind":"case","role":"symbol","modules":[{"name":"SupportSDK"}]},"abstract":[{"type":"text","text":"Help Center has no content."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emptyHelpCenter","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/emptyHelpCenter","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterError","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcentererror","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Help Center error codes."}],"title":"ZDKHelpCenterError","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/emptyHelpCenter":{"title":"ZDKHelpCenterError.emptyHelpCenter","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"emptyHelpCenter","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/emptyHelpCenter","abstract":[{"text":"Help Center has no content.","type":"text"}],"kind":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/emptyhelpcenter","navigatorTitle":[{"text":"ZDKHelpCenterErrorEmptyHelpCenter","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKHelpCenterErrorEmptyHelpCenter","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"ZDKHelpCenterErrorEmptyHelpCenter","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKHelpCenterErrorEmptyHelpCenter","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/title","value":"ZDKHelpCenterError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/fragments","value":[{"text":"ZDKHelpCenterError","kind":"identifier"}]},{"op":"replace","value":"ZDKHelpCenterErrorEmptyHelpCenter","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1emptyHelpCenter\/title"},{"value":[{"text":"ZDKHelpCenterErrorEmptyHelpCenter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1emptyHelpCenter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}