{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/noArticlesForLabels","interfaceLanguage":"swift"},"metadata":{"title":"ZDKHelpCenterError.noArticlesForLabels","role":"symbol","roleHeading":"Case","symbolKind":"case","externalID":"c:@E@ZDKHelpCenterError@ZDKHelpCenterErrorNoArticlesForLabels","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterErrorNoArticlesForLabels"}],"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noArticlesForLabels","kind":"identifier"}]},"abstract":[{"text":"No articles were found with the specified labels.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/noarticlesforlabels"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/noarticlesforlabels"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noArticlesForLabels"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/noArticlesForLabels":{"kind":"symbol","title":"ZDKHelpCenterError.noArticlesForLabels","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/noarticlesforlabels","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/noArticlesForLabels","abstract":[{"type":"text","text":"No articles were found with the specified labels."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noArticlesForLabels","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterErrorNoArticlesForLabels"}],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterError","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcentererror","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Help Center error codes."}],"title":"ZDKHelpCenterError","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKHelpCenterErrorNoArticlesForLabels"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterErrorNoArticlesForLabels","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKHelpCenterErrorNoArticlesForLabels"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1noArticlesForLabels\/title","value":"ZDKHelpCenterErrorNoArticlesForLabels","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1noArticlesForLabels\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterErrorNoArticlesForLabels"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/title","value":"ZDKHelpCenterError"},{"value":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}