{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype\/pdf"]},{"paths":["\/documentation\/supportsdk\/filetype\/pdf"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdf"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"case","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePdf"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypePdf","title":"FileType.pdf","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdf"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pdf"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/pdf":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pdf","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ZDKFileTypePdf","kind":"identifier"}],"title":"FileType.pdf","kind":"symbol","url":"\/documentation\/supportsdk\/filetype\/pdf","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pdf","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","title":"FileType","navigatorTitle":[{"text":"FileType","kind":"identifier"}],"url":"\/documentation\/supportsdk\/filetype","type":"topic","kind":"symbol","abstract":[{"text":"Enum that represents the file types that zendesk supports","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileType"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKFileTypePdf"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypePdf"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKFileTypePdf"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1pdf\/title","value":"ZDKFileTypePdf"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1pdf\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypePdf"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","value":"ZDKFileType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFileType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}