{"variants":[{"paths":["\/documentation\/supportsdk\/coordinatingviewcontroller\/init(coordinator:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/coordinatingviewcontroller\/init(coordinator:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"coordinator"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","text":"Coordinator","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKCoordinator"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController"]]},"metadata":{"navigatorTitle":[{"text":"initWithCoordinator:","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"coordinator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Coordinator","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKCoordinator"},{"text":")","kind":"text"}],"title":"init(coordinator:)","roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@SupportSDK@objc(cs)ZDKCoordinatingViewController(im)initWithCoordinator:"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/init(coordinator:)"},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CoordinatingViewController","kind":"identifier"}],"navigatorTitle":[{"text":"CoordinatingViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportsdk\/coordinatingviewcontroller","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","kind":"symbol","title":"CoordinatingViewController"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/coordinator","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinator"}],"navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"title":"Coordinator"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController/init(coordinator:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/coordinatingviewcontroller\/init(coordinator:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/init(coordinator:)","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coordinator"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKCoordinator","text":"Coordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(coordinator:)","navigatorTitle":[{"text":"initWithCoordinator:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithCoordinator:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCoordinator:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithCoordinator:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<ZDKCoordinator>","preciseIdentifier":"c:Qo@M@SupportSDK@objc(pl)ZDKCoordinator","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"coordinator","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKCoordinatingViewController","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/fragments","value":[{"kind":"identifier","text":"ZDKCoordinatingViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/title","value":"ZDKCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/fragments","value":[{"text":"ZDKCoordinator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1init(coordinator:)\/title","op":"replace","value":"initWithCoordinator:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoordinator:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1init(coordinator:)\/fragments"}]}]}