{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/init(helpCenterController:uiConfigurations:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"helpCenterController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ContainerChild","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChild"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiConfigurations"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"kind":"text","text":"] = [])"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"helpCenterController","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ContainerChild","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChild","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"uiConfigurations","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"])"}],"roleHeading":"Initializer","title":"init(helpCenterController:uiConfigurations:)","navigatorTitle":[{"kind":"identifier","text":"initWithHelpCenterController:uiConfigurations:"}],"modules":[{"name":"SupportSDK"}],"role":"symbol","externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterCoordinator(im)initWithHelpCenterController:uiConfigurations:","symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcentercoordinator\/init(helpcentercontroller:uiconfigurations:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcentercoordinator\/init(helpcentercontroller:uiconfigurations:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChild":{"role":"symbol","title":"ContainerChild","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContainerChild","kind":"identifier"}],"url":"\/documentation\/supportsdk\/containerchild","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","navigatorTitle":[{"kind":"identifier","text":"ContainerChild"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator/init(helpCenterController:uiConfigurations:)":{"url":"\/documentation\/supportsdk\/helpcentercoordinator\/init(helpcentercontroller:uiconfigurations:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"helpCenterController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContainerChild","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChild","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"uiConfigurations","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"])"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithHelpCenterController:uiConfigurations:","kind":"identifier"}],"title":"init(helpCenterController:uiConfigurations:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/init(helpCenterController:uiConfigurations:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator":{"url":"\/documentation\/supportsdk\/helpcentercoordinator","navigatorTitle":[{"kind":"identifier","text":"HelpCenterCoordinator"}],"type":"topic","title":"HelpCenterCoordinator","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterCoordinator"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithHelpCenterController:uiConfigurations:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithHelpCenterController:uiConfigurations:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithHelpCenterController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)UIViewController@M@SupportSDK@objc(pl)ZDKContainerChild","kind":"typeIdentifier","text":"UIViewController<ZDKContainerChild>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"helpCenterController"},{"text":" ","kind":"text"},{"text":"uiConfigurations:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<ZDKConfiguration>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"uiConfigurations","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKContainerChild","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/fragments","value":[{"kind":"identifier","text":"ZDKContainerChild"}],"op":"replace"},{"value":"initWithHelpCenterController:uiConfigurations:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1init(helpCenterController:uiConfigurations:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1init(helpCenterController:uiConfigurations:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithHelpCenterController:uiConfigurations:"}]},{"value":"ZDKHelpCenterCoordinator","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/fragments","value":[{"text":"ZDKHelpCenterCoordinator","kind":"identifier"}],"op":"replace"}]}]}