{"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ticketFormID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"title":"ticketFormID","modules":[{"name":"SupportSDK"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUiConfiguration(py)ticketFormID","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"ticketFormID"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The ticket form of any created tickets.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/ticketFormID","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ticketFormID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"If this property is set "},{"type":"codeVoice","code":"fields"},{"type":"text","text":" must also be set. Any ticket fields set will be associated with "},{"code":"tickerFormID","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"name":"Version","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/ticketformid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/ticketformid"]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration/ticketFormID":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/ticketFormID","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ticketFormID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","kind":"symbol","title":"ticketFormID","url":"\/documentation\/supportsdk\/requestuiconfiguration\/ticketformid","navigatorTitle":[{"text":"ticketFormID","kind":"identifier"}],"abstract":[{"text":"The ticket form of any created tickets.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration":{"abstract":[{"type":"text","text":"Data class used to configure Ticketing"}],"type":"topic","url":"\/documentation\/supportsdk\/requestuiconfiguration","title":"RequestUiConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestUiConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"RequestUiConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ticketFormID"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"ticketFormID","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" * "},{"text":"ticketFormID","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1ticketFormID\/title","value":"ticketFormID"},{"op":"replace","value":[{"kind":"identifier","text":"ticketFormID"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1ticketFormID\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/title","value":"ZDKRequestUiConfiguration"},{"op":"replace","value":[{"text":"ZDKRequestUiConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}