{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/zdksupportattachmentcell\/filesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdksupportattachmentcell\/filesize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/fileSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A label which displays the articles parent category and section."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"title":"fileSize","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ZDKSupportAttachmentCell(py)fileSize","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"fileSize"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell":{"role":"symbol","title":"ZDKSupportAttachmentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSupportAttachmentCell"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKSupportAttachmentCell"}],"url":"\/documentation\/supportsdk\/zdksupportattachmentcell"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell/fileSize":{"role":"symbol","title":"fileSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"A label which displays the articles parent category and section."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/fileSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileSize"}],"url":"\/documentation\/supportsdk\/zdksupportattachmentcell\/filesize"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fileSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fileSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fileSize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/title","value":"ZDKSupportAttachmentCell"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/fragments","value":[{"kind":"identifier","text":"ZDKSupportAttachmentCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1fileSize\/title","value":"fileSize"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1fileSize\/fragments","value":[{"kind":"identifier","text":"fileSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}