{"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterCoordinator","kind":"identifier"}],"role":"symbol","externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterCoordinator","symbolKind":"class","navigatorTitle":[{"text":"HelpCenterCoordinator","kind":"identifier"}],"title":"HelpCenterCoordinator"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKHelpCenterCoordinator) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterCoordinator"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcentercoordinator"]},{"paths":["\/documentation\/supportsdk\/helpcentercoordinator"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/init(helpCenterController:uiConfigurations:)"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/start(present:with:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator/start(present:with:)":{"url":"\/documentation\/supportsdk\/helpcentercoordinator\/start(present:with:)","navigatorTitle":[{"kind":"identifier","text":"startWithPresent:with:"}],"type":"topic","title":"start(present:with:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/start(present:with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"present"},{"kind":"text","text":": ("},{"text":"ContainerChildController","kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","text":"ContainerChildControllerDelegate"},{"kind":"text","text":")"}],"role":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator/init(helpCenterController:uiConfigurations:)":{"url":"\/documentation\/supportsdk\/helpcentercoordinator\/init(helpcentercontroller:uiconfigurations:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"helpCenterController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContainerChild","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChild","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"uiConfigurations","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"])"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithHelpCenterController:uiConfigurations:","kind":"identifier"}],"title":"init(helpCenterController:uiConfigurations:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/init(helpCenterController:uiConfigurations:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator":{"kind":"symbol","url":"\/documentation\/supportsdk\/coordinator","title":"Coordinator","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinator"}]},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator":{"url":"\/documentation\/supportsdk\/helpcentercoordinator","navigatorTitle":[{"kind":"identifier","text":"HelpCenterCoordinator"}],"type":"topic","title":"HelpCenterCoordinator","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterCoordinator"}],"role":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ZDKHelpCenterCoordinator","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"ZDKHelpCenterCoordinator","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKHelpCenterCoordinator","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/init(helpCenterController:uiConfigurations:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/start(present:with:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterCoordinator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"startWithPresent:with:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1start(present:with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithPresent:with:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1start(present:with:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1init(helpCenterController:uiConfigurations:)\/title","value":"initWithHelpCenterController:uiConfigurations:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithHelpCenterController:uiConfigurations:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1init(helpCenterController:uiConfigurations:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/title","value":"ZDKCoordinator"},{"value":[{"kind":"identifier","text":"ZDKCoordinator"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/fragments","op":"replace"},{"op":"replace","value":"ZDKHelpCenterCoordinator","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterCoordinator"}],"op":"replace"}]}]}