{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter"]},{"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/init(withPresentingViewController:configurations:engines:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForEmptySearch()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForNavBar()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterContactUsRouter","symbolKind":"class","role":"symbol","modules":[{"name":"SupportSDK"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"title":"HelpCenterContactUsRouter","navigatorTitle":[{"text":"HelpCenterContactUsRouter","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKHelpCenterContactUsRouter) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterContactUsRouter"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"kind":"symbol","title":"HelpCenterContactUsRouter","type":"topic","url":"\/documentation\/supportsdk\/helpcentercontactusrouter","navigatorTitle":[{"text":"HelpCenterContactUsRouter","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter/decideButtonActionForEmptySearch()":{"type":"topic","title":"decideButtonActionForEmptySearch()","kind":"symbol","navigatorTitle":[{"text":"decideButtonActionForEmptySearch","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForEmptySearch()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decideButtonActionForEmptySearch","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionforemptysearch()","role":"symbol"},"doc://com.zendesk.SupportSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter/decideButtonActionForNavBar()":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForNavBar()","url":"\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionfornavbar()","title":"decideButtonActionForNavBar()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decideButtonActionForNavBar"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"text":"decideButtonActionForNavBar","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter/init(withPresentingViewController:configurations:engines:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/init(withPresentingViewController:configurations:engines:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withPresentingViewController","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configurations"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration"},{"kind":"text","text":"], "},{"text":"engines","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ZDKEngine","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine"},{"text":"])","kind":"text"}],"title":"init(withPresentingViewController:configurations:engines:)","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/helpcentercontactusrouter\/init(withpresentingviewcontroller:configurations:engines:)","navigatorTitle":[{"kind":"identifier","text":"initWithPresentingViewController:configurations:engines:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterContactUsRouter"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKHelpCenterContactUsRouter","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKHelpCenterContactUsRouter","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForEmptySearch()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForNavBar()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/init(withPresentingViewController:configurations:engines:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterContactUsRouter"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/title","op":"replace","value":"ZDKHelpCenterContactUsRouter"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/fragments","value":[{"text":"ZDKHelpCenterContactUsRouter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForEmptySearch()\/title","op":"replace","value":"decideButtonActionForEmptySearch"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForEmptySearch()\/fragments","value":[{"kind":"text","text":"- "},{"text":"decideButtonActionForEmptySearch","kind":"identifier"}]},{"value":"decideButtonActionForNavBar","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForNavBar()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForNavBar()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"decideButtonActionForNavBar","kind":"identifier"}]},{"value":"initWithPresentingViewController:configurations:engines:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1init(withPresentingViewController:configurations:engines:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1init(withPresentingViewController:configurations:engines:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPresentingViewController:configurations:engines:"}]}]}]}