{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RequestAttachment","kind":"identifier"}],"navigatorTitle":[{"text":"RequestAttachment","kind":"identifier"}],"roleHeading":"Class","role":"symbol","title":"RequestAttachment","symbolKind":"class","modules":[{"name":"SupportSDK"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestAttachment"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Creates an attachment to be uploaded when a request is created","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/init(filename:data:fileType:)"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/data","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/fileType","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/filename"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKRequestAttachment) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestAttachment","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"style":"note","type":"aside","name":"Version","content":[{"inlineContent":[{"text":"2.0.0","type":"text"}],"type":"paragraph"}]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestattachment"]},{"paths":["\/documentation\/supportsdk\/requestattachment"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment/init(filename:data:fileType:)":{"role":"symbol","title":"init(filename:data:fileType:)","navigatorTitle":[{"kind":"identifier","text":"initWithFilename:data:fileType:"}],"abstract":[{"text":"Generates a new state from the old state and an action","type":"text"}],"url":"\/documentation\/supportsdk\/requestattachment\/init(filename:data:filetype:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/init(filename:data:fileType:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"filename","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":", ","kind":"text"},{"text":"fileType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FileType","preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment/data":{"title":"data","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/data","url":"\/documentation\/supportsdk\/requestattachment\/data","abstract":[{"type":"text","text":"Data of the file contents to be uploaded"}],"role":"symbol","navigatorTitle":[{"text":"data","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment/filename":{"role":"symbol","abstract":[{"text":"Name of the file to be uploaded","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"filename"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"filename","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/filename","url":"\/documentation\/supportsdk\/requestattachment\/filename","navigatorTitle":[{"text":"filename","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment/fileType":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType","kind":"typeIdentifier","text":"FileType"}],"type":"topic","abstract":[{"type":"text","text":"Type of the file to be uploaded"}],"navigatorTitle":[{"kind":"identifier","text":"fileType"}],"kind":"symbol","url":"\/documentation\/supportsdk\/requestattachment\/filetype","title":"fileType","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/fileType"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestAttachment","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment","title":"RequestAttachment","role":"symbol","url":"\/documentation\/supportsdk\/requestattachment","abstract":[{"text":"Creates an attachment to be uploaded when a request is created","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RequestAttachment"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"ZDKRequestAttachment","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKRequestAttachment","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKRequestAttachment"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/data","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/fileType","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/filename"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/init(filename:data:fileType:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRequestAttachment"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"initWithFilename:data:fileType:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1init(filename:data:fileType:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFilename:data:fileType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1init(filename:data:fileType:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1data\/title","value":"data"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1data\/fragments","value":[{"kind":"identifier","text":"data"}]},{"value":"filename","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1filename\/title"},{"value":[{"text":"filename","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1filename\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1fileType\/title","value":"fileType"},{"op":"replace","value":[{"kind":"identifier","text":"fileType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1fileType\/fragments"},{"value":"ZDKRequestAttachment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestAttachment"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/fragments"}]}]}