{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/12MessagingAPI6EngineP","doc:\/\/com.zendesk.SupportSDK\/12MessagingAPI10ObservableP","doc:\/\/com.zendesk.SupportSDK\/@M@MessagingAPI@objc(pl)ZDKEngine","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"type":"conformsTo"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SupportEngine","kind":"identifier"}],"role":"symbol","roleHeading":"Class","title":"SupportEngine","externalID":"c:@M@SupportSDK@objc(cs)ZDKSupportEngine","symbolKind":"class","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"SupportEngine","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/supportengine"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/supportengine"]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/configs","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/id","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/onUpdate","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/transferOptionDescription"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/isConversationOngoing()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/isConversationOngoing(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/onEvent(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/start(messagingAPI:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/stop()"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/engine()"],"title":"Type Methods"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/Engine-Implementations","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/Observable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKSupportEngine) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SupportEngine","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/engine()":{"abstract":[],"title":"engine()","navigatorTitle":[{"text":"engineAndReturnError:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/engine()","role":"symbol","url":"\/documentation\/supportsdk\/supportengine\/engine()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"engine","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportEngine","text":"SupportEngine"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/onUpdate":{"abstract":[],"title":"onUpdate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/onUpdate","role":"symbol","url":"\/documentation\/supportsdk\/supportengine\/onupdate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onUpdate","kind":"identifier"},{"text":": ([","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"kind":"text","text":" : ("},{"text":"Update","preciseIdentifier":"s:12MessagingAPI6UpdateO","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":"])","kind":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine":{"type":"topic","title":"SupportEngine","kind":"symbol","url":"\/documentation\/supportsdk\/supportengine","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportEngine","kind":"identifier"}],"navigatorTitle":[{"text":"SupportEngine","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/transferOptionDescription":{"abstract":[],"title":"transferOptionDescription","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/transferOptionDescription","role":"symbol","url":"\/documentation\/supportsdk\/supportengine\/transferoptiondescription","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transferOptionDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKTransferOptionDescription","text":"TransferOptionDescription"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/Observable-Implementations":{"type":"topic","title":"Observable Implementations","url":"\/documentation\/supportsdk\/supportengine\/observable-implementations","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/Observable-Implementations"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/isConversationOngoing()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isConversationOngoing"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/isConversationOngoing()","role":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/supportengine\/isconversationongoing()","kind":"symbol","type":"topic","title":"isConversationOngoing()"},"doc://com.zendesk.SupportSDK/12MessagingAPI6EngineP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/12MessagingAPI6EngineP","title":"MessagingAPI.Engine"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/Engine-Implementations":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/Engine-Implementations","role":"collectionGroup","url":"\/documentation\/supportsdk\/supportengine\/engine-implementations","abstract":[],"kind":"article","type":"topic","title":"Engine Implementations"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportSDK/@M@MessagingAPI@objc(pl)ZDKEngine":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/@M@MessagingAPI@objc(pl)ZDKEngine","title":"MessagingAPI.ZDKEngine"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/id":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/id","role":"symbol","url":"\/documentation\/supportsdk\/supportengine\/id","abstract":[],"kind":"symbol","type":"topic","title":"id"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/isConversationOngoing(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isConversationOngoing"},{"text":"((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/isConversationOngoing(_:)","role":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/supportengine\/isconversationongoing(_:)","kind":"symbol","navigatorTitle":[{"text":"isConversationOngoing:","kind":"identifier"}],"type":"topic","title":"isConversationOngoing(_:)"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/12MessagingAPI10ObservableP":{"title":"MessagingAPI.Observable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/12MessagingAPI10ObservableP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/configs":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configs"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(cs)ZDKConfigurations","text":"Configurations","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/configs","role":"symbol","url":"\/documentation\/supportsdk\/supportengine\/configs","abstract":[],"kind":"symbol","type":"topic","title":"configs"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/start(messagingAPI:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"text":"messagingAPI","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI0A11APIProtocolP","text":"MessagingAPIProtocol"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/start(messagingAPI:)","url":"\/documentation\/supportsdk\/supportengine\/start(messagingapi:)","role":"symbol","type":"topic","title":"start(messagingAPI:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/onEvent(_:)":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onEvent"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI5EventO","text":"Event"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/onEvent(_:)","url":"\/documentation\/supportsdk\/supportengine\/onevent(_:)","role":"symbol","type":"topic","title":"onEvent(_:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/stop()":{"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stop","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/stop()","url":"\/documentation\/supportsdk\/supportengine\/stop()","role":"symbol","type":"topic","title":"stop()"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKSupportEngine"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKSupportEngine"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKSupportEngine"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/isConversationOngoing(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/engine()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSupportEngine"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine~1engine()\/title","value":"engineAndReturnError:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"engineAndReturnError:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine~1engine()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/title","value":"ZDKSupportEngine"},{"op":"replace","value":[{"text":"ZDKSupportEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine~1isConversationOngoing(_:)\/title","value":"isConversationOngoing:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isConversationOngoing:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine~1isConversationOngoing(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}