{"abstract":[{"type":"text","text":"Help Center error domain."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterErrorDomain","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererrordomain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererrordomain"]}],"metadata":{"modules":[{"name":"SupportSDK"}],"title":"ZDKHelpCenterErrorDomain","symbolKind":"var","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"ZDKHelpCenterErrorDomain","kind":"identifier"}],"role":"symbol","externalID":"c:@ZDKHelpCenterErrorDomain"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterErrorDomain":{"title":"ZDKHelpCenterErrorDomain","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterErrorDomain"}],"abstract":[{"text":"Help Center error domain.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterErrorDomain","url":"\/documentation\/supportsdk\/zdkhelpcentererrordomain","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKHelpCenterErrorDomain"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKHelpCenterErrorDomain","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterErrorDomain"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterErrorDomain\/title","value":"ZDKHelpCenterErrorDomain","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterErrorDomain\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterErrorDomain"}],"op":"replace"}]}]}