{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/bottom","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/top"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/Equatable-Implementations","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/SY","doc:\/\/com.zendesk.SupportSDK\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicatorposition"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicatorposition"]}],"abstract":[{"text":"Layout guides positions to fix","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"sections":[],"metadata":{"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"externalID":"c:@E@ZDKLayoutGuideApplicatorPosition","navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"symbolKind":"enum","modules":[{"name":"SupportSDK"}],"role":"symbol","title":"ZDKLayoutGuideApplicatorPosition"},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/bottom":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/bottom","title":"ZDKLayoutGuideApplicatorPosition.bottom","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/bottom","abstract":[{"text":"Fix the bottom guide layout position","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"}],"navigatorTitle":[{"text":"ZDKLayoutGuideApplicatorPositionBottom","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/top":{"role":"symbol","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/top","title":"ZDKLayoutGuideApplicatorPosition.top","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fix the top guide layout position"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionTop"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/top"},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition":{"kind":"symbol","navigatorTitle":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"abstract":[{"text":"Layout guides positions to fix","type":"text"}],"title":"ZDKLayoutGuideApplicatorPosition","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/RawRepresentable-Implementations","kind":"article","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/Equatable-Implementations":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/Equatable-Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/equatable-implementations","title":"Equatable Implementations"},"doc://com.zendesk.SupportSDK/s8SendableP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/SY":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/init(rawValue:)":{"kind":"symbol","abstract":[],"type":"topic","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/init(rawvalue:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/init(rawValue:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKLayoutGuideApplicatorPosition"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}]},{"value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/bottom","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/top"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"},{"kind":"text","text":": "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKLayoutGuideApplicatorPositionBottom","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1bottom\/title"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionBottom"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1bottom\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1top\/title","value":"ZDKLayoutGuideApplicatorPositionTop"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1top\/fragments","value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionTop"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/title","op":"replace","value":"ZDKLayoutGuideApplicatorPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/fragments","value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}