{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"type":"aside","name":"Version"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/suasdebuglogger\/enabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/suasdebuglogger\/enabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger\/enabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Toggle the Suas debug logging"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"enabled","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SupportSDK@objc(cs)ZDKSuasDebugLogger(cpy)enabled","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"enabled"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger"]]},"references":{"https://github.com/zendesk/Suas-iOS":{"title":"Suas","titleInlineContent":[{"type":"text","text":"Suas"}],"type":"link","identifier":"https:\/\/github.com\/zendesk\/Suas-iOS","url":"https:\/\/github.com\/zendesk\/Suas-iOS"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger":{"role":"symbol","title":"SuasDebugLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SuasDebugLogger"}],"abstract":[{"type":"text","text":"Used to enable "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/zendesk\/Suas-iOS"},{"type":"text","text":" logging."},{"type":"text","text":" "},{"type":"text","text":"Suas drives most of the Ticketing UI so the Suas logs can be useful for debugging it."},{"type":"text","text":" "},{"type":"text","text":"Enabling the Suas logger produces a lot of information and will slow down the SDK."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SuasDebugLogger"}],"url":"\/documentation\/supportsdk\/suasdebuglogger"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger/enabled":{"role":"symbol","title":"enabled","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Toggle the Suas debug logging"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger\/enabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enabled"}],"url":"\/documentation\/supportsdk\/suasdebuglogger\/enabled"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"enabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"enabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"enabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/title","value":"ZDKSuasDebugLogger"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/fragments","value":[{"kind":"identifier","text":"ZDKSuasDebugLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger~1enabled\/title","value":"enabled"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger~1enabled\/fragments","value":[{"kind":"identifier","text":"enabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}