{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:configurations:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:configurations:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:configurations:)"]}],"kind":"symbol","metadata":{"externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUi(cm)buildRequestUiWithRequestId:configurations:","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"SupportSDK"}],"role":"symbol","navigatorTitle":[{"text":"buildRequestUiWithRequestId:configurations:","kind":"identifier"}],"title":"buildRequestUi(requestId:configurations:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configurations"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Build the Request Ui with a list of Configurations."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildRequestUi","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"configurations","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"text":"]) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"requestId","content":[{"inlineContent":[{"text":"The ID of the ticket to display.","type":"text"}],"type":"paragraph"}]},{"name":"configurations","content":[{"inlineContent":[{"text":"A list of Configuration objects. You do not need to configure the controller being presented.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"content":[{"inlineContent":[{"text":"2.0.0","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note","name":"Version"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi":{"kind":"symbol","title":"RequestUi","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","navigatorTitle":[{"kind":"identifier","text":"RequestUi"}],"abstract":[{"type":"text","text":"Used to build view controller for ticketing. The returned objects must be presented inside a UINavigationController."},{"type":"text","text":" "},{"type":"text","text":"The containing navigation controller can be presented any way you see fit."}],"role":"symbol","type":"topic","url":"\/documentation\/supportsdk\/requestui","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestUi"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestUi(requestId:configurations:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:configurations:)","abstract":[{"type":"text","text":"Build the Request Ui with a list of Configurations."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configurations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"kind":"symbol","url":"\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:configurations:)","navigatorTitle":[{"kind":"identifier","text":"buildRequestUiWithRequestId:configurations:"}],"title":"buildRequestUi(requestId:configurations:)","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"buildRequestUiWithRequestId:configurations:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"buildRequestUiWithRequestId:configurations:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildRequestUiWithRequestId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requestId"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configurations"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"requestId","content":[{"inlineContent":[{"type":"text","text":"The ID of the ticket to display."}],"type":"paragraph"}]},{"name":"configurations","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of Configuration objects. You do not need to configure the controller being presented."}]}]}],"kind":"parameters"}},{"value":"ZDKRequestUi","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKRequestUi"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKRequestUi"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/navigatorTitle","op":"replace"},{"value":"buildRequestUiWithRequestId:configurations:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:configurations:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"buildRequestUiWithRequestId:configurations:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:configurations:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}