{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListAndArticle","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistandarticle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistandarticle"]}],"metadata":{"externalID":"c:@E@ZDKContactUsVisibility@ZDKContactUsVisibilityArticleListAndArticle","role":"symbol","navigatorTitle":[{"text":"ZDKContactUsVisibilityArticleListAndArticle","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"roleHeading":"Case","platforms":[],"symbolKind":"case","title":"ZDKContactUsVisibility.articleListAndArticle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"articleListAndArticle"}]},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}],"type":"paragraph"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleListAndArticle"}]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/articleListAndArticle":{"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistandarticle","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListAndArticle","type":"topic","deprecated":true,"role":"symbol","title":"ZDKContactUsVisibility.articleListAndArticle","navigatorTitle":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListAndArticle"}],"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"articleListAndArticle"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility":{"kind":"symbol","title":"ZDKContactUsVisibility","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","navigatorTitle":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKContactUsVisibility","kind":"identifier"}],"abstract":[{"text":"Used to select where conversations nav bar button will be active.","type":"text"}],"deprecated":true,"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ZDKContactUsVisibilityArticleListAndArticle","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKContactUsVisibilityArticleListAndArticle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKContactUsVisibilityArticleListAndArticle","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ZDKContactUsVisibilityArticleListAndArticle","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListAndArticle\/title"},{"value":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListAndArticle"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListAndArticle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/title","value":"ZDKContactUsVisibility","op":"replace"},{"value":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}