{"abstract":[{"type":"text","text":"The type of ids being used."}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupType","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKHelpCenterOverviewGroupType","preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"name":"Version","style":"note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/grouptype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/grouptype"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"groupType","kind":"identifier"}],"role":"symbol","modules":[{"name":"SupportSDK"}],"title":"groupType","externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterUiConfiguration(py)groupType","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"groupType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType","text":"ZDKHelpCenterOverviewGroupType"}]},"kind":"symbol","sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","abstract":[{"type":"text","text":"Data class used to configure Help Center"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration","title":"HelpCenterUiConfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/groupType":{"abstract":[{"text":"The type of ids being used.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupType","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/grouptype","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType","text":"ZDKHelpCenterOverviewGroupType"}],"navigatorTitle":[{"text":"groupType","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"groupType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"groupType","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"groupType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType","kind":"typeIdentifier","text":"ZDKHelpCenterOverviewGroupType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"ZDKHelpCenterUiConfiguration","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/fragments","value":[{"text":"ZDKHelpCenterUiConfiguration","kind":"identifier"}]},{"op":"replace","value":"groupType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1groupType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1groupType\/fragments","value":[{"kind":"identifier","text":"groupType"}]}]}]}