{"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/overviewContentModel","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/overviewcontentmodel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/overviewcontentmodel"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"overviewContentModel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel","kind":"typeIdentifier","text":"ZDKHelpCenterOverviewContentModel"},{"text":" { get }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterUiConfiguration(py)overviewContentModel","title":"overviewContentModel","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"overviewContentModel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel","kind":"typeIdentifier","text":"ZDKHelpCenterOverviewContentModel"}],"navigatorTitle":[{"text":"overviewContentModel","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","abstract":[{"type":"text","text":"Data class used to configure Help Center"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration","title":"HelpCenterUiConfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/overviewContentModel":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/overviewContentModel","kind":"symbol","title":"overviewContentModel","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/overviewcontentmodel","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"overviewContentModel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterOverviewContentModel","preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel"}],"navigatorTitle":[{"text":"overviewContentModel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"overviewContentModel","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"overviewContentModel","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel","text":"ZDKHelpCenterOverviewContentModel"},{"text":" * ","kind":"text"},{"text":"overviewContentModel","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"ZDKHelpCenterUiConfiguration","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/title"},{"value":[{"text":"ZDKHelpCenterUiConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1overviewContentModel\/title","value":"overviewContentModel","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1overviewContentModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"overviewContentModel"}]}]}]}