{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileAttachments"},{"kind":"text","text":": ["},{"text":"RequestAttachment","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKRequestAttachment","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"fileAttachments","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUiConfiguration(py)fileAttachments","title":"fileAttachments","modules":[{"name":"SupportSDK"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/fileattachments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/fileattachments"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"A list of RequestAttachments sent with any created tickets."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileAttachments","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"RequestAttachment","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKRequestAttachment"},{"text":"]","kind":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Note: These files are treated as any other. They will be displayed in the UI","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and the user will be able to remove them."}]},{"name":"Version","style":"note","content":[{"inlineContent":[{"text":"2.0.0","type":"text"}],"type":"paragraph"}],"type":"aside"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/fileAttachments","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestAttachment"}],"abstract":[{"text":"Creates an attachment to be uploaded when a request is created","type":"text"}],"navigatorTitle":[{"text":"RequestAttachment","kind":"identifier"}],"title":"RequestAttachment","kind":"symbol","url":"\/documentation\/supportsdk\/requestattachment","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration/fileAttachments":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fileAttachments","kind":"identifier"},{"text":": [","kind":"text"},{"text":"RequestAttachment","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKRequestAttachment","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"A list of RequestAttachments sent with any created tickets."}],"navigatorTitle":[{"kind":"identifier","text":"fileAttachments"}],"title":"fileAttachments","url":"\/documentation\/supportsdk\/requestuiconfiguration\/fileattachments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/fileAttachments","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestUiConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Data class used to configure Ticketing"}],"navigatorTitle":[{"text":"RequestUiConfiguration","kind":"identifier"}],"title":"RequestUiConfiguration","kind":"symbol","url":"\/documentation\/supportsdk\/requestuiconfiguration","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"fileAttachments","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"fileAttachments","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<ZDKRequestAttachment *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fileAttachments"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/title","value":"ZDKRequestAttachment"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/fragments","value":[{"text":"ZDKRequestAttachment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1fileAttachments\/title","value":"fileAttachments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1fileAttachments\/fragments","op":"replace","value":[{"kind":"identifier","text":"fileAttachments"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/title","value":"ZDKRequestUiConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/fragments","value":[{"text":"ZDKRequestUiConfiguration","kind":"identifier"}]}]}]}