{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Returns a default model. To customisze the content, update properties on a default model."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/init()"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"2.0.0","type":"text"}]}],"type":"aside","name":"Version","style":"note"}]}],"variants":[{"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/requestuiconfiguration\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUiConfiguration(im)init","title":"init()","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestUiConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Data class used to configure Ticketing"}],"navigatorTitle":[{"text":"RequestUiConfiguration","kind":"identifier"}],"title":"RequestUiConfiguration","kind":"symbol","url":"\/documentation\/supportsdk\/requestuiconfiguration","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUiConfiguration/init()":{"kind":"symbol","role":"symbol","title":"init()","abstract":[{"type":"text","text":"Returns a default model. To customisze the content, update properties on a default model."}],"url":"\/documentation\/supportsdk\/requestuiconfiguration\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUiConfiguration\/init()","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/title","value":"ZDKRequestUiConfiguration"},{"value":[{"kind":"identifier","text":"ZDKRequestUiConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUiConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}