{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/binary"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"binary"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype\/binary"]},{"paths":["\/documentation\/supportsdk\/filetype\/binary"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"metadata":{"modules":[{"name":"SupportSDK"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypeBinary","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"binary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeBinary"}],"title":"FileType.binary"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/binary":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/binary","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/binary","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"binary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeBinary"}],"title":"FileType.binary"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"type":"topic","navigatorTitle":[{"text":"FileType","kind":"identifier"}],"abstract":[{"text":"Enum that represents the file types that zendesk supports","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","title":"FileType","url":"\/documentation\/supportsdk\/filetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FileType","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKFileTypeBinary"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFileTypeBinary"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKFileTypeBinary"}],"languages":["occ"]}]},"op":"replace"},{"value":"ZDKFileTypeBinary","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1binary\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1binary\/fragments","op":"replace","value":[{"text":"ZDKFileTypeBinary","kind":"identifier"}]},{"op":"replace","value":"ZDKFileType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","value":[{"kind":"identifier","text":"ZDKFileType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}