{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"metadata":{"symbolKind":"case","roleHeading":"Case","title":"FileType.numbers","modules":[{"name":"SupportSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"numbers","kind":"identifier"}],"externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypeNumbers","navigatorTitle":[{"text":"ZDKFileTypeNumbers","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/numbers","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numbers"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype\/numbers"]},{"paths":["\/documentation\/supportsdk\/filetype\/numbers"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/numbers":{"abstract":[],"type":"topic","title":"FileType.numbers","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/numbers","role":"symbol","url":"\/documentation\/supportsdk\/filetype\/numbers","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numbers"}],"navigatorTitle":[{"text":"ZDKFileTypeNumbers","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"type":"topic","navigatorTitle":[{"text":"FileType","kind":"identifier"}],"abstract":[{"text":"Enum that represents the file types that zendesk supports","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","title":"FileType","url":"\/documentation\/supportsdk\/filetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FileType","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKFileTypeNumbers","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"ZDKFileTypeNumbers","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKFileTypeNumbers","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKFileTypeNumbers","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1numbers\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1numbers\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypeNumbers"}],"op":"replace"},{"value":"ZDKFileType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","op":"replace","value":[{"text":"ZDKFileType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}