{"abstract":[{"text":"Locale override for help center","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/helpCenterLocaleOverride"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/supportsdk\/supportui\/helpcenterlocaleoverride"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/supportui\/helpcenterlocaleoverride"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpCenterLocaleOverride"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@M@SupportSDK@objc(cs)ZDKSupportUI(py)helpCenterLocaleOverride","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpCenterLocaleOverride","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"SupportSDK"}],"title":"helpCenterLocaleOverride","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"helpCenterLocaleOverride"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI":{"deprecated":true,"role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/supportui","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportUI","kind":"identifier"}],"title":"SupportUI","navigatorTitle":[{"text":"SupportUI","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/helpCenterLocaleOverride":{"deprecated":true,"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpCenterLocaleOverride"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"title":"helpCenterLocaleOverride","navigatorTitle":[{"kind":"identifier","text":"helpCenterLocaleOverride"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/helpCenterLocaleOverride","type":"topic","abstract":[{"text":"Locale override for help center","type":"text"}],"url":"\/documentation\/supportsdk\/supportui\/helpcenterlocaleoverride"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"helpCenterLocaleOverride","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"helpCenterLocaleOverride"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"helpCenterLocaleOverride","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/title","op":"replace","value":"ZDKSupportUI"},{"value":[{"text":"ZDKSupportUI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/fragments","op":"replace"},{"value":"helpCenterLocaleOverride","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1helpCenterLocaleOverride\/title","op":"replace"},{"value":[{"text":"helpCenterLocaleOverride","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1helpCenterLocaleOverride\/fragments","op":"replace"}]}]}