{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/buildButton(withFrame:andTitle:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/supportsdk\/zdkuiutil\/buildbutton(withframe:andtitle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkuiutil\/buildbutton(withframe:andtitle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildButton"},{"kind":"text","text":"("},{"text":"withFrame","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andTitle"},{"kind":"text","text":" "},{"text":"title","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"text":"!","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"is the initial frame."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"is the title string.","type":"text"}]}],"name":"title"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"A new button.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Convenience method for creating UIButton."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildButton"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withFrame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andTitle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"text":"!","kind":"text"}],"roleHeading":"Type Method","title":"buildButton(withFrame:andTitle:)","symbolKind":"method","externalID":"c:objc(cs)ZDKUIUtil(cm)buildButtonWithFrame:andTitle:","modules":[{"name":"SupportSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buildButtonWithFrame:andTitle:"}]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"type":"topic","url":"\/documentation\/supportsdk\/zdkuiutil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIUtil"}],"title":"ZDKUIUtil","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKUIUtil"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/buildButton(withFrame:andTitle:)":{"url":"\/documentation\/supportsdk\/zdkuiutil\/buildbutton(withframe:andtitle:)","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/buildButton(withFrame:andTitle:)","title":"buildButton(withFrame:andTitle:)","type":"topic","kind":"symbol","abstract":[{"text":"Convenience method for creating UIButton.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildButton"},{"text":"(","kind":"text"},{"text":"withFrame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andTitle"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"buildButtonWithFrame:andTitle:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"buildButtonWithFrame:andTitle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"buildButtonWithFrame:andTitle:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"text":" *) ","kind":"text"},{"text":"buildButtonWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":" "},{"text":"andTitle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"title","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title","op":"replace","value":"ZDKUIUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments","value":[{"text":"ZDKUIUtil","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1buildButton(withFrame:andTitle:)\/title","value":"buildButtonWithFrame:andTitle:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1buildButton(withFrame:andTitle:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"buildButtonWithFrame:andTitle:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}