{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/dismissutil\/barbuttonfor(_:embededin:action:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/dismissutil\/barbuttonfor(_:embededin:action:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barButtonFor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"embededIn","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigationController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem","kind":"typeIdentifier"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"barButtonFor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"embededIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem"}],"role":"symbol","roleHeading":"Type Method","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"barButtonFor:embededIn:action:"}],"symbolKind":"method","externalID":"c:@M@SupportSDK@objc(cs)ZDKDismissUtil(cm)barButtonFor:embededIn:action:","title":"barButtonFor(_:embededIn:action:)"},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil\/barButtonFor(_:embededIn:action:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/DismissUtil/barButtonFor(_:embededIn:action:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil\/barButtonFor(_:embededIn:action:)","role":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/dismissutil\/barbuttonfor(_:embededin:action:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barButtonFor","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"embededIn"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier","text":"UINavigationController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier","text":"Selector"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","kind":"typeIdentifier","text":"UIBarButtonItem"}],"navigatorTitle":[{"kind":"identifier","text":"barButtonFor:embededIn:action:"}],"title":"barButtonFor(_:embededIn:action:)","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/DismissUtil":{"navigatorTitle":[{"text":"DismissUtil","kind":"identifier"}],"url":"\/documentation\/supportsdk\/dismissutil","title":"DismissUtil","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DismissUtil","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"barButtonFor:embededIn:action:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"barButtonFor:embededIn:action:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBarButtonItem","text":"UIBarButtonItem","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barButtonFor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"embededIn:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController","text":"UINavigationController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"navigationController"},{"kind":"text","text":" "},{"kind":"identifier","text":"action:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@SEL","text":"SEL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil~1barButtonFor(_:embededIn:action:)\/title","value":"barButtonFor:embededIn:action:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil~1barButtonFor(_:embededIn:action:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"barButtonFor:embededIn:action:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/title","value":"ZDKDismissUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/fragments","value":[{"text":"ZDKDismissUtil","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/navigatorTitle","value":[{"text":"ZDKDismissUtil","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}