{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button on the Help Center Article screen will route to the “UMI” screen,"},{"text":" ","type":"text"},{"text":"if an engine is added to this array. If the array is empty, we route to the ","type":"text"},{"type":"codeVoice","code":"Request List"},{"text":" screen if","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"Conversations"},{"type":"text","text":" are turned on, otherwise we will route to the "},{"type":"codeVoice","code":"Request Screen"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterUiConfiguration(py)objcEngines","navigatorTitle":[{"text":"objcEngines","kind":"identifier"}],"role":"symbol","platforms":[],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"objcEngines","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","text":"ZDKEngine"},{"kind":"text","text":"]"}],"symbolKind":"property","modules":[{"name":"SupportSDK"}],"title":"objcEngines"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"objcEngines","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","kind":"typeIdentifier","text":"ZDKEngine"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"content":[{"inlineContent":[{"text":"5.0.0","type":"text"}],"type":"paragraph"}],"name":"Version","type":"aside","style":"note"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/objcengines"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/objcengines"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/objcEngines"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/objcEngines":{"navigatorTitle":[{"text":"objcEngines","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/objcEngines","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"objcEngines"},{"kind":"text","text":": ["},{"text":"ZDKEngine","kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine"},{"kind":"text","text":"]"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button on the Help Center Article screen will route to the “UMI” screen,"},{"type":"text","text":" "},{"type":"text","text":"if an engine is added to this array. If the array is empty, we route to the "},{"code":"Request List","type":"codeVoice"},{"text":" screen if","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"Conversations"},{"type":"text","text":" are turned on, otherwise we will route to the "},{"type":"codeVoice","code":"Request Screen"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/objcengines","title":"objcEngines"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration":{"abstract":[{"text":"Data class used to configure Help Center","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterUiConfiguration"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration","title":"HelpCenterUiConfiguration","kind":"symbol","navigatorTitle":[{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"objcEngines"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"objcEngines","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<ZDKEngine>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"objcEngines"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1objcEngines\/title","value":"objcEngines"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1objcEngines\/fragments","value":[{"kind":"identifier","text":"objcEngines"}],"op":"replace"},{"value":"ZDKHelpCenterUiConfiguration","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/title"},{"op":"replace","value":[{"text":"ZDKHelpCenterUiConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}