{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"animated","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"viewDidAppear(_:)","symbolKind":"method","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKCoordinatingViewController(im)viewDidAppear:","roleHeading":"Instance Method","modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidAppear(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/coordinatingviewcontroller\/viewdidappear(_:)"]},{"paths":["\/documentation\/supportsdk\/coordinatingviewcontroller\/viewdidappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController":{"url":"\/documentation\/supportsdk\/coordinatingviewcontroller","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","title":"CoordinatingViewController","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinatingViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CoordinatingViewController"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController/viewDidAppear(_:)":{"abstract":[],"title":"viewDidAppear(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidAppear(_:)","type":"topic","url":"\/documentation\/supportsdk\/coordinatingviewcontroller\/viewdidappear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"viewDidAppear:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidAppear:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/title","op":"replace","value":"ZDKCoordinatingViewController"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKCoordinatingViewController"}]},{"value":"viewDidAppear:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidAppear(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}]}]}]}