{"metadata":{"title":"articleRatingVoteSelected(_:at:)","modules":[{"name":"SupportSDK"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"articleRatingVoteSelected:atIndex:"}],"externalID":"c:@M@SupportSDK@objc(cs)HelpCenterArticleVotingHandler(im)articleRatingVoteSelected:atIndex:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"articleRatingVoteSelected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol","text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/articleRatingVoteSelected(_:at:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"ZDKHelpCenterArticleRatingHandlerProtocol.articleRatingVoteSelected(_:at:)"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/articleratingvoteselected(_:at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/articleratingvoteselected(_:at:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleRatingVoteSelected"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"ratingState","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","text":"ZDKHelpCenterArticleRatingStateProtocol"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler","title":"HelpCenterArticleVotingHandler","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler/articleRatingVoteSelected(_:at:)":{"type":"topic","title":"articleRatingVoteSelected(_:at:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/articleRatingVoteSelected(_:at:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"articleRatingVoteSelected","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticleRatingStateProtocol","preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/articleratingvoteselected(_:at:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingStateProtocol":{"type":"topic","title":"ZDKHelpCenterArticleRatingStateProtocol","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"articleRatingVoteSelected:atIndex:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"articleRatingVoteSelected:atIndex:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"articleRatingVoteSelected:"},{"text":"(","kind":"text"},{"text":"id<ZDKHelpCenterArticleRatingStateProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)ZDKHelpCenterArticleRatingStateProtocol"},{"text":" *) ","kind":"text"},{"text":"ratingState","kind":"internalParam"},{"kind":"text","text":" "},{"text":"atIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"index","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"HelpCenterArticleVotingHandler","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/title","op":"replace"},{"op":"replace","value":[{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1articleRatingVoteSelected(_:at:)\/title","value":"articleRatingVoteSelected:atIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1articleRatingVoteSelected(_:at:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/title","op":"replace","value":"ZDKHelpCenterArticleRatingStateProtocol"},{"value":[{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/fragments"}]}]}