{"abstract":[{"type":"text","text":"Inherited from "},{"code":"ZDKHelpCenterArticleRatingHandlerProtocol.currentArticleVote()","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/currentArticleVote()"},"variants":[{"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/currentarticlevote()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/currentarticlevote()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"currentArticleVote","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Method","externalID":"c:@M@SupportSDK@objc(cs)HelpCenterArticleVotingHandler(im)currentArticleVote","symbolKind":"method","navigatorTitle":[{"text":"currentArticleVote","kind":"identifier"}],"title":"currentArticleVote()","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentArticleVote"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler","title":"HelpCenterArticleVotingHandler","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler/currentArticleVote()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"currentArticleVote","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/currentarticlevote()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"currentArticleVote"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/currentArticleVote()","title":"currentArticleVote()","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"currentArticleVote","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"currentArticleVote","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"currentArticleVote"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"HelpCenterArticleVotingHandler","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/title"},{"value":[{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1currentArticleVote()\/title","value":"currentArticleVote","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1currentArticleVote()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"currentArticleVote","kind":"identifier"}],"op":"replace"}]}]}