{"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(withArticleId:andLocale:)","navigatorTitle":[{"text":"initWithArticleId:andLocale:","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)HelpCenterArticleVotingHandler(im)initWithArticleId:andLocale:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"andLocale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"symbolKind":"init","modules":[{"name":"SupportSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/init(witharticleid:andlocale:)"]},{"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/init(witharticleid:andlocale:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"articleId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andLocale"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/init(withArticleId:andLocale:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler/init(withArticleId:andLocale:)":{"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/init(witharticleid:andlocale:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/init(withArticleId:andLocale:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLocale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithArticleId:andLocale:","kind":"identifier"}],"title":"init(withArticleId:andLocale:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler","title":"HelpCenterArticleVotingHandler","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithArticleId:andLocale:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithArticleId:andLocale:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithArticleId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"articleId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"andLocale:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"locale","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1init(withArticleId:andLocale:)\/title","value":"initWithArticleId:andLocale:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1init(withArticleId:andLocale:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithArticleId:andLocale:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/title","value":"HelpCenterArticleVotingHandler","op":"replace"},{"value":[{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/fragments","op":"replace"}]}]}