{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger"]]},"variants":[{"paths":["\/documentation\/supportsdk\/zdksuasdebuglogger\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"SupportSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKSuasDebugLogger(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSuasDebugLogger\/init"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"https://github.com/zendesk/Suas-iOS":{"url":"https:\/\/github.com\/zendesk\/Suas-iOS","type":"link","identifier":"https:\/\/github.com\/zendesk\/Suas-iOS","titleInlineContent":[{"text":"Suas","type":"text"}],"title":"Suas"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SuasDebugLogger","kind":"identifier"}],"url":"\/documentation\/supportsdk\/suasdebuglogger","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SuasDebugLogger","kind":"identifier"}],"title":"SuasDebugLogger","abstract":[{"text":"Used to enable ","type":"text"},{"identifier":"https:\/\/github.com\/zendesk\/Suas-iOS","isActive":true,"type":"reference"},{"text":" logging.","type":"text"},{"text":" ","type":"text"},{"text":"Suas drives most of the Ticketing UI so the Suas logs can be useful for debugging it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Enabling the Suas logger produces a lot of information and will slow down the SDK."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSuasDebugLogger/init":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSuasDebugLogger\/init","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdksuasdebuglogger\/init"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKSuasDebugLogger","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/title"},{"value":[{"text":"ZDKSuasDebugLogger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/fragments"},{"value":[{"text":"ZDKSuasDebugLogger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/navigatorTitle"}]}]}