{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/active()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/active()"]}],"abstract":[{"text":"Determines where the coversations nav bar button will be displayed.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens ","type":"text"}],"type":"paragraph"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"active"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@ZDKContactUsVisibility","text":"ZDKContactUsVisibility","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"a ZDKContactUsVisibility value."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/active()"},"metadata":{"modules":[{"name":"SupportSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKContactUsVisibility","text":"ZDKContactUsVisibility"}],"externalID":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate(im)active","navigatorTitle":[{"kind":"identifier","text":"active"}],"roleHeading":"Instance Method","symbolKind":"method","platforms":[],"required":true,"title":"active()"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/active()":{"abstract":[{"type":"text","text":"Determines where the coversations nav bar button will be displayed."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"active","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@ZDKContactUsVisibility","kind":"typeIdentifier","text":"ZDKContactUsVisibility"}],"navigatorTitle":[{"text":"active","kind":"identifier"}],"deprecated":true,"kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/active()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/active()","title":"active()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate":{"title":"ZDKHelpCenterConversationsUIDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","abstract":[],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility":{"url":"\/documentation\/supportsdk\/zdkcontactusvisibility","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","type":"topic","title":"ZDKContactUsVisibility","abstract":[{"text":"Used to select where conversations nav bar button will be active.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKContactUsVisibility"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"ZDKContactUsVisibility","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"active","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"active"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@E@ZDKContactUsVisibility","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","text":"ZDKContactUsVisibility","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"active","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1active()\/title","value":"active"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1active()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"active","kind":"identifier"}],"op":"replace"},{"value":"ZDKHelpCenterConversationsUIDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/title","op":"replace"},{"value":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/title","value":"ZDKContactUsVisibility","op":"replace"},{"value":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}