{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Fix the bottom guide layout position"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/bottom","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/bottom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/bottom"]}],"metadata":{"role":"symbol","roleHeading":"Case","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionBottom"}],"title":"ZDKLayoutGuideApplicatorPosition.bottom","externalID":"c:@E@ZDKLayoutGuideApplicatorPosition@ZDKLayoutGuideApplicatorPositionBottom","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"}]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/bottom":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/bottom","abstract":[{"type":"text","text":"Fix the bottom guide layout position"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/bottom","navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionBottom"}],"title":"ZDKLayoutGuideApplicatorPosition.bottom","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition":{"kind":"symbol","title":"ZDKLayoutGuideApplicatorPosition","type":"topic","role":"symbol","abstract":[{"text":"Layout guides positions to fix","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKLayoutGuideApplicatorPositionBottom"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionBottom"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKLayoutGuideApplicatorPositionBottom","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1bottom\/title","op":"replace","value":"ZDKLayoutGuideApplicatorPositionBottom"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1bottom\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionBottom"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/title","op":"replace","value":"ZDKLayoutGuideApplicatorPosition"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/fragments","op":"replace","value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/navigatorTitle","op":"replace","value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}