{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/init(rawValue:)"},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:So32ZDKLayoutGuideApplicatorPositionV8rawValueABSgSu_tcfc","role":"symbol","roleHeading":"Initializer","modules":[{"name":"SupportSDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","symbolKind":"init"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/init(rawValue:)":{"url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/init(rawvalue:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/init(rawValue:)","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(rawValue:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition":{"kind":"symbol","title":"ZDKLayoutGuideApplicatorPosition","type":"topic","role":"symbol","abstract":[{"text":"Layout guides positions to fix","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKLayoutGuideApplicatorPosition","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/title"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/fragments"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPosition"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/navigatorTitle"}]}]}