{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/ContainerChildControllerDelegate-Implementations"},"variants":[{"paths":["\/documentation\/supportsdk\/containerviewcontroller\/containerchildcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/containerviewcontroller\/containerchildcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"collectionGroup","title":"ContainerChildControllerDelegate Implementations","modules":[{"name":"SupportSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/navItem"],"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/willDismiss()"]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/navItem":{"role":"symbol","abstract":[],"kind":"symbol","title":"navItem","navigatorTitle":[{"kind":"identifier","text":"navItem"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/navItem","url":"\/documentation\/supportsdk\/containerviewcontroller\/navitem","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navItem"},{"kind":"text","text":": "},{"text":"UINavigationItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"text":"?","kind":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerViewController"}],"url":"\/documentation\/supportsdk\/containerviewcontroller","kind":"symbol","role":"symbol","title":"ContainerViewController","navigatorTitle":[{"kind":"identifier","text":"ContainerViewController"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/willDismiss()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/willDismiss()","url":"\/documentation\/supportsdk\/containerviewcontroller\/willdismiss()","type":"topic","kind":"symbol","role":"symbol","title":"willDismiss()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismiss"},{"text":"()","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"willDismiss","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/navItem"],"generated":true},{"generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/willDismiss()"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1navItem\/title","value":"navItem"},{"op":"replace","value":[{"kind":"identifier","text":"navItem"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1navItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/title","value":"ContainerViewController"},{"value":[{"kind":"identifier","text":"ContainerViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/fragments"},{"value":"willDismiss","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1willDismiss()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1willDismiss()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willDismiss","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}