{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/cellIdentifier()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Helper method to retrieve this classes cell identifier."}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cellIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"externalID":"c:objc(cs)ZDKSupportAttachmentCell(cm)cellIdentifier","symbolKind":"method","title":"cellIdentifier()","role":"symbol","navigatorTitle":[{"text":"cellIdentifier","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cellIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}]}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The classes cell identifier.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdksupportattachmentcell\/cellidentifier()"]},{"paths":["\/documentation\/supportsdk\/zdksupportattachmentcell\/cellidentifier()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell/cellIdentifier()":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cellIdentifier","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/cellIdentifier()","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"cellIdentifier","kind":"identifier"}],"abstract":[{"text":"Helper method to retrieve this classes cell identifier.","type":"text"}],"title":"cellIdentifier()","url":"\/documentation\/supportsdk\/zdksupportattachmentcell\/cellidentifier()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKSupportAttachmentCell","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKSupportAttachmentCell"}],"abstract":[],"title":"ZDKSupportAttachmentCell","url":"\/documentation\/supportsdk\/zdksupportattachmentcell"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"cellIdentifier"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cellIdentifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"cellIdentifier","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1cellIdentifier()\/title","value":"cellIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1cellIdentifier()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"cellIdentifier","kind":"identifier"}],"op":"replace"},{"value":"ZDKSupportAttachmentCell","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSupportAttachmentCell"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}