{"abstract":[{"text":"Initializes a data source with a cell identifier, configuration block and a provider.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"articleId"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The articleId passed as a String, the article to which attachments will be fetched.","type":"text"}]}],"name":"articleId"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new instance."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource\/init(articleid:)"]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource\/init(articleid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource"]]},"metadata":{"roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"articleId"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"!)","kind":"text"}],"title":"init(articleId:)","symbolKind":"init","navigatorTitle":[{"text":"initWithArticleId:","kind":"identifier"}],"externalID":"c:objc(cs)ZDKHelpCenterAttachmentsDataSource(im)initWithArticleId:","modules":[{"name":"SupportSDK"}]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource\/init(articleId:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterAttachmentsDataSource/init(articleId:)":{"url":"\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource\/init(articleid:)","type":"topic","title":"init(articleId:)","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource\/init(articleId:)","fragments":[{"text":"init","kind":"identifier"},{"text":"!(","kind":"text"},{"kind":"externalParam","text":"articleId"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Initializes a data source with a cell identifier, configuration block and a provider."}],"kind":"symbol","navigatorTitle":[{"text":"initWithArticleId:","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterAttachmentsDataSource":{"type":"topic","title":"ZDKHelpCenterAttachmentsDataSource","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource","navigatorTitle":[{"text":"ZDKHelpCenterAttachmentsDataSource","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource","abstract":[{"text":"Data source for Help Center attachments.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithArticleId:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithArticleId:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithArticleId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"articleId"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource~1init(articleId:)\/title","value":"initWithArticleId:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource~1init(articleId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithArticleId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/title","op":"replace","value":"ZDKHelpCenterAttachmentsDataSource"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}]}]}]}