{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/init(rawValue:)"},"metadata":{"title":"init(rawValue:)","externalID":"s:So28ZDKNavBarCreateRequestUITypeV8rawValueABSgSu_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","modules":[{"name":"SupportSDK"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/init(rawvalue:)"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType":{"role":"symbol","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","title":"ZDKNavBarCreateRequestUIType","abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display request creation."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/init(rawValue:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/init(rawvalue:)","abstract":[]}},"variantOverrides":[{"patch":[{"value":"ZDKNavBarCreateRequestUIType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/fragments","op":"replace"},{"value":[{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}