{"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListOnly","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility"]]},"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Case","platforms":[],"role":"symbol","title":"ZDKContactUsVisibility.articleListOnly","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"articleListOnly"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListOnly"}],"externalID":"c:@E@ZDKContactUsVisibility@ZDKContactUsVisibilityArticleListOnly"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistonly"]},{"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistonly"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"articleListOnly","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility":{"abstract":[{"type":"text","text":"Used to select where conversations nav bar button will be active."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKContactUsVisibility"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","deprecated":true,"role":"symbol","type":"topic","title":"ZDKContactUsVisibility","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKContactUsVisibility","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/articleListOnly":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListOnly","title":"ZDKContactUsVisibility.articleListOnly","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"articleListOnly","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKContactUsVisibilityArticleListOnly","kind":"identifier"}],"abstract":[],"deprecated":true,"kind":"symbol","url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistonly"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKContactUsVisibilityArticleListOnly"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListOnly"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListOnly"}]}]},"op":"replace"},{"value":"ZDKContactUsVisibility","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/fragments","value":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKContactUsVisibilityArticleListOnly","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListOnly\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListOnly\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListOnly"}]}]}]}