{"metadata":{"externalID":"c:@M@SupportSDK@objc(cs)ZDKSupportUI(im)refreshRequestWithRequestId:","symbolKind":"method","role":"symbol","title":"refreshRequest(requestId:)","modules":[{"name":"SupportSDK"}],"platforms":[],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"refreshRequestWithRequestId:","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"This method can be used to aid in handling push notifications relating to requests.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method can result in a dynamic update in the request UI. For this occur,"},{"type":"text","text":" "},{"type":"text","text":"the push notification and the on screen request must contain matching request ids."},{"type":"text","text":" "},{"text":"This method will return true only in the case of a successful UI update.","type":"text"},{"text":" ","type":"text"},{"text":"A return value of false means that the push notification was unhandled.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"At this point you can decided how best to update the user based on the contents of the notification."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The ID of the request to refresh","type":"text"}],"type":"paragraph"}],"name":"requestId"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A boolean indicating whether the Request Detail Screen has been refresh or not.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/supportui\/refreshrequest(requestid:)"]},{"paths":["\/documentation\/supportsdk\/supportui\/refreshrequest(requestid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/refreshRequest(requestId:)"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/refreshRequest(requestId:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/refreshRequest(requestId:)","deprecated":true,"url":"\/documentation\/supportsdk\/supportui\/refreshrequest(requestid:)","type":"topic","kind":"symbol","role":"symbol","title":"refreshRequest(requestId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshRequest"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"This method can be used to aid in handling push notifications relating to requests.","type":"text"},{"type":"text","text":" "},{"text":"This method can result in a dynamic update in the request UI. For this occur,","type":"text"},{"type":"text","text":" "},{"text":"the push notification and the on screen request must contain matching request ids.","type":"text"},{"text":" ","type":"text"},{"text":"This method will return true only in the case of a successful UI update.","type":"text"},{"text":" ","type":"text"},{"text":"A return value of false means that the push notification was unhandled.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"At this point you can decided how best to update the user based on the contents of the notification."}],"navigatorTitle":[{"text":"refreshRequestWithRequestId:","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","deprecated":true,"url":"\/documentation\/supportsdk\/supportui","type":"topic","kind":"symbol","role":"symbol","title":"SupportUI","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SupportUI","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SupportUI"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"refreshRequestWithRequestId:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"refreshRequestWithRequestId:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"refreshRequestWithRequestId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"requestId"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1refreshRequest(requestId:)\/title","value":"refreshRequestWithRequestId:"},{"value":[{"text":"- ","kind":"text"},{"text":"refreshRequestWithRequestId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1refreshRequest(requestId:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/title","op":"replace","value":"ZDKSupportUI"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/fragments","op":"replace","value":[{"text":"ZDKSupportUI","kind":"identifier"}]}]}]}