{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appearanceValue"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewClass","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"selector"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The appearance value will come from this class."}]}],"name":"viewClass"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The appearance selector"}]}],"name":"selector"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"An appearance value or nil if none have been set.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-1dn96","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"appearanceValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"selector"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier","text":"Selector"},{"text":"!) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"appearanceValueForClass:selector:","kind":"identifier"}],"title":"appearanceValue(for:selector:)","externalID":"c:objc(cs)ZDKUIUtil(cm)appearanceValueForClass:selector:","modules":[{"name":"SupportSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]]},"sections":[],"abstract":[{"text":"Gets the UI_APPEARANCE_SELECTOR value for a class.","type":"text"}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-1dn96"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-1dn96"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIUtil","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKUIUtil"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil","type":"topic","role":"symbol","url":"\/documentation\/supportsdk\/zdkuiutil","kind":"symbol","abstract":[],"title":"ZDKUIUtil"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/appearanceValue(for:selector:)-1dn96":{"navigatorTitle":[{"text":"appearanceValueForClass:selector:","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkuiutil\/appearancevalue(for:selector:)-1dn96","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appearanceValue"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"selector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"text":"!) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"!"}],"type":"topic","title":"appearanceValue(for:selector:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/appearanceValue(for:selector:)-1dn96","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Gets the UI_APPEARANCE_SELECTOR value for a class."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"appearanceValueForClass:selector:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"appearanceValueForClass:selector:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"appearanceValueForClass:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@Class","text":"Class","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"viewClass"},{"kind":"text","text":" "},{"text":"selector:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SEL","preciseIdentifier":"c:e"},{"text":" *) ","kind":"text"},{"text":"selector","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKUIUtil","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments","value":[{"kind":"identifier","text":"ZDKUIUtil"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-1dn96\/title","op":"replace","value":"appearanceValueForClass:selector:"},{"value":[{"text":"+ ","kind":"text"},{"text":"appearanceValueForClass:selector:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1appearanceValue(for:selector:)-1dn96\/fragments"}]}]}