{"metadata":{"navigatorTitle":[{"text":"CoordinatingViewController","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"SupportSDK"}],"role":"symbol","roleHeading":"Class","title":"CoordinatingViewController","externalID":"c:@M@SupportSDK@objc(cs)ZDKCoordinatingViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinatingViewController"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKCoordinatingViewController) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinatingViewController"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/init(coordinator:)"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidAppear(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidDisappear(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidLoad()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewWillAppear(_:)"],"title":"Instance Methods"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/coordinatingviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/coordinatingviewcontroller"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/s8SendableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIContentContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIStateRestoring","doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"]}],"references":{"doc://com.zendesk.SupportSDK/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","title":"CoordinatingViewController","kind":"symbol","url":"\/documentation\/supportsdk\/coordinatingviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoordinatingViewController"}],"abstract":[],"navigatorTitle":[{"text":"CoordinatingViewController","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController/viewWillAppear(_:)":{"abstract":[],"type":"topic","title":"viewWillAppear(_:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewWillAppear(_:)","url":"\/documentation\/supportsdk\/coordinatingviewcontroller\/viewwillappear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController/viewDidAppear(_:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidAppear(_:)","title":"viewDidAppear(_:)","kind":"symbol","url":"\/documentation\/supportsdk\/coordinatingviewcontroller\/viewdidappear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}]},"doc://com.zendesk.SupportSDK/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"abstract":[],"type":"topic","title":"ContainerChildControllerDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"ContainerChildControllerDelegate"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer"},"doc://com.zendesk.SupportSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController/viewDidDisappear(_:)":{"abstract":[],"title":"viewDidDisappear(_:)","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidDisappear(_:)","url":"\/documentation\/supportsdk\/coordinatingviewcontroller\/viewdiddisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.zendesk.SupportSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.zendesk.SupportSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIContentContainer"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController/viewDidLoad()":{"abstract":[],"title":"viewDidLoad()","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidLoad()","url":"\/documentation\/supportsdk\/coordinatingviewcontroller\/viewdidload()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}]},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.zendesk.SupportSDK/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.zendesk.SupportSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController/init(coordinator:)":{"abstract":[],"type":"topic","title":"init(coordinator:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/init(coordinator:)","url":"\/documentation\/supportsdk\/coordinatingviewcontroller\/init(coordinator:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoordinator:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"coordinator","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Coordinator","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKCoordinator"},{"text":")","kind":"text"}]},"doc://com.zendesk.SupportSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController":{"url":"\/documentation\/supportsdk\/containerviewcontroller","navigatorTitle":[{"text":"ContainerViewController","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","title":"ContainerViewController","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContainerViewController","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKCoordinatingViewController"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKCoordinatingViewController"}]},{"value":[{"text":"ZDKCoordinatingViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/init(coordinator:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidAppear(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidDisappear(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewDidLoad()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController\/viewWillAppear(_:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController"],"type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKCoordinatingViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ContainerViewController","text":"ContainerViewController","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/title","op":"replace","value":"ZDKCoordinatingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/fragments","value":[{"text":"ZDKCoordinatingViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidAppear(_:)\/fragments"},{"value":"ZDKContainerChildControllerDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"value":"initWithCoordinator:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1init(coordinator:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoordinator:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController~1init(coordinator:)\/fragments"},{"value":"ContainerViewController","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/fragments","value":[{"text":"ContainerViewController","kind":"identifier"}],"op":"replace"}]}]}