{"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKRequestListUiConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestListUIConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration"},"variants":[{"paths":["\/documentation\/supportsdk\/requestlistuiconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/requestlistuiconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/init()"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/allowRequestCreation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/isEqual(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestListUIConfiguration"}],"role":"symbol","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestListUiConfiguration","title":"RequestListUIConfiguration","symbolKind":"class","navigatorTitle":[{"text":"RequestListUIConfiguration","kind":"identifier"}]},"sections":[],"references":{"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestListUIConfiguration/init()":{"url":"\/documentation\/supportsdk\/requestlistuiconfiguration\/init()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","role":"symbol","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[]},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportSDK/@M@SDKConfigurations@objc(pl)ZDKConfiguration":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","type":"unresolvable","title":"ZDKConfiguration"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestListUIConfiguration/allowRequestCreation":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/allowRequestCreation","url":"\/documentation\/supportsdk\/requestlistuiconfiguration\/allowrequestcreation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowRequestCreation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"allowRequestCreation","navigatorTitle":[{"text":"allowRequestCreation","kind":"identifier"}],"abstract":[{"type":"text","text":"Show a "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button in the request list view, and in the empty state for the list."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestListUIConfiguration":{"url":"\/documentation\/supportsdk\/requestlistuiconfiguration","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestListUIConfiguration"}],"type":"topic","kind":"symbol","role":"symbol","title":"RequestListUIConfiguration","navigatorTitle":[{"text":"RequestListUIConfiguration","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestListUIConfiguration/isEqual(_:)":{"url":"\/documentation\/supportsdk\/requestlistuiconfiguration\/isequal(_:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","role":"symbol","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKRequestListUiConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKRequestListUiConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKRequestListUiConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/allowRequestCreation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/init()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestListUIConfiguration\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKRequestListUiConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"init","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1init()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"value":"allowRequestCreation","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1allowRequestCreation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1allowRequestCreation\/fragments","value":[{"text":"allowRequestCreation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration\/title","value":"ZDKRequestListUiConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKRequestListUiConfiguration"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestListUIConfiguration~1isEqual(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}