{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterDelegate"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}],"type":"paragraph"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate\/uiDelegate"]}],"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","title":"ZDKHelpCenterDelegate","platforms":[],"externalID":"c:objc(pl)ZDKHelpCenterDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"modules":[{"name":"SupportSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate"},"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterdelegate"]}],"references":{"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate/uiDelegate":{"type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate\/uidelegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate","text":"ZDKHelpCenterConversationsUIDelegate","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"uiDelegate","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"uiDelegate"}],"abstract":[],"kind":"symbol","required":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate\/uiDelegate"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"title":"ZDKHelpCenterDelegate","role":"symbol","deprecated":true,"navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"ZDKHelpCenterDelegate","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate\/uiDelegate"],"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate~1uiDelegate\/title","value":"uiDelegate"},{"value":[{"text":"uiDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate~1uiDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title","value":"ZDKHelpCenterDelegate","op":"replace"},{"value":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments","op":"replace"}]}]}