{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"abstract":[{"type":"text","text":"A block for configuring cells. This is invoked in cell for row at index path."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentercellconfigureblock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentercellconfigureblock"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterCellConfigureBlock"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterCellConfigureBlock"},{"kind":"text","text":" = ("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"languages":["swift"]}]}],"metadata":{"title":"ZDKHelpCenterCellConfigureBlock","modules":[{"name":"SupportSDK"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterCellConfigureBlock"}],"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterCellConfigureBlock","kind":"identifier"}],"roleHeading":"Type Alias","symbolKind":"typealias","externalID":"c:ZDKHelpCenterDataSource.h@T@ZDKHelpCenterCellConfigureBlock"},"sections":[],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterCellConfigureBlock":{"navigatorTitle":[{"text":"ZDKHelpCenterCellConfigureBlock","kind":"identifier"}],"title":"ZDKHelpCenterCellConfigureBlock","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentercellconfigureblock","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterCellConfigureBlock","abstract":[{"text":"A block for configuring cells. This is invoked in cell for row at index path.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterCellConfigureBlock","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"value":"ZDKHelpCenterCellConfigureBlock","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKHelpCenterCellConfigureBlock","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterCellConfigureBlock"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Qo#S2_)","kind":"typeIdentifier","text":"void (^)(id, id)"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterCellConfigureBlock","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterCellConfigureBlock\/title","value":"ZDKHelpCenterCellConfigureBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterCellConfigureBlock\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterCellConfigureBlock"}]}]}]}