{"abstract":[{"text":"The support view that displays help center content.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/hasItems","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/items","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/provider"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/item(at:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/reloadData()"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/cellIdentifierForDataSource()"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterdatasource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterdatasource"]}],"metadata":{"modules":[{"name":"SupportSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"symbolKind":"class","title":"ZDKHelpCenterDataSource","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"roleHeading":"Class","externalID":"c:objc(cs)ZDKHelpCenterDataSource"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterDataSource"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITableViewDataSource"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource/reloadData()":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/reloadData()","title":"reloadData()","navigatorTitle":[{"kind":"identifier","text":"reloadData"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource\/reloaddata()","abstract":[{"text":"Reloads the data source.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadData"},{"text":"()","kind":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterAttachmentsDataSource":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource","title":"ZDKHelpCenterAttachmentsDataSource","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterattachmentsdatasource","abstract":[{"text":"Data source for Help Center attachments.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterAttachmentsDataSource","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/objc(pl)UITableViewDataSource":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITableViewDataSource","title":"UITableViewDataSource","type":"unresolvable"},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource/item(at:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/item(at:)","title":"item(at:)","navigatorTitle":[{"text":"itemAtIndexPath:","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource\/item(at:)","abstract":[{"text":"Retrieves an item for the given index path.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"item","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"!) -> "},{"text":"Any","kind":"keyword"},{"text":"!","kind":"text"}]},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource/items":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/items","title":"items","navigatorTitle":[{"text":"items","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource\/items","abstract":[{"text":"Read-only array of items associated with the data source.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"items","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource","title":"ZDKHelpCenterDataSource","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource","abstract":[{"text":"The support view that displays help center content.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterDataSource","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource/cellIdentifierForDataSource()":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/cellIdentifierForDataSource()","title":"cellIdentifierForDataSource()","navigatorTitle":[{"kind":"identifier","text":"cellIdentifierForDataSource"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource\/cellidentifierfordatasource()","abstract":[{"text":"Returns cell identifier for the data source. Default ZDKHelpCenterTableViewCell. Override if using a different cell type.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cellIdentifierForDataSource","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}]},"doc://com.zendesk.SupportSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource/hasItems":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/hasItems","title":"hasItems","navigatorTitle":[{"kind":"identifier","text":"hasItems"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource\/hasitems","abstract":[{"type":"text","text":"Read only property, indicating if the DataSource has any items"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasItems","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDataSource/provider":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/provider","title":"provider","navigatorTitle":[{"kind":"identifier","text":"provider"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdatasource\/provider","abstract":[{"text":"Help Center provider.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"provider","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterProvider","preciseIdentifier":"c:objc(cs)ZDKHelpCenterProvider"},{"kind":"text","text":"!"}]},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ZDKHelpCenterDataSource","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}]},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterDataSource"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/hasItems","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/items","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/provider"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/item(at:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/reloadData()"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDataSource\/cellIdentifierForDataSource()"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterAttachmentsDataSource"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITableViewDataSource"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDataSource","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1reloadData()\/title","value":"reloadData"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1reloadData()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reloadData"}]},{"value":"ZDKHelpCenterAttachmentsDataSource","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/title"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterAttachmentsDataSource"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterAttachmentsDataSource\/fragments"},{"value":"itemAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1item(at:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1item(at:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"itemAtIndexPath:"}]},{"value":"items","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1items\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1items\/fragments","value":[{"text":"items","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/title","value":"ZDKHelpCenterDataSource","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource\/fragments","value":[{"text":"ZDKHelpCenterDataSource","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1cellIdentifierForDataSource()\/title","value":"cellIdentifierForDataSource"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1cellIdentifierForDataSource()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"cellIdentifierForDataSource","kind":"identifier"}],"op":"replace"},{"value":"hasItems","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1hasItems\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hasItems"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1hasItems\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1provider\/title","op":"replace","value":"provider"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDataSource~1provider\/fragments","op":"replace","value":[{"text":"provider","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}