{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/addObserver(_:identifier:eagerObserver:onRemove:_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","extendedModule":"MessagingAPI","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"text":", ","kind":"text"},{"text":"eagerObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Observable","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI10ObservablePABQa"},{"text":"?, ","kind":"text"},{"text":"onRemove","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, (","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Observable","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI10ObservablePABQa"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken"}],"externalID":"s:12MessagingAPI10ObservablePAAE11addObserver_10identifier05eagerE08onRemove_AA16ObservationTokenCqd___AA0C10IdentifierOABQzSgyAKcSgyqd__Sg_AkLtctRld__ClF::SYNTHESIZED::c:@M@SupportSDK@objc(cs)ZDKSupportEngine","symbolKind":"method","title":"addObserver(_:identifier:eagerObserver:onRemove:_:)","modules":[{"relatedModules":["MessagingAPI"],"name":"SupportSDK"}],"roleHeading":"Instance Method"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Observable.addObserver(_:identifier:eagerObserver:onRemove:_:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/supportsdk\/supportengine\/addobserver(_:identifier:eagerobserver:onremove:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":" = .uuid(), ","kind":"text"},{"text":"eagerObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","text":"Observable","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"onRemove","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"closure","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","text":"Observable","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken","text":"ObservationToken","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":" : AnyObject","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SupportEngine"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","kind":"symbol","title":"SupportEngine","url":"\/documentation\/supportsdk\/supportengine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportEngine"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/addObserver(_:identifier:eagerObserver:onRemove:_:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/addObserver(_:identifier:eagerObserver:onRemove:_:)","kind":"symbol","role":"symbol","title":"addObserver(_:identifier:eagerObserver:onRemove:_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"text":"<","kind":"text"},{"text":"T","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"T","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO"},{"text":", ","kind":"text"},{"text":"eagerObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","text":"Observable"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onRemove"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?, ("},{"kind":"typeIdentifier","text":"T"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI20ObservableIdentifierO","text":"ObservableIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","text":"Observable"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken","text":"ObservationToken"}],"url":"\/documentation\/supportsdk\/supportengine\/addobserver(_:identifier:eagerobserver:onremove:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/title","op":"replace","value":"ZDKSupportEngine"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKSupportEngine"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/navigatorTitle","op":"replace","value":[{"text":"ZDKSupportEngine","kind":"identifier"}]}]}]}