{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/supportengine\/observeupdates(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeUpdates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"callback","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Update","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6UpdateO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> MessagingAPI"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/observeUpdates(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine"]]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Engine.observeUpdates(_:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"SupportSDK"}],"symbolKind":"method","externalID":"s:10SupportSDK0A6EngineC14observeUpdatesy12MessagingAPI16ObservationTokenCyAE6UpdateOcF","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeUpdates","kind":"identifier"},{"text":"((","kind":"text"},{"text":"Update","preciseIdentifier":"s:12MessagingAPI6UpdateO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> MessagingAPI","kind":"text"},{"text":".","kind":"text"},{"text":"ObservationToken","preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken","kind":"typeIdentifier"}],"title":"observeUpdates(_:)","extendedModule":"SupportSDK"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SupportEngine"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","kind":"symbol","title":"SupportEngine","url":"\/documentation\/supportsdk\/supportengine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportEngine"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/observeUpdates(_:)":{"url":"\/documentation\/supportsdk\/supportengine\/observeupdates(_:)","kind":"symbol","title":"observeUpdates(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeUpdates"},{"kind":"text","text":"(("},{"preciseIdentifier":"s:12MessagingAPI6UpdateO","kind":"typeIdentifier","text":"Update"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> MessagingAPI"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@M@MessagingAPI@objc(cs)ZDKObservationToken","kind":"typeIdentifier","text":"ObservationToken"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/observeUpdates(_:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ZDKSupportEngine","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/title"},{"op":"replace","value":[{"text":"ZDKSupportEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSupportEngine"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}