{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topLevelView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"text":"layoutPosition","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition","kind":"typeIdentifier","text":"ZDKLayoutGuideApplicatorPosition"},{"text":")","kind":"text"}],"platforms":[],"roleHeading":"Initializer","externalID":"c:objc(cs)ZDKLayoutGuideApplicator(im)initWithViewController:topLevelView:layoutPosition:::SYNTHESIZED::c:objc(cs)ZDKLayoutGuideApplicator","title":"init(viewController:topLevelView:layoutPosition:)","modules":[{"name":"SupportSDK"}],"symbolKind":"init","role":"symbol"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"ZDKLayoutGuideApplicator.init(viewController:topLevelView:layoutPosition:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"topLevelView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layoutPosition"},{"kind":"text","text":" "},{"text":"position","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition","text":"ZDKLayoutGuideApplicatorPosition","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicator\/init(viewcontroller:toplevelview:layoutposition:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator\/init(viewController:topLevelView:layoutPosition:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicator/init(viewController:topLevelView:layoutPosition:)":{"title":"init(viewController:topLevelView:layoutPosition:)","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator\/init(viewController:topLevelView:layoutPosition:)","kind":"symbol","url":"\/documentation\/supportsdk\/zdklayoutguideapplicator\/init(viewcontroller:toplevelview:layoutposition:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"viewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topLevelView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"text":"layoutPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKLayoutGuideApplicatorPosition","preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition"},{"kind":"text","text":")"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","navigatorTitle":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Layout guides positions to fix"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition","title":"ZDKLayoutGuideApplicatorPosition","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicator":{"title":"ZDKLayoutGuideApplicator","role":"symbol","abstract":[{"type":"text","text":"This class tries to fix the layout spacing when using XIB instead of storyboard."},{"type":"text","text":" "},{"text":"Since we cannot reference the top\/bottom layout guids. This class fixes the top\/bottom layout to be relative to the guides.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"type":"topic","url":"\/documentation\/supportsdk\/zdklayoutguideapplicator","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/title","value":"ZDKLayoutGuideApplicatorPosition","op":"replace"},{"op":"replace","value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/title","value":"ZDKLayoutGuideApplicator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/fragments","value":[{"text":"ZDKLayoutGuideApplicator","kind":"identifier"}]}]}]}