{"metadata":{"externalID":"c:@M@SupportSDK@objc(cs)ZDKArticleUiConfiguration(py)objcEngines","title":"objcEngines","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"objcEngines"}],"roleHeading":"Instance Property","platforms":[],"modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"objcEngines","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","text":"ZDKEngine","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/objcEngines"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"objcEngines"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","kind":"typeIdentifier","text":"ZDKEngine"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"name":"Version","content":[{"inlineContent":[{"type":"text","text":"5.0.0"}],"type":"paragraph"}],"type":"aside","style":"note"}],"kind":"content"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/articleuiconfiguration\/objcengines"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/articleuiconfiguration\/objcengines"]}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Contact Support"},{"text":" button on the Help Center Article screen will route to the “UMI” screen,","type":"text"},{"type":"text","text":" "},{"text":"if an engine is added to this array. If the array is empty, we route to the ","type":"text"},{"type":"codeVoice","code":"Request List"},{"type":"text","text":" screen if"},{"type":"text","text":" "},{"code":"Conversations","type":"codeVoice"},{"type":"text","text":" are turned on, otherwise we will route to the "},{"code":"Request Screen","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration":{"navigatorTitle":[{"text":"ArticleUiConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Data class used to configure Article Screen"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration","type":"topic","title":"ArticleUiConfiguration","url":"\/documentation\/supportsdk\/articleuiconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ArticleUiConfiguration","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/objcEngines":{"type":"topic","title":"objcEngines","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/objcEngines","navigatorTitle":[{"text":"objcEngines","kind":"identifier"}],"url":"\/documentation\/supportsdk\/articleuiconfiguration\/objcengines","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"objcEngines","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","text":"ZDKEngine","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button on the Help Center Article screen will route to the “UMI” screen,"},{"text":" ","type":"text"},{"type":"text","text":"if an engine is added to this array. If the array is empty, we route to the "},{"type":"codeVoice","code":"Request List"},{"text":" screen if","type":"text"},{"text":" ","type":"text"},{"code":"Conversations","type":"codeVoice"},{"type":"text","text":" are turned on, otherwise we will route to the "},{"code":"Request Screen","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"objcEngines"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"objcEngines"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<ZDKEngine>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"objcEngines","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/title","op":"replace","value":"ZDKArticleUiConfiguration"},{"value":[{"kind":"identifier","text":"ZDKArticleUiConfiguration"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1objcEngines\/title","value":"objcEngines"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1objcEngines\/fragments","value":[{"kind":"identifier","text":"objcEngines"}],"op":"replace"}]}]}