{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/fileType","interfaceLanguage":"swift"},"abstract":[{"text":"Type of the file to be uploaded","type":"text"}],"sections":[],"metadata":{"title":"fileType","navigatorTitle":[{"kind":"identifier","text":"fileType"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestAttachment(py)fileType","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType","text":"FileType","kind":"typeIdentifier"}],"modules":[{"name":"SupportSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType","text":"FileType","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","kind":"typeIdentifier"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Version","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"2.0.0"}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestattachment\/filetype"]},{"paths":["\/documentation\/supportsdk\/requestattachment\/filetype"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestAttachment"}],"abstract":[{"text":"Creates an attachment to be uploaded when a request is created","type":"text"}],"navigatorTitle":[{"text":"RequestAttachment","kind":"identifier"}],"title":"RequestAttachment","kind":"symbol","url":"\/documentation\/supportsdk\/requestattachment","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","title":"FileType","navigatorTitle":[{"text":"FileType","kind":"identifier"}],"url":"\/documentation\/supportsdk\/filetype","type":"topic","kind":"symbol","abstract":[{"text":"Enum that represents the file types that zendesk supports","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileType"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment/fileType":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"fileType","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/fileType","type":"topic","title":"fileType","url":"\/documentation\/supportsdk\/requestattachment\/filetype","abstract":[{"type":"text","text":"Type of the file to be uploaded"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileType"},{"text":": ","kind":"text"},{"text":"FileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"fileType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fileType","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ZDKFileType","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType"},{"kind":"text","text":" "},{"text":"fileType","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/title","value":"ZDKRequestAttachment"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/fragments","op":"replace","value":[{"text":"ZDKRequestAttachment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","op":"replace","value":"ZDKFileType"},{"value":[{"kind":"identifier","text":"ZDKFileType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1fileType\/title","value":"fileType"},{"value":[{"text":"fileType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1fileType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}