{"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/requestattachment\/init(filename:data:filetype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/requestattachment\/init(filename:data:filetype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"filename","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"fileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileType","preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType"},{"kind":"text","text":")"}],"title":"init(filename:data:fileType:)","navigatorTitle":[{"text":"initWithFilename:data:fileType:","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestAttachment(im)initWithFilename:data:fileType:","symbolKind":"init","role":"symbol","modules":[{"name":"SupportSDK"}]},"abstract":[{"type":"text","text":"Generates a new state from the old state and an action"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"filename"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"fileType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FileType","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the name of the file to be uploaded, without the file extension"}]}],"name":"filename"},{"name":"data","content":[{"inlineContent":[{"type":"text","text":"the data of the contents of the file to be uploaded"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"the type of the file to be uploaded","type":"text"}]}],"name":"fileType"}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"an instance of RequestAttachment"}],"type":"paragraph"}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"name":"Version"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/init(filename:data:fileType:)"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/requestattachment","title":"RequestAttachment","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RequestAttachment","kind":"identifier"}],"abstract":[{"text":"Creates an attachment to be uploaded when a request is created","type":"text"}],"navigatorTitle":[{"text":"RequestAttachment","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestAttachment/init(filename:data:fileType:)":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/requestattachment\/init(filename:data:filetype:)","title":"init(filename:data:fileType:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"filename"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"fileType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FileType","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType"},{"kind":"text","text":")"}],"abstract":[{"text":"Generates a new state from the old state and an action","type":"text"}],"navigatorTitle":[{"text":"initWithFilename:data:fileType:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestAttachment\/init(filename:data:fileType:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","type":"topic","url":"\/documentation\/supportsdk\/filetype","abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"navigatorTitle":[{"kind":"identifier","text":"FileType"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileType"}],"title":"FileType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithFilename:data:fileType:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFilename:data:fileType:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithFilename:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"filename","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"data:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"kind":"text","text":" "},{"text":"fileType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","preciseIdentifier":"c:@M@SupportSDK@E@ZDKFileType","text":"ZDKFileType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"fileType","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/title","op":"replace","value":"ZDKRequestAttachment"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment\/fragments","value":[{"kind":"identifier","text":"ZDKRequestAttachment"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1init(filename:data:fileType:)\/title","value":"initWithFilename:data:fileType:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFilename:data:fileType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestAttachment~1init(filename:data:fileType:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","value":"ZDKFileType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","value":[{"text":"ZDKFileType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}