{"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator\/start(present:with:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"present"},{"kind":"text","text":": ("},{"text":"ContainerChildController","kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContainerChildControllerDelegate","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@SupportSDK@objc(cs)RequestCoordinator(im)startWithPresent:with:","title":"start(present:with:)","symbolKind":"method","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"startWithPresent:with:","kind":"identifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Coordinator.start(present:with:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"text":"present","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","text":"ContainerChildController","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"containerDelegate","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","text":"ContainerChildControllerDelegate"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestcoordinator\/start(present:with:)"]},{"paths":["\/documentation\/supportsdk\/requestcoordinator\/start(present:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestCoordinator":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/requestcoordinator","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestCoordinator"}],"navigatorTitle":[{"text":"RequestCoordinator","kind":"identifier"}],"title":"RequestCoordinator"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildController":{"title":"ContainerChildController","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ContainerChildController","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController","abstract":[],"role":"symbol","url":"\/documentation\/supportsdk\/containerchildcontroller","type":"topic","navigatorTitle":[{"text":"ContainerChildController","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","type":"topic","title":"ContainerChildControllerDelegate","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContainerChildControllerDelegate"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestCoordinator/start(present:with:)":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startWithPresent:with:"}],"url":"\/documentation\/supportsdk\/requestcoordinator\/start(present:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"present","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ContainerChildController","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier","text":"ContainerChildControllerDelegate"},{"kind":"text","text":")"}],"title":"start(present:with:)","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator\/start(present:with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"startWithPresent:with:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"startWithPresent:with:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWithPresent:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(UIViewController<ZDKContainerChild> *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)UIViewController@M@SupportSDK@objc(pl)ZDKContainerChild)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"present"},{"kind":"text","text":" "},{"text":"with:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<ZDKContainerChildControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":" *) ","kind":"text"},{"text":"containerDelegate","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/title","value":"RequestCoordinator"},{"op":"replace","value":[{"text":"RequestCoordinator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/fragments"},{"value":"ZDKContainerChildControllerDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"}]},{"value":"startWithPresent:with:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator~1start(present:with:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"startWithPresent:with:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator~1start(present:with:)\/fragments"}]}]}