{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/keynote"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype\/keynote"]},{"paths":["\/documentation\/supportsdk\/filetype\/keynote"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"keynote","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeKeynote"}],"modules":[{"name":"SupportSDK"}],"title":"FileType.keynote","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keynote"}],"externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypeKeynote","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/keynote":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeKeynote"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/keynote","url":"\/documentation\/supportsdk\/filetype\/keynote","title":"FileType.keynote","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keynote","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"title":"FileType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FileType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","url":"\/documentation\/supportsdk\/filetype"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKFileTypeKeynote","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKFileTypeKeynote","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKFileTypeKeynote"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1keynote\/title","value":"ZDKFileTypeKeynote","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1keynote\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypeKeynote"}],"op":"replace"},{"value":"ZDKFileType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFileType"}]}]}]}