{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"png"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype\/png"]},{"paths":["\/documentation\/supportsdk\/filetype\/png"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/png","interfaceLanguage":"swift"},"metadata":{"title":"FileType.png","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"png","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePng"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypePng","modules":[{"name":"SupportSDK"}]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"title":"FileType","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FileType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","url":"\/documentation\/supportsdk\/filetype"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/png":{"url":"\/documentation\/supportsdk\/filetype\/png","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePng"}],"title":"FileType.png","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"png","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/png","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"ZDKFileTypePng","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ZDKFileTypePng","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKFileTypePng","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","value":"ZDKFileType"},{"value":[{"kind":"identifier","text":"ZDKFileType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments"},{"value":"ZDKFileTypePng","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1png\/title"},{"value":[{"text":"ZDKFileTypePng","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1png\/fragments"}]}]}