{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError"]]},"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/invalidcategoryids"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/invalidcategoryids"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidCategoryIds"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCategoryIds"}],"role":"symbol","title":"ZDKHelpCenterError.invalidCategoryIds","roleHeading":"Case","navigatorTitle":[{"text":"ZDKHelpCenterErrorInvalidCategoryIds","kind":"identifier"}],"symbolKind":"case","externalID":"c:@E@ZDKHelpCenterError@ZDKHelpCenterErrorInvalidCategoryIds","modules":[{"name":"SupportSDK"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Category ids were not found in Help Center."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidCategoryIds","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError":{"abstract":[{"text":"Help Center error codes.","type":"text"}],"kind":"symbol","type":"topic","title":"ZDKHelpCenterError","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentererror","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterError"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterError"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/invalidCategoryIds":{"abstract":[{"text":"Category ids were not found in Help Center.","type":"text"}],"kind":"symbol","type":"topic","title":"ZDKHelpCenterError.invalidCategoryIds","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidCategoryIds","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/invalidcategoryids","navigatorTitle":[{"text":"ZDKHelpCenterErrorInvalidCategoryIds","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidCategoryIds"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"ZDKHelpCenterErrorInvalidCategoryIds","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterErrorInvalidCategoryIds"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKHelpCenterErrorInvalidCategoryIds","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/title","value":"ZDKHelpCenterError"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterError"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/fragments"},{"op":"replace","value":"ZDKHelpCenterErrorInvalidCategoryIds","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidCategoryIds\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidCategoryIds\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterErrorInvalidCategoryIds","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}