{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"heic"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"variants":[{"paths":["\/documentation\/supportsdk\/filetype\/heic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/filetype\/heic"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/heic","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"heic","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKFileTypeHeic","kind":"identifier"}],"title":"FileType.heic","symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypeHeic"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"navigatorTitle":[{"kind":"identifier","text":"FileType"}],"title":"FileType","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","url":"\/documentation\/supportsdk\/filetype","type":"topic","role":"symbol","abstract":[{"text":"Enum that represents the file types that zendesk supports","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileType"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/heic":{"type":"topic","kind":"symbol","title":"FileType.heic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"heic"}],"url":"\/documentation\/supportsdk\/filetype\/heic","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/heic","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeHeic"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKFileTypeHeic","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKFileTypeHeic","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKFileTypeHeic"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKFileType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","op":"replace"},{"value":[{"text":"ZDKFileType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKFileType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/navigatorTitle","op":"replace"},{"value":"ZDKFileTypeHeic","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1heic\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKFileTypeHeic"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1heic\/fragments","op":"replace"}]}]}