{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"navBarCreateRequestUIType","kind":"identifier"}],"externalID":"c:objc(pl)ZDKCreateRequestUIDelegate(im)navBarCreateRequestUIType","roleHeading":"Instance Method","modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navBarCreateRequestUIType"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNavBarCreateRequestUIType","text":"ZDKNavBarCreateRequestUIType"}],"title":"navBarCreateRequestUIType()","required":true,"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"To conform implementations should return the request creation UI type desired."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/navBarCreateRequestUIType()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/navbarcreaterequestuitype()"]},{"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/navbarcreaterequestuitype()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navBarCreateRequestUIType"},{"kind":"text","text":"() -> "},{"text":"ZDKNavBarCreateRequestUIType","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","preciseIdentifier":"c:@E@ZDKNavBarCreateRequestUIType","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"The ZDKNavBarCreateRequestUIType to display.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate":{"abstract":[{"text":"Delegate for the create request view.","type":"text"}],"title":"ZDKCreateRequestUIDelegate","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate","type":"topic","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate","navigatorTitle":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate/navBarCreateRequestUIType()":{"abstract":[{"type":"text","text":"To conform implementations should return the request creation UI type desired."}],"title":"navBarCreateRequestUIType()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/navBarCreateRequestUIType()","type":"topic","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/navbarcreaterequestuitype()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"navBarCreateRequestUIType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@ZDKNavBarCreateRequestUIType","text":"ZDKNavBarCreateRequestUIType","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"navBarCreateRequestUIType"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType":{"title":"ZDKNavBarCreateRequestUIType","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype","abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display request creation."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"navBarCreateRequestUIType"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"navBarCreateRequestUIType","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"ZDKNavBarCreateRequestUIType","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","preciseIdentifier":"c:@E@ZDKNavBarCreateRequestUIType"},{"text":") ","kind":"text"},{"text":"navBarCreateRequestUIType","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/title","value":"ZDKCreateRequestUIDelegate"},{"op":"replace","value":[{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1navBarCreateRequestUIType()\/title","value":"navBarCreateRequestUIType"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1navBarCreateRequestUIType()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navBarCreateRequestUIType"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/title","value":"ZDKNavBarCreateRequestUIType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}]}]}]}