{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/suasdebuglogger\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SupportSDK@objc(cs)ZDKSuasDebugLogger(im)init","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger"]]},"references":{"https://github.com/zendesk/Suas-iOS":{"title":"Suas","titleInlineContent":[{"type":"text","text":"Suas"}],"type":"link","identifier":"https:\/\/github.com\/zendesk\/Suas-iOS","url":"https:\/\/github.com\/zendesk\/Suas-iOS"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/supportsdk\/suasdebuglogger\/init"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SuasDebugLogger":{"role":"symbol","title":"SuasDebugLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SuasDebugLogger"}],"abstract":[{"type":"text","text":"Used to enable "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/zendesk\/Suas-iOS"},{"type":"text","text":" logging."},{"type":"text","text":" "},{"type":"text","text":"Suas drives most of the Ticketing UI so the Suas logs can be useful for debugging it."},{"type":"text","text":" "},{"type":"text","text":"Enabling the Suas logger produces a lot of information and will slow down the SDK."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SuasDebugLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SuasDebugLogger"}],"url":"\/documentation\/supportsdk\/suasdebuglogger"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/title","value":"ZDKSuasDebugLogger"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SuasDebugLogger\/fragments","value":[{"kind":"identifier","text":"ZDKSuasDebugLogger"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}