{"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/jpg","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"jpg","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeJpg"}],"externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypeJpg","modules":[{"name":"SupportSDK"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpg","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"FileType.jpg"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype\/jpg"]},{"paths":["\/documentation\/supportsdk\/filetype\/jpg"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/jpg":{"url":"\/documentation\/supportsdk\/filetype\/jpg","kind":"symbol","navigatorTitle":[{"text":"ZDKFileTypeJpg","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/jpg","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"jpg","kind":"identifier"}],"role":"symbol","title":"FileType.jpg","type":"topic","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","type":"topic","url":"\/documentation\/supportsdk\/filetype","abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"navigatorTitle":[{"kind":"identifier","text":"FileType"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileType"}],"title":"FileType"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKFileTypeJpg","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKFileTypeJpg","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKFileTypeJpg","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1jpg\/title","value":"ZDKFileTypeJpg","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1jpg\/fragments","value":[{"text":"ZDKFileTypeJpg","kind":"identifier"}]},{"op":"replace","value":"ZDKFileType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title"},{"value":[{"text":"ZDKFileType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments"}]}]}