{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpointX"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype\/powerpointx"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/filetype\/powerpointx"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"powerpointX","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePowerpointX"}],"role":"symbol","title":"FileType.powerpointX","modules":[{"name":"SupportSDK"}],"externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypePowerpointX","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"powerpointX","kind":"identifier"}]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/powerpointX":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"powerpointX","kind":"identifier"}],"kind":"symbol","title":"FileType.powerpointX","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePowerpointX"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpointX","url":"\/documentation\/supportsdk\/filetype\/powerpointx","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","type":"topic","url":"\/documentation\/supportsdk\/filetype","abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"navigatorTitle":[{"kind":"identifier","text":"FileType"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileType"}],"title":"FileType"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKFileTypePowerpointX","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ZDKFileTypePowerpointX","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKFileTypePowerpointX"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ZDKFileTypePowerpointX","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1powerpointX\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1powerpointX\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypePowerpointX"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","value":"ZDKFileType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments","value":[{"text":"ZDKFileType","kind":"identifier"}]}]}]}