{"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/containerchild"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/containerchild"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKContainerChild) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContainerChild"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild\/childDelegate"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerChild","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"symbolKind":"protocol","externalID":"c:@M@SupportSDK@objc(pl)ZDKContainerChild","navigatorTitle":[{"text":"ContainerChild","kind":"identifier"}],"title":"ContainerChild","roleHeading":"Protocol"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChild":{"url":"\/documentation\/supportsdk\/containerchild","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ContainerChild","kind":"identifier"}],"title":"ContainerChild","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerChild"}]},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChild/childDelegate":{"url":"\/documentation\/supportsdk\/containerchild\/childdelegate","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"childDelegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier","text":"ContainerChildControllerDelegate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild\/childDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"childDelegate"}],"kind":"symbol","title":"childDelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"ZDKContainerChild","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContainerChild"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKContainerChild","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild\/childDelegate"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKContainerChild","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/title","op":"replace","value":"ZDKContainerChild"},{"value":[{"text":"ZDKContainerChild","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/fragments","op":"replace"},{"op":"replace","value":"childDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild~1childDelegate\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild~1childDelegate\/fragments","value":[{"kind":"identifier","text":"childDelegate"}],"op":"replace"}]}]}