{"sections":[],"abstract":[{"text":"Error description for label error.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterNoArticlesForLabelsDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoArticlesForLabelsDescription"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenternoarticlesforlabelsdescription"]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenternoarticlesforlabelsdescription"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"ZDKHelpCenterNoArticlesForLabelsDescription","kind":"identifier"}],"symbolKind":"var","title":"ZDKHelpCenterNoArticlesForLabelsDescription","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterNoArticlesForLabelsDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","modules":[{"name":"SupportSDK"}],"externalID":"c:@ZDKHelpCenterNoArticlesForLabelsDescription"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterNoArticlesForLabelsDescription":{"title":"ZDKHelpCenterNoArticlesForLabelsDescription","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterNoArticlesForLabelsDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterNoArticlesForLabelsDescription","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenternoarticlesforlabelsdescription","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoArticlesForLabelsDescription","abstract":[{"type":"text","text":"Error description for label error."}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"ZDKHelpCenterNoArticlesForLabelsDescription","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKHelpCenterNoArticlesForLabelsDescription","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterNoArticlesForLabelsDescription"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoArticlesForLabelsDescription\/title","op":"replace","value":"ZDKHelpCenterNoArticlesForLabelsDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoArticlesForLabelsDescription\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterNoArticlesForLabelsDescription"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}