{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol\/updateButtonStatesForButton(atIndexSelected:)"],"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Protocol","title":"ZDKHelpCenterArticleRatingStateProtocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"externalID":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol","role":"symbol","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingStateProtocol/updateButtonStatesForButton(atIndexSelected:)":{"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol\/updatebuttonstatesforbutton(atindexselected:)","required":true,"type":"topic","title":"updateButtonStatesForButton(atIndexSelected:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateButtonStatesForButton"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"atIndexSelected"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateButtonStatesForButtonAtIndexSelected:"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol\/updateButtonStatesForButton(atIndexSelected:)"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingStateProtocol":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","type":"topic","title":"ZDKHelpCenterArticleRatingStateProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}],"abstract":[],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKHelpCenterArticleRatingStateProtocol","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol\/updateButtonStatesForButton(atIndexSelected:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"updateButtonStatesForButtonAtIndexSelected:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol~1updateButtonStatesForButton(atIndexSelected:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateButtonStatesForButtonAtIndexSelected:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol~1updateButtonStatesForButton(atIndexSelected:)\/fragments"},{"value":"ZDKHelpCenterArticleRatingStateProtocol","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}