{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSupportAttachmentCell","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"metadata":{"roleHeading":"Class","modules":[{"name":"SupportSDK"}],"symbolKind":"class","title":"ZDKSupportAttachmentCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKSupportAttachmentCell","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKSupportAttachmentCell"}],"role":"symbol","externalID":"c:objc(cs)ZDKSupportAttachmentCell"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdksupportattachmentcell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdksupportattachmentcell"]}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/fileSize","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/title"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/cellIdentifier()"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)UITableViewCell"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/objc(pl)CALayerDelegate","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/s8SendableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearance","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIDynamicItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.zendesk.SupportSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.zendesk.SupportSDK/objc(cs)UITableViewCell":{"title":"UITableViewCell","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)UITableViewCell"},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment"},"doc://com.zendesk.SupportSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment"},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItemContainer"},"doc://com.zendesk.SupportSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP"},"doc://com.zendesk.SupportSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.zendesk.SupportSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.zendesk.SupportSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.zendesk.SupportSDK/objc(pl)UIGestureRecognizerDelegate":{"title":"UIKit.UIGestureRecognizerDelegate","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.zendesk.SupportSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding"},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItem"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UILargeContentViewerItem"},"doc://com.zendesk.SupportSDK/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UICoordinateSpace"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell/fileSize":{"url":"\/documentation\/supportsdk\/zdksupportattachmentcell\/filesize","navigatorTitle":[{"text":"fileSize","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/fileSize","type":"topic","title":"fileSize","abstract":[{"type":"text","text":"A label which displays the articles parent category and section."}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.SupportSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAccessibilityIdentification"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearance"},"doc://com.zendesk.SupportSDK/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIDynamicItem"},"doc://com.zendesk.SupportSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)CALayerDelegate"},"doc://com.zendesk.SupportSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.zendesk.SupportSDK/objc(pl)UIAppearanceContainer":{"title":"UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell","abstract":[],"role":"symbol","type":"topic","title":"ZDKSupportAttachmentCell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSupportAttachmentCell"}],"kind":"symbol","navigatorTitle":[{"text":"ZDKSupportAttachmentCell","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdksupportattachmentcell"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell/title":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/title","abstract":[{"text":"A label which displays the articles title.","type":"text"}],"role":"symbol","type":"topic","title":"title","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"kind":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdksupportattachmentcell\/title"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSupportAttachmentCell/cellIdentifier()":{"abstract":[{"type":"text","text":"Helper method to retrieve this classes cell identifier."}],"url":"\/documentation\/supportsdk\/zdksupportattachmentcell\/cellidentifier()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/cellIdentifier()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cellIdentifier","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"title":"cellIdentifier()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cellIdentifier"}],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportSDK/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKSupportAttachmentCell"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKSupportAttachmentCell"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKSupportAttachmentCell","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/fileSize","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/title"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSupportAttachmentCell\/cellIdentifier()"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)UITableViewCell"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKSupportAttachmentCell"},{"text":" : ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"fileSize","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1fileSize\/title"},{"value":[{"kind":"identifier","text":"fileSize"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1fileSize\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/title","op":"replace","value":"ZDKSupportAttachmentCell"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell\/fragments","value":[{"text":"ZDKSupportAttachmentCell","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1title\/title","value":"title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1title\/fragments","value":[{"text":"title","kind":"identifier"}]},{"op":"replace","value":"cellIdentifier","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1cellIdentifier()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSupportAttachmentCell~1cellIdentifier()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cellIdentifier"}],"op":"replace"}]}]}