{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"article"},{"kind":"text","text":": "},{"text":"ZDKHelpCenterArticle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":" "},{"text":"configs","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/build(_:andconfigs:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/build(_:andconfigs:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:andConfigs:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"metadata":{"platforms":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"build"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":", "},{"text":"andConfigs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration"},{"kind":"text","text":"]) -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"buildHelpCenterArticle:andConfigs:","kind":"identifier"}],"title":"build(_:andConfigs:)","symbolKind":"method","modules":[{"name":"SupportSDK"}],"roleHeading":"Type Method","externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterArticle:andConfigs:","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"deprecationSummary":[{"inlineContent":[{"text":"use buildHelpCenterArticleUi:andConfigs instead","type":"text"}],"type":"paragraph"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/build(_:andConfigs:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"build","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration"},{"text":"]) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate","text":"ZDKHelpCenterDelegate"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/build(_:andconfigs:)","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticle:andConfigs:"}],"title":"build(_:andConfigs:)","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/build(_:andConfigs:)","kind":"symbol","deprecated":true,"type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate","navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"title":"ZDKHelpCenterDelegate","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","kind":"symbol","deprecated":true,"type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"title":"ZDKHelpCenterUi","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"buildHelpCenterArticle:andConfigs:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"buildHelpCenterArticle:andConfigs:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewControllerobjc(pl)ZDKHelpCenterDelegate","text":"UIViewController<ZDKHelpCenterDelegate>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildHelpCenterArticle:"},{"text":"(","kind":"text"},{"text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"article","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"andConfigs:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>"},{"kind":"text","text":" *) "},{"text":"configs","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"buildHelpCenterArticle:andConfigs:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1build(_:andConfigs:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1build(_:andConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"buildHelpCenterArticle:andConfigs:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title","op":"replace","value":"ZDKHelpCenterDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments","value":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"op":"replace"},{"value":"ZDKHelpCenterUi","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title"},{"op":"replace","value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}