{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui(withconfigs:)"]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui(withconfigs:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverviewUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"roleHeading":"Type Method","title":"buildHelpCenterOverviewUi(withConfigs:)","modules":[{"name":"SupportSDK"}],"role":"symbol","navigatorTitle":[{"text":"buildHelpCenterOverviewUiWithConfigs:","kind":"identifier"}],"externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterOverviewUiWithConfigs:"},"abstract":[{"text":"Build the Help Center Overview view controller with a list of ZDKConfigurations.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildHelpCenterOverviewUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigs"},{"kind":"text","text":" "},{"text":"configs","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier","text":"Configuration"},{"text":"]) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A list of ZDKConfigurations."}],"type":"paragraph"}],"name":"configs"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi(withConfigs:)"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"title":"ZDKHelpCenterUi","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverviewUi(withConfigs:)":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi(withConfigs:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"buildHelpCenterOverviewUi","kind":"identifier"},{"kind":"text","text":"("},{"text":"withConfigs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":"]) -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"buildHelpCenterOverviewUi(withConfigs:)","abstract":[{"type":"text","text":"Build the Help Center Overview view controller with a list of ZDKConfigurations."}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui(withconfigs:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverviewUiWithConfigs:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"buildHelpCenterOverviewUiWithConfigs:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"buildHelpCenterOverviewUiWithConfigs:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildHelpCenterOverviewUiWithConfigs:"},{"kind":"text","text":"("},{"text":"NSArray<id<ZDKConfiguration>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"configs","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ZDKHelpCenterUi","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title"},{"value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi(withConfigs:)\/title","value":"buildHelpCenterOverviewUiWithConfigs:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverviewUiWithConfigs:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi(withConfigs:)\/fragments"}]}]}