{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"buildHelpCenterArticleUi","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"article"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","kind":"typeIdentifier","text":"ZDKHelpCenterArticle"},{"text":", ","kind":"text"},{"text":"andConfigs","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"article","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A ZDKHelpCenterArticle to display."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of ZDKConfigurations."}]}],"name":"configs"}]}],"metadata":{"title":"buildHelpCenterArticleUi(_:andConfigs:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"text":"(","kind":"text"},{"text":"ZDKHelpCenterArticle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":", "},{"text":"andConfigs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterArticleUi:andConfigs:","roleHeading":"Type Method","role":"symbol","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUi:andConfigs:"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:andConfigs:)"},"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:andconfigs:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:andconfigs:)"]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(_:andConfigs:)":{"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:andconfigs:)","abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"title":"buildHelpCenterArticleUi(_:andConfigs:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:andConfigs:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"buildHelpCenterArticleUi","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","kind":"typeIdentifier","text":"ZDKHelpCenterArticle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andConfigs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"buildHelpCenterArticleUi:andConfigs:","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"title":"ZDKHelpCenterUi","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"buildHelpCenterArticleUi:andConfigs:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"buildHelpCenterArticleUi:andConfigs:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"buildHelpCenterArticleUi:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","text":"ZDKHelpCenterArticle"},{"kind":"text","text":" *) "},{"text":"article","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"andConfigs:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"configs","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:andConfigs:)\/title","value":"buildHelpCenterArticleUi:andConfigs:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:andConfigs:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"buildHelpCenterArticleUi:andConfigs:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title","value":"ZDKHelpCenterUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]}]}]}