{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"startWithPresent:with:"}],"modules":[{"name":"SupportSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"present"},{"kind":"text","text":": ("},{"text":"ContainerChildController","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"start(present:with:)","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterCoordinator(im)startWithPresent:with:"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Coordinator.start(present:with:)"},{"type":"text","text":"."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/start(present:with:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator"]]},"variants":[{"paths":["\/documentation\/supportsdk\/helpcentercoordinator\/start(present:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/helpcentercoordinator\/start(present:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"present"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"ContainerChildController","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController","kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"containerDelegate","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","text":"ContainerChildControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator":{"kind":"symbol","type":"topic","title":"HelpCenterCoordinator","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator","url":"\/documentation\/supportsdk\/helpcentercoordinator","navigatorTitle":[{"kind":"identifier","text":"HelpCenterCoordinator"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterCoordinator"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildController":{"title":"ContainerChildController","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ContainerChildController","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController","abstract":[],"role":"symbol","url":"\/documentation\/supportsdk\/containerchildcontroller","type":"topic","navigatorTitle":[{"text":"ContainerChildController","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","type":"topic","title":"ContainerChildControllerDelegate","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContainerChildControllerDelegate"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterCoordinator/start(present:with:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithPresent:with:"}],"abstract":[],"title":"start(present:with:)","url":"\/documentation\/supportsdk\/helpcentercoordinator\/start(present:with:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterCoordinator\/start(present:with:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"present"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","kind":"typeIdentifier","text":"ContainerChildController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"startWithPresent:with:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"startWithPresent:with:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWithPresent:"},{"kind":"text","text":"("},{"text":"void (^)(UIViewController<ZDKContainerChild> *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Q$objc(cs)UIViewController@M@SupportSDK@objc(pl)ZDKContainerChild)"},{"kind":"text","text":") "},{"text":"present","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"with:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","text":"id<ZDKContainerChildControllerDelegate>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"containerDelegate"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/title","value":"ZDKHelpCenterCoordinator"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterCoordinator"}]},{"value":"ZDKContainerChildControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1start(present:with:)\/title","value":"startWithPresent:with:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterCoordinator~1start(present:with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithPresent:with:"}]}]}]}