{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/image","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"roleHeading":"Case","externalID":"c:@E@ZDKNavBarCreateRequestUIType@ZDKNavBarCreateRequestUITypeImage","title":"ZDKNavBarCreateRequestUIType.image","symbolKind":"case","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"ZDKNavBarCreateRequestUITypeImage","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Nav bar button with image for request creation."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/image"]},{"paths":["\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType":{"abstract":[{"text":"Enum to describe the types of nav bar button that display request creation.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"navigatorTitle":[{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","title":"ZDKNavBarCreateRequestUIType"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/image":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"type":"topic","abstract":[{"text":"Nav bar button with image for request creation.","type":"text"}],"url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/image","title":"ZDKNavBarCreateRequestUIType.image","navigatorTitle":[{"text":"ZDKNavBarCreateRequestUITypeImage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/image"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKNavBarCreateRequestUITypeImage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUITypeImage"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUITypeImage"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/title","value":"ZDKNavBarCreateRequestUIType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}]},{"value":"ZDKNavBarCreateRequestUITypeImage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUITypeImage"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1image\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}