{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate","text":"ZDKHelpCenterDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverview"}],"role":"symbol","title":"buildHelpCenterOverview()","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterOverview","modules":[{"name":"SupportSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use buildHelpCenterOverviewUi instead"}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"deprecated":true,"role":"symbol","title":"ZDKHelpCenterDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterDelegate"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverview()":{"deprecated":true,"role":"symbol","title":"buildHelpCenterOverview()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverview"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverview"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"role":"symbol","title":"ZDKHelpCenterUi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"buildHelpCenterOverview"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverview"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIViewController<ZDKHelpCenterDelegate>","preciseIdentifier":"c:Q$objc(cs)UIViewControllerobjc(pl)ZDKHelpCenterDelegate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildHelpCenterOverview"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title","value":"ZDKHelpCenterDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview()\/title","value":"buildHelpCenterOverview"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverview"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title","value":"ZDKHelpCenterUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}