{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"articleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:andconfigs:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:andconfigs:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:andConfigs:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"buildHelpCenterArticleUi(withArticleId:andConfigs:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterArticleUiWithArticleId:andConfigs:","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:andConfigs:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"role":"symbol","title":"ZDKHelpCenterUi","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(withArticleId:andConfigs:)":{"role":"symbol","title":"buildHelpCenterArticleUi(withArticleId:andConfigs:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andConfigs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:andConfigs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:andConfigs:"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:andconfigs:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"buildHelpCenterArticleUiWithArticleId:andConfigs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:andConfigs:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"articleId"},{"kind":"text","text":" "},{"kind":"identifier","text":"andConfigs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"configs"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title","value":"ZDKHelpCenterUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:andConfigs:)\/title","value":"buildHelpCenterArticleUiWithArticleId:andConfigs:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:andConfigs:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:andConfigs:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}