{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/supportsdk\/containerviewcontroller\/navitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/containerviewcontroller\/navitem"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/navItem","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ContainerChildControllerDelegate.navItem"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":"?"}],"title":"navItem","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@CM@SupportSDK@objc(cs)ContainerViewController(py)navItem","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"navItem"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/ContainerChildControllerDelegate-Implementations"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController":{"role":"symbol","title":"ContainerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerViewController"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContainerViewController"}],"url":"\/documentation\/supportsdk\/containerviewcontroller"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/navItem":{"role":"symbol","title":"navItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/navItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"navItem"}],"url":"\/documentation\/supportsdk\/containerviewcontroller\/navitem"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/ContainerChildControllerDelegate-Implementations":{"role":"collectionGroup","title":"ContainerChildControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/ContainerChildControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/supportsdk\/containerviewcontroller\/containerchildcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"navItem"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"navItem"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":" * "},{"kind":"identifier","text":"navItem"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/title","value":"ContainerViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/fragments","value":[{"kind":"identifier","text":"ContainerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1navItem\/title","value":"navItem"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1navItem\/fragments","value":[{"kind":"identifier","text":"navItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}