{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","modules":[{"name":"SupportSDK"}],"externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypePlain","title":"FileType.plain","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"plain","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKFileTypePlain","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/supportsdk\/filetype\/plain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/filetype\/plain"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"plain","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/plain","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/plain":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/plain","kind":"symbol","title":"FileType.plain","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePlain"}],"url":"\/documentation\/supportsdk\/filetype\/plain","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"plain","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","type":"topic","abstract":[{"text":"Enum that represents the file types that zendesk supports","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FileType","kind":"identifier"}],"url":"\/documentation\/supportsdk\/filetype","kind":"symbol","role":"symbol","title":"FileType","navigatorTitle":[{"text":"FileType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKFileTypePlain"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKFileTypePlain","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKFileTypePlain","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ZDKFileTypePlain","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1plain\/title"},{"value":[{"text":"ZDKFileTypePlain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1plain\/fragments","op":"replace"},{"value":"ZDKFileType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFileType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments"}]}]}