{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter"]]},"metadata":{"externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterContactUsRouter(im)decideButtonActionForNavBar","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"decideButtonActionForNavBar"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decideButtonActionForNavBar","kind":"identifier"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","title":"decideButtonActionForNavBar()","role":"symbol"},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForNavBar()","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decideButtonActionForNavBar"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionfornavbar()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionfornavbar()"]}],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter/decideButtonActionForNavBar()":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForNavBar()","url":"\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionfornavbar()","navigatorTitle":[{"text":"decideButtonActionForNavBar","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decideButtonActionForNavBar","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"role":"symbol","title":"decideButtonActionForNavBar()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/helpcentercontactusrouter","title":"HelpCenterContactUsRouter","navigatorTitle":[{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"decideButtonActionForNavBar"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decideButtonActionForNavBar"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"decideButtonActionForNavBar"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForNavBar()\/title","value":"decideButtonActionForNavBar","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"decideButtonActionForNavBar"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForNavBar()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/title","value":"ZDKHelpCenterContactUsRouter"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/fragments","value":[{"text":"ZDKHelpCenterContactUsRouter","kind":"identifier"}]}]}]}