{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionforemptysearch()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionforemptysearch()"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Instance Method","symbolKind":"method","title":"decideButtonActionForEmptySearch()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decideButtonActionForEmptySearch","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"decideButtonActionForEmptySearch","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterContactUsRouter(im)decideButtonActionForEmptySearch","role":"symbol"},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForEmptySearch()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decideButtonActionForEmptySearch","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter/decideButtonActionForEmptySearch()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter\/decideButtonActionForEmptySearch()","type":"topic","title":"decideButtonActionForEmptySearch()","url":"\/documentation\/supportsdk\/helpcentercontactusrouter\/decidebuttonactionforemptysearch()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decideButtonActionForEmptySearch","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"decideButtonActionForEmptySearch","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"role":"collection","title":"SupportSDK","url":"\/documentation\/supportsdk","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterContactUsRouter":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/helpcentercontactusrouter","title":"HelpCenterContactUsRouter","navigatorTitle":[{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterContactUsRouter","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterContactUsRouter"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"decideButtonActionForEmptySearch"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"decideButtonActionForEmptySearch","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"decideButtonActionForEmptySearch","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForEmptySearch()\/title","value":"decideButtonActionForEmptySearch","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter~1decideButtonActionForEmptySearch()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decideButtonActionForEmptySearch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/title","value":"ZDKHelpCenterContactUsRouter"},{"op":"replace","value":[{"text":"ZDKHelpCenterContactUsRouter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterContactUsRouter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}