{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration"]]},"abstract":[{"type":"text","text":"Show the "},{"code":"Contact Support","type":"codeVoice"},{"text":" button in the help center’s article view","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/showContactOptions"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"showContactOptions","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"style":"note","name":"Version","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.3.0"}]}],"type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/articleuiconfiguration\/showcontactoptions"]},{"paths":["\/documentation\/supportsdk\/articleuiconfiguration\/showcontactoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@SupportSDK@objc(cs)ZDKArticleUiConfiguration(py)showContactOptions","role":"symbol","symbolKind":"property","title":"showContactOptions","roleHeading":"Instance Property","navigatorTitle":[{"text":"showContactOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"showContactOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"SupportSDK"}]},"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration":{"url":"\/documentation\/supportsdk\/articleuiconfiguration","navigatorTitle":[{"text":"ArticleUiConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration","abstract":[{"text":"Data class used to configure Article Screen","type":"text"}],"type":"topic","title":"ArticleUiConfiguration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleUiConfiguration"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/showContactOptions":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showContactOptions"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Show the ","type":"text"},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button in the help center’s article view"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/showContactOptions","title":"showContactOptions","navigatorTitle":[{"kind":"identifier","text":"showContactOptions"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/supportsdk\/articleuiconfiguration\/showcontactoptions"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"showContactOptions","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"showContactOptions","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"showContactOptions","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKArticleUiConfiguration","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKArticleUiConfiguration"}]},{"value":"showContactOptions","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1showContactOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"showContactOptions"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1showContactOptions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}