{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/top"]},{"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/top"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@ZDKLayoutGuideApplicatorPosition@ZDKLayoutGuideApplicatorPositionTop","symbolKind":"case","title":"ZDKLayoutGuideApplicatorPosition.top","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"ZDKLayoutGuideApplicatorPositionTop","kind":"identifier"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/top","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Fix the top guide layout position"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition","navigatorTitle":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Layout guides positions to fix"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition","title":"ZDKLayoutGuideApplicatorPosition","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicatorPosition/top":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Fix the top guide layout position"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicatorposition\/top","title":"ZDKLayoutGuideApplicatorPosition.top","navigatorTitle":[{"text":"ZDKLayoutGuideApplicatorPositionTop","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicatorPosition\/top"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKLayoutGuideApplicatorPositionTop","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionTop"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionTop"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/title","value":"ZDKLayoutGuideApplicatorPosition"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition\/fragments","value":[{"text":"ZDKLayoutGuideApplicatorPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1top\/title","op":"replace","value":"ZDKLayoutGuideApplicatorPositionTop"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicatorPositionTop"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicatorPosition~1top\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}