{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"buildRequestList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"configurations","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configurations","content":[{"inlineContent":[{"text":"A list of Configuration objects. You do not need to configure the controller being presented.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Conversations must be enabled in your Zendesk SDK admin settings. Conversations are not available on Essential."}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"2.0.0"}],"type":"paragraph"}],"name":"Version","type":"aside","style":"note"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"buildRequestList(with:)","modules":[{"name":"SupportSDK"}],"symbolKind":"method","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUi(cm)buildRequestListWith:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildRequestList","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"navigatorTitle":[{"kind":"identifier","text":"buildRequestListWith:"}],"roleHeading":"Type Method"},"kind":"symbol","abstract":[{"text":"Build the Request List with a list of Configurations.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList(with:)"},"variants":[{"paths":["\/documentation\/supportsdk\/requestui\/buildrequestlist(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/requestui\/buildrequestlist(with:)"]}],"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestList(with:)":{"kind":"symbol","role":"symbol","title":"buildRequestList(with:)","abstract":[{"type":"text","text":"Build the Request List with a list of Configurations."}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestlist(with:)","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestList(with:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"buildRequestList","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"navigatorTitle":[{"text":"buildRequestListWith:","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi":{"navigatorTitle":[{"kind":"identifier","text":"RequestUi"}],"kind":"symbol","title":"RequestUi","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestUi"}],"abstract":[{"type":"text","text":"Used to build view controller for ticketing. The returned objects must be presented inside a UINavigationController."},{"text":" ","type":"text"},{"type":"text","text":"The containing navigation controller can be presented any way you see fit."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","url":"\/documentation\/supportsdk\/requestui","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"buildRequestListWith:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestListWith:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"buildRequestListWith:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configurations"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestList(with:)\/title","value":"buildRequestListWith:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"buildRequestListWith:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestList(with:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/title","value":"ZDKRequestUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/fragments","value":[{"text":"ZDKRequestUi","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}