{"metadata":{"modules":[{"name":"SupportSDK"}],"title":"buildRequestUi(with:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildRequestUi"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier","text":"Configuration"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"buildRequestUiWith:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUi(cm)buildRequestUiWith:"},"variants":[{"paths":["\/documentation\/supportsdk\/requestui\/buildrequestui(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/requestui\/buildrequestui(with:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"buildRequestUi","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configurations"},{"text":": [","kind":"text"},{"text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"configurations","content":[{"inlineContent":[{"type":"text","text":"A list of Configuration objects. You do not need to configure the controller being presented."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"name":"Version"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(with:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Build the Request Ui with a list of Configurations.","type":"text"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestUi(with:)":{"kind":"symbol","role":"symbol","title":"buildRequestUi(with:)","abstract":[{"text":"Build the Request Ui with a list of Configurations.","type":"text"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestui(with:)","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(with:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"navigatorTitle":[{"text":"buildRequestUiWith:","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi":{"navigatorTitle":[{"kind":"identifier","text":"RequestUi"}],"kind":"symbol","title":"RequestUi","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RequestUi"}],"abstract":[{"type":"text","text":"Used to build view controller for ticketing. The returned objects must be presented inside a UINavigationController."},{"text":" ","type":"text"},{"type":"text","text":"The containing navigation controller can be presented any way you see fit."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","url":"\/documentation\/supportsdk\/requestui","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"buildRequestUiWith:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"buildRequestUiWith:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildRequestUiWith:"},{"text":"(","kind":"text"},{"text":"NSArray<id<ZDKConfiguration>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configurations","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"buildRequestUiWith:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(with:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"buildRequestUiWith:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(with:)\/fragments","op":"replace"},{"op":"replace","value":"ZDKRequestUi","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRequestUi"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}