{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiDelegate"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","text":"ZDKHelpCenterConversationsUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"uiDelegate","kind":"identifier"}],"required":true,"title":"uiDelegate","symbolKind":"property","platforms":[],"roleHeading":"Instance Property","externalID":"c:objc(pl)ZDKHelpCenterDelegate(py)uiDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"uiDelegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate","text":"ZDKHelpCenterConversationsUIDelegate","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate\/uiDelegate"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterdelegate\/uidelegate"]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterdelegate\/uidelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"kind":"symbol","deprecated":true,"url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate","role":"symbol","title":"ZDKHelpCenterDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKHelpCenterDelegate"}],"type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","role":"collection","url":"\/documentation\/supportsdk","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","abstract":[],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate/uiDelegate":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate\/uiDelegate","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uiDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate","text":"ZDKHelpCenterConversationsUIDelegate"},{"kind":"text","text":"!"}],"title":"uiDelegate","required":true,"deprecated":true,"navigatorTitle":[{"text":"uiDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate\/uidelegate"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate":{"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"deprecated":true,"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","title":"ZDKHelpCenterConversationsUIDelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"uiDelegate","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"uiDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<ZDKHelpCenterConversationsUIDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)ZDKHelpCenterConversationsUIDelegate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"uiDelegate"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title","value":"ZDKHelpCenterDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterDelegate"}]},{"op":"replace","value":"uiDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate~1uiDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"uiDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate~1uiDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/title","value":"ZDKHelpCenterConversationsUIDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/fragments","op":"replace"}]}]}