{"metadata":{"modules":[{"name":"SupportSDK"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileType","kind":"identifier"}],"externalID":"c:@M@SupportSDK@E@ZDKFileType","symbolKind":"enum","roleHeading":"Enumeration","title":"FileType","navigatorTitle":[{"text":"FileType","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKFileType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"},"abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/filetype"]},{"paths":["\/documentation\/supportsdk\/filetype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/binary","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/excel","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/heic","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/jpg","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/keynote","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/numbers","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pages","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pdf","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/plain","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/png","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpoint","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpointX","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/word"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/Equatable-Implementations","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/excel":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/excel","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/excel","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"excel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeExcel"}],"title":"FileType.excel"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/binary":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/binary","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/binary","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"binary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeBinary"}],"title":"FileType.binary"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/Equatable-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/equatable-implementations","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/Equatable-Implementations","type":"topic","role":"collectionGroup","title":"Equatable Implementations"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/supportsdk\/filetype\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"type":"topic","navigatorTitle":[{"text":"FileType","kind":"identifier"}],"abstract":[{"text":"Enum that represents the file types that zendesk supports","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","title":"FileType","url":"\/documentation\/supportsdk\/filetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FileType","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/powerpoint":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"powerpoint","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpoint","url":"\/documentation\/supportsdk\/filetype\/powerpoint","role":"symbol","title":"FileType.powerpoint","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePowerpoint"}],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/jpg":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/jpg","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/jpg","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpg"}],"navigatorTitle":[{"text":"ZDKFileTypeJpg","kind":"identifier"}],"title":"FileType.jpg"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/powerpointX":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/powerpointx","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpointX","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"powerpointX","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePowerpointX"}],"title":"FileType.powerpointX"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/plain":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/plain","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/plain","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"plain"}],"navigatorTitle":[{"text":"ZDKFileTypePlain","kind":"identifier"}],"title":"FileType.plain"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/heic":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"heic","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/heic","navigatorTitle":[{"text":"ZDKFileTypeHeic","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/heic","title":"FileType.heic","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/pdf":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/pdf","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pdf","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pdf","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePdf"}],"title":"FileType.pdf"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/numbers":{"abstract":[],"type":"topic","title":"FileType.numbers","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/numbers","role":"symbol","url":"\/documentation\/supportsdk\/filetype\/numbers","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numbers"}],"navigatorTitle":[{"text":"ZDKFileTypeNumbers","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/word":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/word","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/word","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"word"}],"navigatorTitle":[{"text":"ZDKFileTypeWord","kind":"identifier"}],"title":"FileType.word"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/png":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/png","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/png","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"png","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePng"}],"title":"FileType.png"},"doc://com.zendesk.SupportSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SY"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/keynote":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/keynote","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/keynote","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keynote"}],"navigatorTitle":[{"text":"ZDKFileTypeKeynote","kind":"identifier"}],"title":"FileType.keynote"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/pages":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/filetype\/pages","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pages","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pages","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypePages"}],"title":"FileType.pages"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/filetype\/init(rawvalue:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKFileType","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"ZDKFileType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKFileType","kind":"identifier"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/binary","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/excel","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/heic","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/jpg","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/keynote","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/numbers","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pages","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/pdf","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/plain","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/png","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpoint","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/powerpointX","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/word"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKFileType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1excel\/title","value":"ZDKFileTypeExcel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1excel\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypeExcel"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1binary\/title","op":"replace","value":"ZDKFileTypeBinary"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1binary\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFileTypeBinary"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title","op":"replace","value":"ZDKFileType"},{"op":"replace","value":[{"text":"ZDKFileType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1powerpoint\/title","value":"ZDKFileTypePowerpoint","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1powerpoint\/fragments","op":"replace","value":[{"text":"ZDKFileTypePowerpoint","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1jpg\/title","op":"replace","value":"ZDKFileTypeJpg"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1jpg\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypeJpg"}]},{"value":"ZDKFileTypePowerpointX","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1powerpointX\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1powerpointX\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFileTypePowerpointX"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1plain\/title","value":"ZDKFileTypePlain","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1plain\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFileTypePlain"}]},{"op":"replace","value":"ZDKFileTypeHeic","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1heic\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1heic\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypeHeic"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1pdf\/title","value":"ZDKFileTypePdf"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1pdf\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKFileTypePdf"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1numbers\/title","value":"ZDKFileTypeNumbers"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1numbers\/fragments","op":"replace","value":[{"text":"ZDKFileTypeNumbers","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1word\/title","value":"ZDKFileTypeWord","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1word\/fragments","value":[{"kind":"identifier","text":"ZDKFileTypeWord"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1png\/title","op":"replace","value":"ZDKFileTypePng"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1png\/fragments","value":[{"text":"ZDKFileTypePng","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1keynote\/title","value":"ZDKFileTypeKeynote"},{"value":[{"kind":"identifier","text":"ZDKFileTypeKeynote"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1keynote\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1pages\/title","value":"ZDKFileTypePages"},{"value":[{"text":"ZDKFileTypePages","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1pages\/fragments","op":"replace"}]}]}