{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol"],"title":"Conforms To"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/init(withArticleId:andLocale:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/articleRatingVoteSelected(_:at:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/currentArticleVote()"]}],"metadata":{"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)HelpCenterArticleVotingHandler","symbolKind":"class","title":"HelpCenterArticleVotingHandler","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler"]},{"paths":["\/documentation\/supportsdk\/helpcenterarticlevotinghandler"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler","title":"HelpCenterArticleVotingHandler","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler/articleRatingVoteSelected(_:at:)":{"type":"topic","title":"articleRatingVoteSelected(_:at:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/articleRatingVoteSelected(_:at:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"articleRatingVoteSelected","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticleRatingStateProtocol","preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol"},{"text":", ","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/articleratingvoteselected(_:at:)"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingHandlerProtocol":{"title":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingHandlerProtocol"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler/currentArticleVote()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"currentArticleVote","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/currentarticlevote()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"currentArticleVote"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/currentArticleVote()","title":"currentArticleVote()","type":"topic","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterArticleVotingHandler/init(withArticleId:andLocale:)":{"url":"\/documentation\/supportsdk\/helpcenterarticlevotinghandler\/init(witharticleid:andlocale:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/init(withArticleId:andLocale:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andLocale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithArticleId:andLocale:","kind":"identifier"}],"title":"init(withArticleId:andLocale:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"HelpCenterArticleVotingHandler","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"HelpCenterArticleVotingHandler"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/articleRatingVoteSelected(_:at:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/currentArticleVote()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterArticleVotingHandler\/init(withArticleId:andLocale:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterArticleVotingHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/title","value":"HelpCenterArticleVotingHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler\/fragments","value":[{"text":"HelpCenterArticleVotingHandler","kind":"identifier"}]},{"value":"articleRatingVoteSelected:atIndex:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1articleRatingVoteSelected(_:at:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"articleRatingVoteSelected:atIndex:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1articleRatingVoteSelected(_:at:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/title","value":"ZDKHelpCenterArticleRatingHandlerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingHandlerProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1currentArticleVote()\/title","value":"currentArticleVote"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"currentArticleVote","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1currentArticleVote()\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1init(withArticleId:andLocale:)\/title","value":"initWithArticleId:andLocale:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithArticleId:andLocale:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterArticleVotingHandler~1init(withArticleId:andLocale:)\/fragments"}]}]}