{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens ","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/SY","doc:\/\/com.zendesk.SupportSDK\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKContactUsVisibility"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"ZDKContactUsVisibilityArticleListAndArticle: The contact us nav bar button is visible in the article list and the article view."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ZDKContactUsVisibilityArticleListOnly: The contact us nav bar button is only visible in the article list."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"ZDKContactUsVisibilityOff: The contact us nav bar button is not visible anywhere.","type":"text"}]}]}],"type":"unorderedList"}]}],"abstract":[{"text":"Used to select where conversations nav bar button will be active.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListAndArticle","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListOnly","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/off"]},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/Equatable-Implementations","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/RawRepresentable-Implementations"]}],"kind":"symbol","metadata":{"externalID":"c:@E@ZDKContactUsVisibility","role":"symbol","platforms":[],"roleHeading":"Enumeration","title":"ZDKContactUsVisibility","symbolKind":"enum","navigatorTitle":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKContactUsVisibility"}]},"references":{"doc://com.zendesk.SupportSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/init(rawValue:)":{"abstract":[],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","deprecated":true,"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/articleListAndArticle":{"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistandarticle","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListAndArticle","type":"topic","title":"ZDKContactUsVisibility.articleListAndArticle","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"articleListAndArticle"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"ZDKContactUsVisibilityArticleListAndArticle","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility":{"url":"\/documentation\/supportsdk\/zdkcontactusvisibility","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","type":"topic","title":"ZDKContactUsVisibility","abstract":[{"text":"Used to select where conversations nav bar button will be active.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKContactUsVisibility"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"ZDKContactUsVisibility","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SY"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","type":"topic"},"doc://com.zendesk.SupportSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/RawRepresentable-Implementations"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/off":{"title":"ZDKContactUsVisibility.off","type":"topic","kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/off","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"off","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKContactUsVisibilityOff","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/off"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/articleListOnly":{"abstract":[],"url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/articlelistonly","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListOnly","kind":"symbol","title":"ZDKContactUsVisibility.articleListOnly","navigatorTitle":[{"text":"ZDKContactUsVisibilityArticleListOnly","kind":"identifier"}],"deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"articleListOnly","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"ZDKContactUsVisibility","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContactUsVisibility"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKContactUsVisibility","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListAndArticle","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/articleListOnly","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/off"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKContactUsVisibility","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListAndArticle\/title","value":"ZDKContactUsVisibilityArticleListAndArticle"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListAndArticle\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListAndArticle"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/title","op":"replace","value":"ZDKContactUsVisibility"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/fragments","value":[{"text":"ZDKContactUsVisibility","kind":"identifier"}]},{"value":"ZDKContactUsVisibilityOff","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1off\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1off\/fragments","value":[{"text":"ZDKContactUsVisibilityOff","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListOnly\/title","value":"ZDKContactUsVisibilityArticleListOnly","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility~1articleListOnly\/fragments","value":[{"kind":"identifier","text":"ZDKContactUsVisibilityArticleListOnly"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}