{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKToastViewWrapper"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKToastViewWrapper"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKToastViewWrapper"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)ZDKToastViewWrapper","title":"ZDKToastViewWrapper","modules":[{"name":"SupportSDK"}],"symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)UIView"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/objc(pl)CALayerDelegate","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/s8SendableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearance","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UICoordinateSpace","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIDynamicItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItemContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/isVisible"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/dismiss()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/hideToastView(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:buttonTitle:action:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:duration:)"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper"]}],"references":{"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/showError(in:withMessage:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:)","type":"topic","title":"showError(in:withMessage:)","role":"symbol","url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/showerror(in:withmessage:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withMessage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"showErrorInViewController:withMessage:"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/isVisible":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isVisible"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/isVisible","title":"isVisible","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isVisible","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/isvisible"},"doc://com.zendesk.SupportSDK/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAccessibilityIdentification"},"doc://com.zendesk.SupportSDK/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://com.zendesk.SupportSDK/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://com.zendesk.SupportSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.zendesk.SupportSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP"},"doc://com.zendesk.SupportSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/showError(in:withMessage:duration:)":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:duration:)","navigatorTitle":[{"text":"showErrorInViewController:withMessage:duration:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":")","kind":"text"}],"url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/showerror(in:withmessage:duration:)","title":"showError(in:withMessage:duration:)","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)CALayerDelegate"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKToastViewWrapper"}],"url":"\/documentation\/supportsdk\/zdktoastviewwrapper","title":"ZDKToastViewWrapper","navigatorTitle":[{"text":"ZDKToastViewWrapper","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)UIView"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/dismiss()":{"kind":"symbol","abstract":[],"url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/dismiss()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/dismiss()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"dismiss","kind":"identifier"}],"title":"dismiss()"},"doc://com.zendesk.SupportSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://com.zendesk.SupportSDK/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.zendesk.SupportSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.zendesk.SupportSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/showError(in:withMessage:buttonTitle:action:)":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:buttonTitle:action:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showError"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"text":"buttonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")!)"}],"url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/showerror(in:withmessage:buttontitle:action:)","title":"showError(in:withMessage:buttonTitle:action:)","navigatorTitle":[{"text":"showErrorInViewController:withMessage:buttonTitle:action:","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://com.zendesk.SupportSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.zendesk.SupportSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/hideToastView(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hideToastView"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/hideToastView(_:)","type":"topic","title":"hideToastView(_:)","role":"symbol","url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/hidetoastview(_:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hideToastView:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKToastViewWrapper"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"ZDKToastViewWrapper","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKToastViewWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/isVisible"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/dismiss()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/hideToastView(_:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:buttonTitle:action:)","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:duration:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)UIView"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ZDKToastViewWrapper","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:)\/title","value":"showErrorInViewController:withMessage:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"showErrorInViewController:withMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1isVisible\/title","op":"replace","value":"isVisible"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1isVisible\/fragments","value":[{"text":"isVisible","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:duration:)\/title","value":"showErrorInViewController:withMessage:duration:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"showErrorInViewController:withMessage:duration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:duration:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/title","value":"ZDKToastViewWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/fragments","value":[{"text":"ZDKToastViewWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1dismiss()\/title","value":"dismiss","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1dismiss()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dismiss","kind":"identifier"}]},{"value":"showErrorInViewController:withMessage:buttonTitle:action:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:buttonTitle:action:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:buttonTitle:action:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showErrorInViewController:withMessage:buttonTitle:action:"}]},{"op":"replace","value":"hideToastView:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1hideToastView(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1hideToastView(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hideToastView:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}