{"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKUIIsLandscape"}],"modules":[{"name":"SupportSDK"}],"roleHeading":"Function","role":"symbol","title":"ZDKUIIsLandscape()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIIsLandscape"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:ZDKUIUtil.h@F@ZDKUIIsLandscape","symbolKind":"func"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkuiislandscape()"]},{"paths":["\/documentation\/supportsdk\/zdkuiislandscape()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIIsLandscape()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Helper for device orientation."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIIsLandscape"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIIsLandscape()":{"kind":"symbol","navigatorTitle":[{"text":"ZDKUIIsLandscape","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Helper for device orientation."}],"url":"\/documentation\/supportsdk\/zdkuiislandscape()","title":"ZDKUIIsLandscape()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"ZDKUIIsLandscape","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIIsLandscape()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Function"},{"path":"\/metadata\/title","value":"ZDKUIIsLandscape","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"value":[{"text":"ZDKUIIsLandscape","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUIIsLandscape"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIIsLandscape()\/title","value":"ZDKUIIsLandscape"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIIsLandscape()\/fragments","value":[{"text":"ZDKUIIsLandscape","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}