{"metadata":{"roleHeading":"Type Method","symbolKind":"method","platforms":[],"title":"buildHelpCenterArticle(withArticleId:andConfigs:)","externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterArticleWithArticleId:andConfigs:","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:andConfigs:"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticle"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"andConfigs","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"role":"symbol"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildHelpCenterArticle"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"articleId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"andConfigs"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"configs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use buildHelpCenterArticleUiWithArticleId:andConfigs instead"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:andconfigs:)"]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:andconfigs:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:andConfigs:)","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticle(withArticleId:andConfigs:)":{"navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:andConfigs:"}],"deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:andConfigs:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"buildHelpCenterArticle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"andConfigs","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"abstract":[],"type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:andconfigs:)","title":"buildHelpCenterArticle(withArticleId:andConfigs:)","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"title":"ZDKHelpCenterDelegate","url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","deprecated":true},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","navigatorTitle":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterUi","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"title":"ZDKHelpCenterUi","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterui"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"buildHelpCenterArticleWithArticleId:andConfigs:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"buildHelpCenterArticleWithArticleId:andConfigs:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"UIViewController<ZDKHelpCenterDelegate>","preciseIdentifier":"c:Q$objc(cs)UIViewControllerobjc(pl)ZDKHelpCenterDelegate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"articleId"},{"text":" ","kind":"text"},{"text":"andConfigs:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<id<ZDKConfiguration>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configs"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"buildHelpCenterArticleWithArticleId:andConfigs:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:andConfigs:)\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"buildHelpCenterArticleWithArticleId:andConfigs:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:andConfigs:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title","value":"ZDKHelpCenterDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterDelegate"}],"op":"replace"},{"value":"ZDKHelpCenterUi","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}