{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUi:"}],"externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterArticleUi:","modules":[{"name":"SupportSDK"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"buildHelpCenterArticleUi","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKHelpCenterArticle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"roleHeading":"Type Method","title":"buildHelpCenterArticleUi(_:)","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"buildHelpCenterArticleUi","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"article","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A ZDKHelpCenterArticle to display."}]}],"name":"article"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Build the Help Center Article view controller. Displays a single article.","type":"text"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","navigatorTitle":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterUi","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"title":"ZDKHelpCenterUi","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterui"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(_:)":{"url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUi:"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buildHelpCenterArticleUi"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKHelpCenterArticle","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"role":"symbol","title":"buildHelpCenterArticleUi(_:)","type":"topic","abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"buildHelpCenterArticleUi:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"buildHelpCenterArticleUi:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"buildHelpCenterArticleUi:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterArticle","text":"ZDKHelpCenterArticle"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"article"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKHelpCenterUi","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:)\/title","value":"buildHelpCenterArticleUi:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"buildHelpCenterArticleUi:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}