{"metadata":{"title":"buildHelpCenterOverviewUi()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterOverviewUi","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterOverviewUi","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterOverviewUi"}],"modules":[{"name":"SupportSDK"}],"roleHeading":"Type Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Build the Help Center Overview view controller. Displays an overview of your HelpCenter","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"buildHelpCenterOverviewUi","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterUi","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","url":"\/documentation\/supportsdk\/zdkhelpcenterui","title":"ZDKHelpCenterUi","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverviewUi()":{"title":"buildHelpCenterOverviewUi()","role":"symbol","abstract":[{"type":"text","text":"Build the Help Center Overview view controller. Displays an overview of your HelpCenter"}],"navigatorTitle":[{"text":"buildHelpCenterOverviewUi","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverviewUi()","kind":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverviewui()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterOverviewUi","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"kind":"symbol","type":"topic","title":"SupportSDK","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"buildHelpCenterOverviewUi","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"buildHelpCenterOverviewUi","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"buildHelpCenterOverviewUi"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title","value":"ZDKHelpCenterUi"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi()\/title","value":"buildHelpCenterOverviewUi","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverviewUi()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverviewUi"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}