{"metadata":{"title":"showError(in:withMessage:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)ZDKToastViewWrapper(im)showErrorInViewController:withMessage:","navigatorTitle":[{"text":"showErrorInViewController:withMessage:","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withMessage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!)","kind":"text"}]},"variants":[{"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper\/showerror(in:withmessage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper\/showerror(in:withmessage:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showError"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"!, ","kind":"text"},{"text":"withMessage","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"!)","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper"]]},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/showError(in:withMessage:)":{"title":"showError(in:withMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showError"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withMessage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"!)","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"showErrorInViewController:withMessage:","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/showerror(in:withmessage:)","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/showError(in:withMessage:)","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"url":"\/documentation\/supportsdk","title":"SupportSDK","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper":{"url":"\/documentation\/supportsdk\/zdktoastviewwrapper","abstract":[],"title":"ZDKToastViewWrapper","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKToastViewWrapper","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKToastViewWrapper"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"showErrorInViewController:withMessage:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showErrorInViewController:withMessage:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"showErrorInViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withMessage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:)\/title","value":"showErrorInViewController:withMessage:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1showError(in:withMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showErrorInViewController:withMessage:"}]},{"value":"ZDKToastViewWrapper","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/title","op":"replace"},{"op":"replace","value":[{"text":"ZDKToastViewWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/fragments"}]}]}