{"variants":[{"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonlocalizedlabel()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonlocalizedlabel()"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createRequestBarButtonLocalizedLabel","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"createRequestBarButtonLocalizedLabel()","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"createRequestBarButtonLocalizedLabel","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"externalID":"c:objc(pl)ZDKCreateRequestUIDelegate(im)createRequestBarButtonLocalizedLabel","required":true,"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonLocalizedLabel()"},"sections":[],"abstract":[{"text":"To conform implementations should return a localized string for the right nav bar button title.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createRequestBarButtonLocalizedLabel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A localized string for the right nav bar button.","type":"text"}]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate":{"navigatorTitle":[{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate","title":"ZDKCreateRequestUIDelegate","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Delegate for the create request view."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate/createRequestBarButtonLocalizedLabel()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createRequestBarButtonLocalizedLabel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"title":"createRequestBarButtonLocalizedLabel()","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonlocalizedlabel()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createRequestBarButtonLocalizedLabel"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonLocalizedLabel()","abstract":[{"type":"text","text":"To conform implementations should return a localized string for the right nav bar button title."}],"required":true},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"createRequestBarButtonLocalizedLabel","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createRequestBarButtonLocalizedLabel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createRequestBarButtonLocalizedLabel"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/title","value":"ZDKCreateRequestUIDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonLocalizedLabel()\/title","op":"replace","value":"createRequestBarButtonLocalizedLabel"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonLocalizedLabel()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createRequestBarButtonLocalizedLabel"}]}]}]}