{"kind":"symbol","variants":[{"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptions"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.4.0"}]}],"name":"Version","style":"note","type":"aside"}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Show the "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button in the Help Center main screen"},{"text":" ","type":"text"},{"type":"text","text":"true by default"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showContactOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterUiConfiguration(py)showContactOptions","role":"symbol","title":"showContactOptions","modules":[{"name":"SupportSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"showContactOptions"}]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","abstract":[],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","url":"\/documentation\/supportsdk","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration":{"abstract":[{"text":"Data class used to configure Help Center","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","role":"symbol","title":"HelpCenterUiConfiguration","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HelpCenterUiConfiguration"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/showContactOptions":{"navigatorTitle":[{"text":"showContactOptions","kind":"identifier"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptions","title":"showContactOptions","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptions","abstract":[{"type":"text","text":"Show the "},{"code":"Contact Support","type":"codeVoice"},{"text":" button in the Help Center main screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"true by default"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"showContactOptions"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"showContactOptions","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptions"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/title","value":"ZDKHelpCenterUiConfiguration"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterUiConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptions\/title","value":"showContactOptions","op":"replace"},{"value":[{"kind":"identifier","text":"showContactOptions"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptions\/fragments","op":"replace"}]}]}