{"metadata":{"title":"CGCenterRectInRect(_:_:)","modules":[{"name":"SupportSDK"}],"symbolKind":"func","externalID":"c:ZDKUIUtil.h@F@CGCenterRectInRect","roleHeading":"Function","navigatorTitle":[{"text":"CGCenterRectInRect","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGCenterRectInRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGCenterRectInRect(_:_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/cgcenterrectinrect(_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/cgcenterrectinrect(_:_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGCenterRectInRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"inRect","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CGCenterRectInRect(_:_:)":{"url":"\/documentation\/supportsdk\/cgcenterrectinrect(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGCenterRectInRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CGCenterRectInRect(_:_:)","role":"symbol","type":"topic","kind":"symbol","title":"CGCenterRectInRect(_:_:)","abstract":[],"navigatorTitle":[{"text":"CGCenterRectInRect","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Function","path":"\/metadata\/roleHeading","op":"replace"},{"value":"CGCenterRectInRect","path":"\/metadata\/title","op":"replace"},{"value":"func","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"CGCenterRectInRect"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"CGCenterRectInRect","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inRect"},{"text":");","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"CGCenterRectInRect","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGCenterRectInRect(_:_:)\/title"},{"op":"replace","value":[{"text":"CGCenterRectInRect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CGCenterRectInRect(_:_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}