{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerViewController"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/viewDidLoad()"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/ContainerChildControllerDelegate-Implementations"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)UIViewController"]},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s8CopyableP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/s8SendableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIContentContainer","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIStateRestoring","doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/containerviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/containerviewcontroller"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"ContainerViewController","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)ContainerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerViewController","kind":"identifier"}],"role":"symbol","title":"ContainerViewController","modules":[{"name":"SupportSDK"}],"roleHeading":"Class","symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController"},"kind":"symbol","references":{"doc://com.zendesk.SupportSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIStateRestoring"},"doc://com.zendesk.SupportSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/CoordinatingViewController":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoordinatingViewController","kind":"identifier"}],"role":"symbol","title":"CoordinatingViewController","abstract":[],"navigatorTitle":[{"text":"CoordinatingViewController","kind":"identifier"}],"url":"\/documentation\/supportsdk\/coordinatingviewcontroller","kind":"symbol"},"doc://com.zendesk.SupportSDK/objc(cs)UIViewController":{"title":"UIViewController","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)UIViewController"},"doc://com.zendesk.SupportSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIContentContainer"},"doc://com.zendesk.SupportSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSExtensionRequestHandling"},"doc://com.zendesk.SupportSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.zendesk.SupportSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/initWithCoder:":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/initWithCoder:","title":"initWithCoder:","url":"\/documentation\/supportsdk\/containerviewcontroller\/initwithcoder:","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController":{"navigatorTitle":[{"text":"ContainerViewController","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerViewController","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","title":"ContainerViewController","kind":"symbol","url":"\/documentation\/supportsdk\/containerviewcontroller"},"doc://com.zendesk.SupportSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/5UIKit23UITraitChangeObservableP"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"},"doc://com.zendesk.SupportSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/initWithNibName:bundle:":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/initWithNibName:bundle:","title":"initWithNibName:bundle:","url":"\/documentation\/supportsdk\/containerviewcontroller\/initwithnibname:bundle:","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/viewDidLoad()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/viewDidLoad()","title":"viewDidLoad()","url":"\/documentation\/supportsdk\/containerviewcontroller\/viewdidload()","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.zendesk.SupportSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UITraitEnvironment"},"doc://com.zendesk.SupportSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP"},"doc://com.zendesk.SupportSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIAppearanceContainer"},"doc://com.zendesk.SupportSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSCoding"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerViewController/ContainerChildControllerDelegate-Implementations":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/ContainerChildControllerDelegate-Implementations","title":"ContainerChildControllerDelegate Implementations","url":"\/documentation\/supportsdk\/containerviewcontroller\/containerchildcontrollerdelegate-implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic"},"doc://com.zendesk.SupportSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"title":"ContainerChildControllerDelegate","url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","role":"symbol","navigatorTitle":[{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.SupportSDK/s8CopyableP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ContainerViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ContainerViewController","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ContainerViewController"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/initWithCoder:","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/initWithNibName:bundle:","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/viewDidLoad()"],"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerViewController\/ContainerChildControllerDelegate-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From"},{"type":"inheritedBy","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/CoordinatingViewController"],"kind":"relationships","title":"Inherited By"},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate"],"kind":"relationships","title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/title","op":"replace","value":"ZDKCoordinatingViewController"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKCoordinatingViewController"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1CoordinatingViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKCoordinatingViewController"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/title","op":"replace","value":"ContainerViewController"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContainerViewController"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ContainerViewController"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerViewController~1viewDidLoad()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title","op":"replace","value":"ZDKContainerChildControllerDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments","op":"replace","value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}]}]}]}