{"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator\/start(present:with:)"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestCoordinator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"RequestCoordinator","kind":"identifier"}],"role":"symbol","title":"RequestCoordinator","roleHeading":"Class","externalID":"c:@M@SupportSDK@objc(cs)RequestCoordinator","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestCoordinator"}],"modules":[{"name":"SupportSDK"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/requestcoordinator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/requestcoordinator"]}],"references":{"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestCoordinator/start(present:with:)":{"url":"\/documentation\/supportsdk\/requestcoordinator\/start(present:with:)","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator\/start(present:with:)","type":"topic","title":"start(present:with:)","navigatorTitle":[{"kind":"identifier","text":"startWithPresent:with:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"present","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ContainerChildController","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator":{"url":"\/documentation\/supportsdk\/coordinator","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator","title":"Coordinator","navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestCoordinator":{"url":"\/documentation\/supportsdk\/requestcoordinator","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator","type":"topic","title":"RequestCoordinator","navigatorTitle":[{"kind":"identifier","text":"RequestCoordinator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestCoordinator"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RequestCoordinator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RequestCoordinator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RequestCoordinator"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestCoordinator\/start(present:with:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RequestCoordinator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator~1start(present:with:)\/title","value":"startWithPresent:with:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator~1start(present:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startWithPresent:with:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/title","value":"ZDKCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/fragments","value":[{"text":"ZDKCoordinator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKCoordinator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/title","value":"RequestCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/fragments","value":[{"text":"RequestCoordinator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestCoordinator\/navigatorTitle","value":[{"text":"RequestCoordinator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}