{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate"},"metadata":{"title":"ZDKCreateRequestUIDelegate","roleHeading":"Protocol","modules":[{"name":"SupportSDK"}],"symbolKind":"protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}],"externalID":"c:objc(pl)ZDKCreateRequestUIDelegate","navigatorTitle":[{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Delegate for the create request view.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonImage()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonLocalizedLabel()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/navBarCreateRequestUIType()"],"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkcreaterequestuidelegate"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate/navBarCreateRequestUIType()":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/navBarCreateRequestUIType()","navigatorTitle":[{"kind":"identifier","text":"navBarCreateRequestUIType"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navBarCreateRequestUIType"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNavBarCreateRequestUIType","text":"ZDKNavBarCreateRequestUIType"}],"title":"navBarCreateRequestUIType()","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/navbarcreaterequestuitype()","required":true,"abstract":[{"text":"To conform implementations should return the request creation UI type desired.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}],"role":"symbol","kind":"symbol","title":"ZDKCreateRequestUIDelegate","navigatorTitle":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}],"url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate","type":"topic","abstract":[{"text":"Delegate for the create request view.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate/createRequestBarButtonLocalizedLabel()":{"role":"symbol","abstract":[{"text":"To conform implementations should return a localized string for the right nav bar button title.","type":"text"}],"required":true,"title":"createRequestBarButtonLocalizedLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createRequestBarButtonLocalizedLabel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"createRequestBarButtonLocalizedLabel"}],"type":"topic","kind":"symbol","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonlocalizedlabel()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonLocalizedLabel()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKCreateRequestUIDelegate/createRequestBarButtonImage()":{"role":"symbol","abstract":[{"text":"To conform implementations should return an image for the right nav bar button.","type":"text"}],"required":true,"title":"createRequestBarButtonImage()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createRequestBarButtonImage"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"createRequestBarButtonImage"}],"type":"topic","kind":"symbol","url":"\/documentation\/supportsdk\/zdkcreaterequestuidelegate\/createrequestbarbuttonimage()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonImage()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ZDKCreateRequestUIDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKCreateRequestUIDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonImage()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/createRequestBarButtonLocalizedLabel()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKCreateRequestUIDelegate\/navBarCreateRequestUIType()"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1navBarCreateRequestUIType()\/title","value":"navBarCreateRequestUIType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1navBarCreateRequestUIType()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"navBarCreateRequestUIType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/title","value":"ZDKCreateRequestUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKCreateRequestUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonLocalizedLabel()\/title","value":"createRequestBarButtonLocalizedLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonLocalizedLabel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createRequestBarButtonLocalizedLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonImage()\/title","value":"createRequestBarButtonImage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKCreateRequestUIDelegate~1createRequestBarButtonImage()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createRequestBarButtonImage","kind":"identifier"}]}]}]}