{"abstract":[{"type":"text","text":"Error description for empty Help Center."}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"SupportSDK"}],"roleHeading":"Global Variable","title":"ZDKHelpCenterEmptyHelpCenterDescription","role":"symbol","externalID":"c:@ZDKHelpCenterEmptyHelpCenterDescription"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterEmptyHelpCenterDescription"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenteremptyhelpcenterdescription"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenteremptyhelpcenterdescription"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterEmptyHelpCenterDescription":{"type":"topic","title":"ZDKHelpCenterEmptyHelpCenterDescription","navigatorTitle":[{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"}],"abstract":[{"type":"text","text":"Error description for empty Help Center."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterEmptyHelpCenterDescription","url":"\/documentation\/supportsdk\/zdkhelpcenteremptyhelpcenterdescription","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"ZDKHelpCenterEmptyHelpCenterDescription"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterEmptyHelpCenterDescription","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterEmptyHelpCenterDescription"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterEmptyHelpCenterDescription\/title","op":"replace","value":"ZDKHelpCenterEmptyHelpCenterDescription"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterEmptyHelpCenterDescription\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterEmptyHelpCenterDescription"}]}]}]}