{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenternosectionslocaliseddescription"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenternosectionslocaliseddescription"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoSectionsLocalisedDescription"},"abstract":[{"text":"Error description for section id error.","type":"text"}],"sections":[],"metadata":{"roleHeading":"Global Variable","modules":[{"name":"SupportSDK"}],"externalID":"c:@ZDKHelpCenterNoSectionsLocalisedDescription","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterNoSectionsLocalisedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","title":"ZDKHelpCenterNoSectionsLocalisedDescription","symbolKind":"var"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterNoSectionsLocalisedDescription":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoSectionsLocalisedDescription","abstract":[{"type":"text","text":"Error description for section id error."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"}],"role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenternosectionslocaliseddescription","title":"ZDKHelpCenterNoSectionsLocalisedDescription"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ZDKHelpCenterNoSectionsLocalisedDescription"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoSectionsLocalisedDescription\/title","value":"ZDKHelpCenterNoSectionsLocalisedDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoSectionsLocalisedDescription\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterNoSectionsLocalisedDescription"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}