{"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"SupportSDK"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"ZDKNavBarCreateRequestUIType","externalID":"c:@E@ZDKNavBarCreateRequestUIType","role":"symbol","navigatorTitle":[{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display request creation."}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/s15BitwiseCopyableP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH","doc:\/\/com.zendesk.SupportSDK\/SY","doc:\/\/com.zendesk.SupportSDK\/s8SendableP"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdknavbarcreaterequestuitype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdknavbarcreaterequestuitype"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/image","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/localizedLabel"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/Equatable-Implementations","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"references":{"doc://com.zendesk.SupportSDK/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s8SendableP","title":"Swift.Sendable"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/image":{"abstract":[{"type":"text","text":"Nav bar button with image for request creation."}],"type":"topic","navigatorTitle":[{"text":"ZDKNavBarCreateRequestUITypeImage","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/image","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/image","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"}],"title":"ZDKNavBarCreateRequestUIType.image"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/Equatable-Implementations":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/equatable-implementations","abstract":[]},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH"},"doc://com.zendesk.SupportSDK/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType":{"role":"symbol","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","title":"ZDKNavBarCreateRequestUIType","abstract":[{"type":"text","text":"Enum to describe the types of nav bar button that display request creation."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/init(rawValue:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/init(rawvalue:)","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","type":"topic","url":"\/documentation\/supportsdk","role":"collection"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/localizedLabel":{"abstract":[{"type":"text","text":"Nav bar button with localized label for request creation."}],"title":"ZDKNavBarCreateRequestUIType.localizedLabel","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUITypeLocalizedLabel"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/localizedLabel","role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/localizedlabel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedLabel"}],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/RawRepresentable-Implementations":{"url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/rawrepresentable-implementations","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"title":"RawRepresentable Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ZDKNavBarCreateRequestUIType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/image","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/localizedLabel"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1image\/title","value":"ZDKNavBarCreateRequestUITypeImage"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1image\/fragments","value":[{"text":"ZDKNavBarCreateRequestUITypeImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/title","value":"ZDKNavBarCreateRequestUIType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/fragments","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1localizedLabel\/title","value":"ZDKNavBarCreateRequestUITypeLocalizedLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1localizedLabel\/fragments","value":[{"text":"ZDKNavBarCreateRequestUITypeLocalizedLabel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}